### ISSUE TITLE
Loading new objects even when scrolling up or a bit down, why?

### ISSUE THREAD

**Issue by bandzgla** [metafizzy/infinite-scroll#143]
Hi im using this infinite scroll connected with masonry and I have issues:

 It's loading new objects even when I scroll up.

Another problem is that even if I only slightly slide the scroll down and it loads the new content. It seems to me that it should load it only when the scrollbar get to the bottom of the window (or close to it).

And last thing, how to make all animations off? when I'm deleting code responsible for animations it make diferent one instead... like as example in google chrome object fly from upper left corner...

Any help would be appreciated.

**Comment by fabianp** [comment]
@coryalder: adding the DOCTYPE solved my problem!
