### ISSUE TITLE
Manual triggering threshold

### ISSUE THREAD

**Issue by spaceknight** [metafizzy/infinite-scroll#176]
Hello,

I would like to trigger manual mode after X automatic scrolls. Facebook has such a behaviour.

One downside of infinite auto scroll on our site is that the visitor almost never reaches the footer of the site and cannot click any of the links in the footer. Assuming that we have 1000+ pages, this looks impossible.

So, let's say after 3 scrolls, I would like to append a manual trigger element with "Click to load more items" text and trigger the loading of next page.

Can this be done?

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I've documented an [example of how to disable loading with scrolling and rely on loading with a button.](https://infinite-scroll.com/extras.html#scroll-2-pages-then-load-with-button) 

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
