### ISSUE TITLE
JS Hover with Infinite Scroll

### ISSUE THREAD

**Issue by 1b4ugo** [metafizzy/infinite-scroll#200]
I am working on a site that contains a list of product images. When a visitor hovers over a product, the behavior is similar to the google images hover behavior. I have incorporated the infinite-scroll plugin and the scroll works fine, however once I scroll down and the new products are loaded, the hover for the new loaded images no longer works. The hover is completely controlled by js. Any ideas on how to get this to work?

**Comment by samb172** [comment]
I'm suffering a similar issue but the callback function has/hasn't solved it. 

When you hover the first 10, the hover works fine. However when you load the next 5 via infinite scroll they work but the first 10 now don't hover. 

Scroll for the final 5 and now the first 10 hover fine but the middle 5 don't hover and if you scroll with one of the squares hovered on, it stays on even when you hover away.

`

     (function() {

        // Main content container
        var $container = jQuery('.cont_panel.js-clients');

        // Masonry + ImagesLoaded
        $container.imagesLoaded(function(){
            $container.masonry({
                // selector for entry content
                layoutMode: 'masonry',
                columnWidth: '.grid-sizer',
                itemSelector: '.cont_panel__img.grid-item',
            });
        });

        // Infinite Scroll
        $container.infinitescroll({
            // selector for the paged navigation (it will be hidden)
            navSelector  : ".page-numbers",
            // selector for the NEXT link (to page 2)
            nextSelector : ".next.page-numbers",
            // selector for all items you'll retrieve
            itemSelector : ".cont_panel__img.grid-item",

            // finished message
            loading: {
                finishedMsg: 'No more pages to load.'
                }
            },

            // Trigger Masonry as a callback
            function( newElements ) {
                // hide new items while they are loading
                var $newElems = jQuery( newElements ).css({ opacity: 0 });
                // ensure that images load before adding to masonry layout
                $newElems.imagesLoaded(function(){
                    // show elems now they're ready
                    $newElems.animate({ opacity: 1 });
                    $container.masonry( 'appended', $newElems, true );
                });

                jQuery('.cont_panel__img').hover(function() {
                    jQuery(this).toggleClass('active');
                    jQuery(this).siblings().toggleClass('inactive');
                    jQuery('.cont_panel__black').toggleClass('active');
                });
            }
        );

        jQuery('.filter li').click(function() {
            var filterValue = jQuery( this ).attr('data-filter');
            $container.isotope({ filter: filterValue });
        });

    })();
`
