### ISSUE TITLE
If the document is smaller than the browser window, infinite scroll is not triggered.

### ISSUE THREAD

**Issue by Prakt** [metafizzy/infinite-scroll#227]
Just playing around with infinite scrolling here with some demo pages. I have a huge (2560x1440px) monitor at work and if the document is smaller than my browser window, infinte scroll is not fired. Resizing the window so that it is smaller than the page and refreshing the page works as intended.

Test page is available on pastebin: http://pastebin.com/wee5BcZJ

**Comment by SivakumarMurugan** [comment]
$("#wrapper").css("min-height",($(window).height() + 5));
or
$(body).css("min-height",($(window).height() + 5));

I fixed using this.

**Comment by dgafz** [comment]
It has happened to some that when you concatenate the new data, the scroll returns to the beginning of the page
