### ISSUE TITLE
Would replacing/removing old pages help improve performance?

### ISSUE THREAD

**Issue by ghost** [metafizzy/infinite-scroll#300]
After loading many pages, especially ones with images, it seems one common issue with infinite scroll is that increasing memory usage begins to negatively affect the browsing experience, as the scrolling becomes much jerkier and there's a higher chance for the browser to crash. I was wondering if adding an option to limit the number of "present" pages and discard everything else that goes beyond that number limit would help mitigate this in any way. I saw this option in another endless scroll plugin but didn't get a chance to test it.

 https://github.com/fredwu/jquery-endless-scroll/blob/master/README.md
(parameter 'pagesToKeep' : The number of 'pages' to keep before either end of the scrolling content are discarded, by default (value set to `null`) no content will be discarded.)

Would be interested to hear what others think.

**Comment by charanjit-singh** [comment]
Thanks
