### ISSUE TITLE
Infinite Scroll + WP_Query (WordPress) orderby RANDOM creates duplicates

### ISSUE THREAD

**Issue by zumajoe** [metafizzy/infinite-scroll#318]
If you randomize the order in which your posts are pulled, infinite scroll creates duplicate entries of posts.  Tested without infinite scroll and there are no duplicates.

```
$args = array(
'post_type' => array(
            'post',
            'portfolio',
        ),

'posts_per_page' => 20,
'orderby' => 'rand',    
'paged' => $paged,
'caller_get_posts'=> 1,
);
$wp_query = new WP_Query( $args );
```

Also seems to be happening with Drupal:  http://drupal.org/node/1655346

**Comment by msshohan** [comment]
Do you have any fix for this issue? I am getting this issue as well. When I disable Infinite Scroll the pagination doesn't have any duplicate posts. But duplicate posts appear when Infinite Scroll is enabled.

This is exactly what happens:

I have 2 featured posts in a different query without any infinite scroll. Then below that, I have another WP_Query but with infinite scroll. The infinite scroll loads those 2 featured posts every time a new set of posts are scrolled. That means only the duplicate of the first wp_query or featured posts is created. The second page don't show these duplicate posts if we disable Infinite Scroll.
