### ISSUE TITLE
ipad scrolling

### ISSUE THREAD

**Issue by coldlamper** [metafizzy/infinite-scroll#375]
I have an issue where the ipad will stop scrolling. the infinite scroller just stops, no javascript errors are thrown. If I scroll slow i can get thru everything,but you have to go pretty slow. 
Works on desktops fine.

I was trying to go thru the code and find out where the issue is and noticed if i comment out 

opts.loading.msg.fadeOut(opts.loading.speed);

it's really hard to break the scroller, but when that's left in it is really easy to break it.

Any ideas? Thanks

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
