### ISSUE TITLE
the plugin will not fire again ones it gets to the bottom

### ISSUE THREAD

**Issue by kulldox** [metafizzy/infinite-scroll#376]
I'm trying to use the jQuery infinitescroll plugin for search results. Everything is working fine excepting the fact that after I do scroll to the bottom (no results anymore) and want to search for  something else the plugin doesn't fire anymore. I can't figure out from the code why. I've tried even to call it again upon search form submit, no luck. Any suggestions? Thanks.

**Comment by firsh** [comment]
I have the same problem with the same case(search form).

@jacopotarantino it sounds like we have a problem with plugin, not the implementation. 

> So I guess it doesn't want to run the _create method.

Yes, its not getting reinit correctly and it was mistake to close the issue.

**Comment by firsh** [comment]
This workaround allow to init after destroy:
#654
