### ISSUE TITLE
Does not work with jquery mobile 

### ISSUE THREAD

**Issue by nikhilvij** [metafizzy/infinite-scroll#378]
This works great otherwise but doesn't seem to work when I include jquery mobile as well.
The ajax call itself is not fired on reaching the end of the page.
If i exclude the jquery mobile file, it works great

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
