### ISSUE TITLE
InfiniteScrolling with additional parameters?

### ISSUE THREAD

**Issue by confile** [metafizzy/infinite-scroll#422]
I use the plugin with

``` javascript
        path: function generatePageUrl(currentPageNumber) { 
            var uri = $container.attr("dataUrl");
            return (uri + currentPageNumber); 
        },
```

The problem is that I get urls like this: 

http://someurl?page=1
http://someurl?page=2
http://someurl?page=3
http://someurl?page=4
http://someurl?page=5

The problem is that I need to send additional parameter in each request like:

http://someurl?page=1&offset1=10&offset2=30
http://someurl?page=2&offset1=15&offset2=55

I want to send these additional parameters in the (ajax) request that is sent from the server to the client. Is it somehow possible that the plugin adds this parameters to the next request as url parameters?

**Comment by arbadzukhron** [comment]
lah gimana ini, yg mulai diskusi siapa tapi yg close diskusi siapa
