### ISSUE TITLE
instance.options.contentSelector.height is not a function

### ISSUE THREAD

**Issue by null-null-null** [metafizzy/infinite-scroll#432]
When I enable the prefill option, I get this error:

```
instance.options.contentSelector.height is not a function
```

Any idea what's causing this? I'm using the latest version of infinite-scroll.

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
