### ISSUE TITLE
Make infinite scroll work with another js plugin

### ISSUE THREAD

**Issue by learningcurves** [metafizzy/infinite-scroll#436]
I have a plugin that pretty much looks like this in my body tag.

```
<script src="https://raw.github.com/davist11/jQuery-Stickem/master/jquery.stickem.js"></script>

<script>
$('.stickem-container').stickem();
</script>
```

However it doesn't work once the scrolling loads a new page. I don't know jQuery, but I searched for it here and the issue seems to be that scripts will be stripped out and you have to use some sort of a callback function or include the in the selector to make it work? 

How do I do that exactly? I am sorry that I don't seem to know what I'm doing. I don't, I just like the plugin a lot and I'd like to use it even though I don't understand how it works. Thanks!

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
