### ISSUE TITLE
Issues with IE8/9

### ISSUE THREAD

**Issue by mikesmithson** [metafizzy/infinite-scroll#437]
When using IE8/9 and dragging the browser scrollbar, the infinite scroll plugin fires. The loading message does not hide if the scrollbar remains at the same position. If you move the scrollbar again, the message disappears. In Chrome, Firefox, Opera, Safari, and IE10, this behavior is not observed.

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 supports IE11+. Sorry I won't be able to debug this issue.

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
