### ISSUE TITLE
More IE8 weirdness

### ISSUE THREAD

**Issue by mikesmithson** [metafizzy/infinite-scroll#439]
We are using the plugin on a page where the items to display are &lt;li&gt; items that are children of a single &lt;ul&gt;. The loading message shows after the first set of cont. scroll items are fetched. Any other triggering of the cont. scroll plugin afterwards does not show any loading message indication. Please advise.

Thanks

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 supports IE11+. Sorry I won't be able to debug this issue.

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
