### ISSUE TITLE
Suggested desturl calculation

### ISSUE THREAD

**Issue by ChristopherBrand** [metafizzy/infinite-scroll#444]
On my implementation the url generation didn't work optimally as I used dates rather than page numbers to fetch the next page.  Since each new pull grabbed the next page link as well I simply changed the desturl calculation to fetch the href of the last opts.nextSelector on the page.  It works perfectly.  It might be a nice configurable option.

desturl = (typeof path === 'function') ? path(opts.state.currPage) : $(opts.nextSelector).last().attr('href');

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

You can set [`path` to a function](https://infinite-scroll.com/options.html#path) to return a string of the next page URL.

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
