### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by wpexplorer** [metafizzy/infinite-scroll#446]
Where can I donate to support your awesome work?

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

You can support Infinite Scroll by purchasing a [Commercial License](https://infinite-scroll.com/#commercial-license). Thank you for your enthusiasm!
