### ISSUE TITLE
Loading another section before the next page?

### ISSUE THREAD

**Issue by LiamDawe** [metafizzy/infinite-scroll#448]
On my website each post has a separator div below it, how exactly would I get this separator div to load before each new page?

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
