### ISSUE TITLE
Any way I can create Facebook like ticker with json callback data

### ISSUE THREAD

**Issue by tusharvikky** [metafizzy/infinite-scroll#452]
Hello,

Any help, I wanted to create a facebook like rightsidebar ticker which callbacks to a certain url and fetch json data and load it into the sidebar exactly like infinite scroll.
[Already using this plugin in the same page as main view.]

Regards,
tusharvikky

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

[See Loading JSON with v3](https://infinite-scroll.com/extras.html#loading-json)

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
