### ISSUE TITLE
strange img loadimage animation

### ISSUE THREAD

**Issue by koyotee** [metafizzy/infinite-scroll#455]
Hello there,
my load image just fades in on first reload but on the following reloads it does a size-animation from left bottom to right top. Is there a way to control or style this animation.
Here is the style:
# infscr-loading{

```
position:fixed;
bottom:20px;
left:50%;
```

}
you can also take a look at:
http://lovlylinks.tumblr.com/

I guess I have to change something in the source as mentioned here (https://github.com/paulirish/infinite-scroll/issues/91) but I couldnt get anything out of this.

thanks for any advice.

**Comment by mhulse** [comment]
Thanks for your solution @mh-nichts!

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 has a new setup for loading and status elements. [See `status` option](https://infinite-scroll.com/options.html#status). This uses your own HTML.

``` html
<div class="page-load-status">
  <p class="infinite-scroll-request"><img src="/img/loading.gif" alt="Loading..." /></p>
  <p class="infinite-scroll-last">End of content</p>
  <p class="infinite-scroll-error">No more pages to load</p>
</div>
```

``` js
status: '.page-load-status'
```

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
