### ISSUE TITLE
"Next" link page count is overridden

### ISSUE THREAD

**Issue by dgb75** [metafizzy/infinite-scroll#460]
I have a "next" link where the page count is being overridden when making a JSON call. The page count on my site API starts from 0, not 1. Despite this, infinite-scroll overrides the link URL's request for page=1 and instead sends page=2. At no point within the DOM are there any references to page=2. This is wholly internal to infinite-scroll.

**Comment by desandro** [comment]
Thank you for reporting this issue.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 has better `path` parsing, so your page numbers are maintained. I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
