### ISSUE TITLE
How to return to the same scroll position when using browser's back button?

### ISSUE THREAD

**Issue by chaonextdoor** [metafizzy/infinite-scroll#467]
If I use infinite-scroll to scroll down deeply somewhere on the page, and then click on a link to go to another page, when I click on the back button of the browser, I want to go to exactly the same position when I was on the previous page. But right now, it seems that this is not the case. What should I do to achieve this?

**Comment by desandro** [comment]
Thank you for this feature request. Infinite Scroll v3 has been released with support!

See my comment at https://github.com/metafizzy/infinite-scroll/issues/337#issuecomment-311130015

**Comment by grapeba** [comment]
Hi

Thanks for this amazing lib, i know that the V3 now support going back with back button to retain position, however i have used it to turn wordpress pagination to infinite scroll, but when i go back it only loads page that user was on.

Is it possible for instance when user hits back on page 4 it shows him pages before that also, like 1,2,3, and current 4 position.

**Comment by Macro-Jackson** [comment]
No, not at the moment. See ticket #728.
I really would like this feature too.

**Comment by grapeba** [comment]
> No, not at the moment. See ticket #728.
> I really would like this feature too.

Its very hard to find working IS that has this, if this is not possible can we somehow make that generated DOM is saved in browser memory instead?
