### ISSUE TITLE
Infinite scroll with masonry in woocommerce not working.

### ISSUE THREAD

**Issue by abude** [metafizzy/infinite-scroll#469]
Hi there!

Thank you for your support and all the great work.
I'm facing a nasty problem with integrating the infinite scroll plugin in wordpress with the theme that is using masonry.

i have the last version of infinite scroll, 2.6.2 
i added this code in the call back:

// hide new items while they are loading
var $newElems = jQuery(newElements).css({ opacity: 0 });
// ensure that images load before adding to masonry layout
$newElems.imagesLoaded(function(){
// show elems now they're ready
$newElems.animate({ opacity: 1 });
$container.masonry( 'appended', $newElems, true );
});

but it's not working, it adds the opacity to the new <li> elements but it's not adding the positions ... etc, so not quite working the new <li> are going on the top of the page over the old products <li>.

script looks like:

/\* <![CDATA[ _/
var infinite_scroll = "{\"loading\":{\"msgText\":\"<em>Loading...<\\/em>\",\"finishedMsg\":\"<em>No additional products.<\\/em>\",\"img\":\"http:\\/\\/www.test.com\\/wp-content\\/plugins\\/infinite-scroll\\/img\\/ajax-loader.gif\"},\"nextSelector\":\".next\",\"navSelector\":\".woo-pagination\",\"itemSelector\":\"li.product\",\"contentSelector\":\"ul.products\",\"debug\":false,\"behavior\":\"\",\"callback\":\"\\/\\/ hide new items while they are loading\r\nvar $newElems = jQuery(newElements).css({ opacity: 0 });\r\n\\/\\/ ensure that images load before adding to masonry layout\r\n$newElems.imagesLoaded(function(){\r\n\\/\\/ show elems now they're ready\r\n$newElems.animate({ opacity: 1 });\r\n$container.masonry( 'appended', $newElems, true );\r\n});\"}";
/_ ]]> */

the masonry looks like:

```
                            // Only fire masonry if the window is an appropriate size and images are loaded
                            jQuery(function(){
                                var $container = jQuery('ul.products');
                                $container.imagesLoaded( function(){
                                    if (jQuery(window).width() > 767) {
                                        $container.masonry({
                                            itemSelector : 'li.product',
                                            columnWidth : 295,
                                            isFitWidth: true,
                                            gutterWidth : 2
                                        });
                                    }
                                });
                            });
```

any idea please?

**Comment by desandro** [comment]
Thank you for reporting this issue.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

[Infinite Scroll v3 has direct integration with Masonry with the `outlayer` option](https://infinite-scroll.com/options.html#outlayer). I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
