### ISSUE TITLE
Behaviour is not working with IE 8

### ISSUE THREAD

**Issue by adasite** [metafizzy/infinite-scroll#474]
Hi, I couldn't test your script with other IE versions but the new behaviour (e.g. Twitter) is not working with IE 8. The same configuration works fine with Chrome and Firefox.

When I remove behaviour, it's OK with IE 8 as well. But beware that while min version of jquery.infinitescroll works fine with Chrome and Firefox, it does not with IE 8. I had to use the developer version of the .js file to make it work with IE 8. The behaviour still didnt't work though. I hope there is a solution for this, thanks in advance. 

Here is the code I use:

```
<div class="fetch"><?php next_posts_link( __( 'Load More', 'theme' ) ); ?></div>
<script type="text/javascript">
$('#yukle').infinitescroll({
navSelector  : ".fetch",
nextSelector : ".fetch a:first",
itemSelector : "#yukle .kart",
loading: { msgText: "Loading...", 
finishedMsg: "End of posts",
img:"loading.gif", 
speed: 'fast'},
behavior: 'twitter',
});
</script>
```

**Comment by nmacd85** [comment]
I have this issue now and was testing with IE10. Works with Chrome and FF though, and no following ",". 

"Working" example at http://epicreads-dev.tumblr.com

**Comment by desandro** [comment]
Thank you for reporting this issue.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 supports IE/Edge 11+.

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
