### ISSUE TITLE
Pagination Regex Interferes with IP address [bug] + Lack of "starting page" or Zero-Based counter support [feature request]

### ISSUE THREAD

**Issue by jvanasco** [metafizzy/infinite-scroll#478]
So a few issues here.  They seem tied to https://github.com/paulirish/infinite-scroll/issues/6 and https://github.com/paulirish/infinite-scroll/issues/460
- When trying to set up an ajax infinite scroll, the lib made me default to an absolute url ( with FQDN or IP address ) and would not accept a relative url.  Not a big deal [ would have been nice to see this documented ]
- When I started with an infinite scroll, it kept breaking.  I finally figured out why. It was a combination of the URL and having a Zero-based counter for pages.
  
  // infinite scroll doesn't like zero based pages!
  var url = "http://127.0.0.1/api/call?page=1"
  ["determinePath", Array[2]  ]
      0: "http://1"
      1: "7.0.0.1/api/call?page=1"
  
  // infinite scroll does like 1 based pages!
  var url = "http://127.0.0.1/api/call?page=2"
  ["determinePath", Array[2]  ]
      0: "http://127.0.0.1/api/call?page="
      1: ""
  
  // want to start on page 5? NO YOU CAN NOT!
  var url = "http://127.0.0.1/api/call?page=5"
  ["determinePath", Array[2]  ]
      0: "http://1"
      1: "7.0.0.1/api/call?page=5"

Attached is a jsfiddle.  It defaults to creating the error ( on page=1 ).  You can see that by increasing the next page to "2", everything works fine.  if you go to 3 or above, it breaks again.

http://jsfiddle.net/w8vnb/

Note: you have to open the browser console to see the the logged messages

I think this all this could be elegantly fixed by allowing for a "start page" setting.  If the infinite scroll is initialized with a start-page of "0", then the "next page" is 1; if it starts with page "5", then 6.  If you do nothing, no worries.

**Comment by desandro** [comment]
Thank you for reporting this issue.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 has better parsing and use of page numbers. You can use relative paths. You can start on latter pages, not just the first. See [`pageIndex` property](https://infinite-scroll.com/api.html#pageindex)

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
