### ISSUE TITLE
Virtuemart

### ISSUE THREAD

**Issue by sofianosg** [metafizzy/infinite-scroll#484]
Is there a way to make it work in virtuemart?
I have  4 products per row . When i choose for itemselector the 'product class' or the 'row' class i get the message 'Sorry, we couldn't '

Any ideas?

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
