### ISSUE TITLE
Custom Selector 

### ISSUE THREAD

**Issue by birkoff** [metafizzy/infinite-scroll#490]
As a developer I would like to implement infinite scroll in my application using a custom attribute selector other than "href"

Currently we only can use href as attribute selector

Example:

``` js
$.infinitescroll.defaults = {
        attSelector: "rel",
        navSelector: "div.navigation",
        contentSelector: null, // rename to pageFragment
        itemSelector: "div.post"
};
```

**Comment by desandro** [comment]
Thank you for this feature request. Looks like it didn't get much additional interest. Sorry, we'll have to pass on this one.
