### ISSUE TITLE
Using infinite scroll with Masonry and Flexslider

### ISSUE THREAD

**Issue by genethic** [metafizzy/infinite-scroll#498]
I'm using masonry jQuery plugin and loading content with infinite scroll, and in this content a I have differents FlexSlider slideshows. When I use the infinite scroll, the slider doesn't show correctly, the next post is positioned just in the same place, like masonry doesn't load the flexslider post.. I suppouse that the FlexSlider jQuery doesn't load well with infinite scroll.

Like you can see, I append new elements to Masonry after load infinete scroll, and imageLoader and prettyPhoto, too. I have try to doing something like this with FlexSlider, but nothing. How can I achieve this? Help please!
This is the code:

FlexSlider:

``` php
jQuery(document).ready(function ($) {
    $(\'#' . $id . '\').flexslider({
    namespace: "flex-",  
    selector: ".slides > li",
    animation: "' . $animation_effect . '",
    direction: "horizontal",  
    animationLoop: true,  
    slideshow: true,  
    slideshowSpeed:' . $slideshow_speed . ',
    animationSpeed:' . $animation_speed . ',
    pauseOnAction: true,  
    pauseOnHover: true,  
    useCSS: true,  
    touch: true,  
    video: true,  
    controlNav: false,  
    directionNav: false, 
    prevText: "",  
    nextText: "",
    });});
```

Masonry + Infinite scroll:

``` js
jQuery(document).ready(function($){
var $container = $('#masonry-content');
$container.imagesLoaded(function(){
              $container.masonry({
                itemSelector: 'article',
                columnWidth: 1,
              });
            });


        $container.infinitescroll({
          navSelector  : '.archive-nav',    // selector for the paged navigation 
          nextSelector : '.archive-nav .next',  // selector for the NEXT link (to page 2)
          itemSelector : '#masonry-content article',     // selector for all items you'll retrieve
          loading: {
              finishedMsg: 'No more pages to load.',
              img: 'http://i.imgur.com/6RMhx.gif',
              msgText:'',
            }
          },
          // trigger Masonry as a callback
          function( newElements ) {
            // hide new items while they are loading
            var $newElems = $( newElements ).css({ opacity: 0 });
            // ensure that images load before adding to masonry layout
            $newElems.imagesLoaded(function(){
              // show elems now they're ready
              $newElems.animate({ opacity: 1 });
              $container.masonry( 'appended', $newElems, true ); 
               $("a[rel^='prettyPhoto']").prettyPhoto();
               $('#slider-74').flexslider();
              });
          });
        <?php } ?>
    });
```

**Comment by desandro** [comment]
Thanks for reporting this issue. Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

[Infinite Scroll v3 has direct support for Masonry.](https://infinite-scroll.com/options.html#outlayer) I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
