### ISSUE TITLE
Detecting last page when soft 404 given

### ISSUE THREAD

**Issue by DeeEmm** [metafizzy/infinite-scroll#499]
I am creating a plugin to adapt infinitescroll to work with Hikashop. Everything is now functional except for one minor issue that I cannot seem to figure out. (javascript is not my forte)

The issue I have is that when scrolling past the last page instead of seeing the 'you have reached the end of the internets...' message, the script tries to retrieve another page and displays the 'Loading the next set of posts...' message. It will keep doing this for as long as you care to try.

Here's what I think the issue is...

When trying to retrieve a page that does not exist Joomla returns a 404 information page with a 200 error response. This lack of a hard 404 error response is preventing the instance from being stopped when the last page is reached.

Here's what I cannot figure out (due to aforementioned lack of JavaScript-fu)...

How I can detect the last page by another method.

I have tried to test the data variable to check it's contents but it is not empty - this is actually expected as the soft 404 page actually does have contents - it's a normal joomla page but it's just missing the hikashop elements.  However, try as hard as I might I cannot seem to get my head around how to isolate the page elements within the content_selector from the next page.

Am I on the right track? or is there an easier way to achieve what I am trying. Is there an easier way to catch soft 404's?

//link removed as solution found

Any help greatly appreciated.

DM

**Comment by desandro** [comment]
Hello DM! Thanks so much for this suggestion. This behavior has been added to [Infinite Scroll v3, now out](https://infinite-scroll.com)! Infinite Scroll v3 has [`checkLastPage` option](https://infinite-scroll.com/options.html#checklastpage), when enabled it will check for if the `path` pagination element is in the loaded page. There a couple other ways it checks. Thank you for your feedback, it means a lot!

I recommend upgrading to v3. It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2). Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
