### ISSUE TITLE
regex breaks under certain conditions in drupal

### ISSUE THREAD

**Issue by nathangs** [metafizzy/infinite-scroll#500]
Not sure why, but it seems that the regex changes the query string value under certain conditions when using using infinite scroll with drupal 7/views 3.  The href value for the next page link in the markup for my site was:

`<a title="Go to next page" href="/directory?title=&amp;field_organization_type_tid[0]=20&amp;page=1">next ›</a>`

However, the plugin would make an ajax request to the following url:

`<a title="Go to next page" href="/directory?title=&amp;field_organization_type_tid[0]=10&amp;page=1">next ›</a>`

You'll notice the field_organization_type_tid[0] query string value was getting changed for some reason.  I was able to get it working as expected by modifying the script where it performs some regex operations.  Unforunately I'm not advanced enough to understand why this is breaking.

```
_determinepath: function infscr_determinepath(path) {

      var opts = this.options;

      // if behavior is defined and this function is extended, call that instead of default
      if (!!opts.behavior && this['_determinepath_' + opts.behavior] !== undefined) {
        return this['_determinepath_' + opts.behavior].call(this, path);
      }

//      if (!!opts.pathParse) {
//
//        this._debug('pathParse manual');
//        return opts.pathParse(path, this.options.state.currPage + 1);
//
//      } else if (path.match(/^(.*?)\b2\b(.*?$)/)) {
//        path = path.match(/^(.*?)\b2\b(.*?$)/).slice(1);
//
//        // if there is any 2 in the url at all.
//      } else if (path.match(/^(.*?)2(.*?$)/)) {
//
//        // page= is used in django:
//        // http://www.infinite-scroll.com/changelog/comment-page-1/#comment-127
//        if (path.match(/^(.*?page=)2(\/.*|$)/)) {
//          path = path.match(/^(.*?page=)2(\/.*|$)/).slice(1);
//          return path;
//        }
//
//        path = path.match(/^(.*?)2(.*?$)/).slice(1);
//
//      } else {

      // page= is used in drupal too but second page is page=1 not page=2:
      // thx Jerod Fritz, vladikoff
      if (path.match(/^(.*?page=)1(\/.*|$)/)) {
        path = path.match(/^(.*?page=)1(\/.*|$)/).slice(1);
        return path;
      } else {
        this._debug('Sorry, we couldn\'t parse your Next (Previous Posts) URL. Verify your the css selector points to the correct A tag. If you still get this error: yell, scream, and kindly ask for help at infinite-scroll.com.');
        // Get rid of isInvalidPage to allow permalink to state
        opts.state.isInvalidPage = true;  //prevent it from running on this page.
      }
      //}
      this._debug('determinePath', path);
      return path;

    },
```

**Comment by desandro** [comment]
Thanks for reporting this issue. 

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll has better parsing for URLs with parameters. In addition, you can [set `path` with a string](https://infinite-scroll.com/options.html#path) with `{{#}}`:

``` js
path: '/directory?title=&amp;field_organization_type_tid[0]=20&amp;page={{#}}'
```

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻

**Comment by mojeb-smile** [comment]
the problem it's still reproducible in v3

**Comment by desandro** [comment]
@mojeb-smile For complicated URLs with multiple parameters, I recommend using [path with a function](https://infinite-scroll.com/options.html#path)

``` js
path: function() {
  return '/directory?title=&amp;field_organization_type_tid[0]=20&amp;page=' + this.loadCount;
}
```

**Comment by mojeb-smile** [comment]
Hi Desandro,

yes I fixed it by putting the page parameter at the end of my URL like:

<a href="/myurl?title=foo&field_organization_type_tid[0]=20&page=1">Next</a>

Thank you.
