### ISSUE TITLE
Modal window is not working on page 2 of infinite scroll 

### ISSUE THREAD

**Issue by dann2013** [metafizzy/infinite-scroll#501]
Hi,
I try to use modal windows on a page which have infinite scroll implemented, but on the second page the modal don't work. 
Is there a known conflict between modal plugins and infinite scroll plugin ? 
Could you tell me how can I fix this problem ?
Thank you

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻

**Comment by masalewales** [comment]
sir i have same problem...when scroll to 2nd page variations of product not showing.
