### ISSUE TITLE
Default value of appendCallback: true breaks overflow divs with tables

### ISSUE THREAD

**Issue by rschooley** [metafizzy/infinite-scroll#508]
The first load will always error as it checks box for children, but the selector points to the scrollable div and not the table.

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
