### ISSUE TITLE
Your nextSelector found no elements

### ISSUE THREAD

**Issue by al2879** [metafizzy/infinite-scroll#516]
Trying to use infinite-scroll at the development copy of the site
http://www.cablook.com/category/inspiration/
I got error: Your nextSelector found no elements
Settings:
Content Selector - div#cat_posts
Navigation Selector - div#cat_list
Next Selector - a.next (or div#cat_list>ul>li>a.next)
Item Selector - div.cat_post
Debug - true, all others - default values. It's rather strange I can't
get elements #cat_list and a.next from the script but
jQuery('#cat_list').hide(), jQuery('a.next').hide() run in Firebug
works OK. Can someone give an advice?

**Comment by hopita** [comment]
<div class="pagination">
          <?php next_posts_link(); ?>
          <?php previous_posts_link(); ?>
      </div>
Maybe your theme has just '<?php next_posts_link(); ?>'
