### ISSUE TITLE
AMD compatibilty

### ISSUE THREAD

**Issue by szepeviktor** [metafizzy/infinite-scroll#523]
Please consider making your lib AMD friendly.
https://github.com/umdjs/umd

Thank you!!

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 now supports UMD. I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
