### ISSUE TITLE
infinitescroll prefill option doesn't work in some case

### ISSUE THREAD

**Issue by ishikoro2** [metafizzy/infinite-scroll#527]
I'm using infinitescroll with masonry, and infinitescroll often works fine.

However, when I have only about 90px between bottom of the content and the bottom of window, prefill: true doesn't work and I can not get newelements except in the case I resize the window.

If I have larger space between them, it works very fine.

Does anybody know the problem of this issue?

Thank you very much.

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
