### ISSUE TITLE
Multiple columns

### ISSUE THREAD

**Issue by untoreh** [metafizzy/infinite-scroll#537]
Does not work on multiple columns/loops

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 supports multiple instances. I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
