### ISSUE TITLE
(WordPress - not sure if specific to plugin) #infscr-loading breaking layout

### ISSUE THREAD

**Issue by nathanhornby** [metafizzy/infinite-scroll#539]
Due to the way in which the content is loading in the #infscr-loading breaks the layout after the second page is loaded in.

I.e. the layout is like so:

[DIV] [DIV] [DIV]
[A - NEXT PAGE]

After clicking the next page CTA:

[DIV] [DIV] [DIV]
[#infscr-loading]
[DIV] [DIV] [DIV]
[A - NEXT PAGE]

That #infscr-loading in the middle breaks the layout as it messes with the nth selectors and whatnnot (it's set to display:none, but it's still there).

Shouldn't this element just be removed once the content is loaded, and subsequently re-introduced when required?

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

With Infinite Scroll v3, you can set a loading message and/or loading image within a [`status` element's HTML](https://infinite-scroll.com/options.html#status). I recommend putting the status element outside of the container.

``` html
<div class="container">
  <article class="post">...</article>
  <article class="post">...</article>
</div>

<div class="page-load-status">
  <p class="infinite-scroll-request">Loading new posts...</p>
  <p class="infinite-scroll-last">End of content</p>
  <p class="infinite-scroll-error">No more pages to load</p>
</div>
```

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
