### ISSUE TITLE
infinite scroll not triggered on mobile on page load

### ISSUE THREAD

**Issue by zang** [metafizzy/infinite-scroll#542]
$(document).height() always set to the screensize on initial pageload and infinite scroll not get tribgerred on my android galaxy s4. 

And, Here are the mobile related meta tags I got in header:
 meta name="HandheldFriendly" content="True"
meta name="MobileOptimized" content="320"
meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"

Not sure if this is a bug or I done something wrong. Please advise.

thanks,
Lucy

**Comment by KaraAJC** [comment]
Was there a solution that worked for you, @zang ? i'm finding a similar issue with my site, and I'm running into Issues with mobile and tablet scrolling..

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
