### ISSUE TITLE
loading.finished without opts on last scroll when maxPage is set

### ISSUE THREAD

**Issue by stefanomiccoli** [metafizzy/infinite-scroll#547]
I use infinite scroll with the following config:

``` javascript
scrollContainer.infinitescroll({
    loading: {
        finished: function(opts) {
            console.log(opts);
        }
    },
    navSelector: '.paginazione-archivi-N',
    nextSelector: '.paginazione-archivi-N .nav-arrow-right-N',
    itemSelector: '.elemento-infinite-scroll',
    debug: true,
    maxPage: MAX_SCROLL_PAGES, // 3 scrolls
    path: function( pageNumber ){
        return "/ezjscore/call/grazia::getSubChannelEl::" + pageNumber + "::" + scrollContainer.attr('data-channel-id');
    }
},function(newElements, opts, url){
    // something in the callback
}
```

Even if opts.loading.finished is not well documented. i looked in code and found that it defines a callback function, with opts as parameter when loading is completed.
The problem is that the last time it is called (after the last page, when it show "you've reached the end of..." by default), when i expected opts.state.isBeyondMaxPage was true, opts is not defined.
So I cannot bind any operation to the "show congratulation message" event, neither reproduce the default 

``` javascript
opts.loading.finished = opts.loading.finished || function() {
    if (!opts.state.isBeyondMaxPage)
        opts.loading.msg.fadeOut(opts.loading.speed);
};
```

I will add an if condition in callback function where opts.state.currPage == MAX_SCROLL_PAGES and i will obtain the same result, but I suppose it would be cleaner if done in opts.loading.finished if opts where set

I think this is happening because of maxPage is set. In this case infinite scroll is destroyed without calling finished in line ~ 548,

``` javascript
// Manually control maximum page
if ( opts.maxPage !== undefined && opts.state.currPage > opts.maxPage ){
    opts.state.isBeyondMaxPage = true;
    this.destroy();
    return;
}
```

Thank you for the attention and sorry for my poor english,
Stefano.

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 comes with vanilla JS support. Additionally, you can access the instance with `[.data('infiniteScroll')`](https://infinite-scroll.com/api.html#jquery-fn-data-infinitescroll).

The `loading.finished` option method has been replaced with [events](https://infinite-scroll.com/events.html): `request` and `append` or `load`. `maxPage` is no longer supported, but you can reproduce this behavior with code inside an event handler. See similar demo: [Scroll 2 pages then load with button](https://infinite-scroll.com/extras.html#scroll-2-pages-then-load-with-button)

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
