### ISSUE TITLE
jQuery 1.7

### ISSUE THREAD

**Issue by delister** [metafizzy/infinite-scroll#548]
Hi! Not work with jQuery 1.7
error: 
Uncaught Error: Syntax error, unrecognized expression: > jquery.js:4179

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
