### ISSUE TITLE
Scroll up will fire the load event

### ISSUE THREAD

**Issue by marius-t** [metafizzy/infinite-scroll#550]
Hi,

I found a little issue with the scroll, if you have the content in a container and there is a footer present then when you scroll up the loading will fire. 

Thank you

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
