### ISSUE TITLE
Scroll unbinding

### ISSUE THREAD

**Issue by rouvenherzog** [metafizzy/infinite-scroll#555]
Hey,

I have multiple Infinitescroll running on one page and all instances get unbound from the scroll listener once one instance reaches the last page.

I guess including 

++$.infinitescroll.defaults.infid;

at the end of _create fixes this problem, since only the current instance get's unbound.

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 supports multiple instances on the same page. [Check out a documentation page for an example](https://infinite-scroll.com/options.html#append)

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
