### ISSUE TITLE
visible selector results in "... found no elements"

### ISSUE THREAD

**Issue by rajbala** [metafizzy/infinite-scroll#557]
I'm trying to use the :visible jQuery selector in for the selector parameters in Infinite Scroll, but this results in the message "Your contentSelector found no elements."

Should something this work?

contentSelector: "div.content:visible"

I can do this in the Firebug console and get back a result:

$("div.content:visible")

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
