### ISSUE TITLE
triggering new results immediately after scrolling

### ISSUE THREAD

**Issue by linuxaman** [metafizzy/infinite-scroll#566]
hey 
I'm using infinite-scroll on my site and it triggers new posts immediately after scrolling little bit. I tried to increase and decrease bufferPx & extraScrollPx but no luck. you can see at my site i've uploaded some sample data at loltub.com
try scrolling a bit, it'll load new results what i want is the user need to reach all the way to the bottom to trigger infinite-scroll.

**Comment by alse** [comment]
A missing html doctype declaration caused the same problem for me. Without the doctype, $(window).height() the same as $(document).height() in Chrome, so the _nearbottom function returns the wrong result.
