### ISSUE TITLE
Support to Show Current Page URL for Better SEO

### ISSUE THREAD

**Issue by chanzone** [metafizzy/infinite-scroll#568]
I am using this plugin and it works fine. However I can't find any option to enable browser URL auto update when infinite-scroll load new page content. A demo site for this feature is at <a href="http://scrollsample.appspot.com/items">Infinite scroll with pagination demo</a>, when user scrolls forward or backward, the browser URL is updated to show current page URL.

Appreciate if anyone can let me know:

<ul>
<li>If infinite-scroll plugin already built-in this feature, may I know how to enable it?</li>
<li>If it is not built-in, what is the best practise to integrate it to infinite-scroll plugin and how?</li>
</ul>

Some relevant info:

<ul>
<li><a href="http://stackoverflow.com/questions/824349/modify-the-url-without-reloading-the-page">Modify the URL without reloading the page</a></li>
<li><a href="http://googlewebmastercentral.blogspot.in/2014/02/infinite-scroll-search-friendly.html">Infinite scroll search-friendly recommendations</a></li>
</ul>

**Comment by coldpumpkin** [comment]
@jacopotarantino Sorry haven't been around. Did you manage to test the PR?

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 changes the URL to loaded page by default. [See `history` option](https://infinite-scroll.com/options.html#history). This makes it back & refresh button friendly. It also changes document title to match the newly loaded page.

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
