### ISSUE TITLE
Loading WP Comments with infinite scroll

### ISSUE THREAD

**Issue by Bobz-zg** [metafizzy/infinite-scroll#580]
Hi,

I'm trying to load next page comments in Wordpress with infinite scroll.
I get an error:

"Sorry, we couldn't parse your Next (Previous Posts) URL. Verify your the css selector points to the correct A tag. If you still get this error: yell, scream, and kindly ask for help at infinite-scroll.com."

Console screenshot: http://i.imgur.com/k4aw015.png

**Comments markup**
`<ol class="media-list"> 
<li class="comment">Comment Text</li>
<li class="comment">Comment Text</li>
</ol>`

**Infscr function**

```
var $container = $('ol.media-list');

    $container.infinitescroll({
      msgText      : '<em>Loading reviews...</em>',
      debug        : true,
      navSelector  : '.pager',
      nextSelector : '.load-reviews a',
      itemSelector : 'li.comment',
      loading: {
          finishedMsg: 'All Reviews loaded',
          img: '<?php echo get_template_directory_uri(); ?>/assets/img/ajax-loader.gif'
        }
    });

    $(window).unbind('.infscr');

    $('.load-reviews a').click(function(e){
        if(e.preventDefault) { e.preventDefault(); }
    $('ol.media-list').infinitescroll('retrieve');
    });
```

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
