### ISSUE TITLE
send context(instance) for all function calls

### ISSUE THREAD

**Issue by AngeIII** [metafizzy/infinite-scroll#583]
for now it is impossible to use methods when defining an element like this:

``` js
$loaderControl.infinitescroll({
            nextSelector:$('[data-lazy-loading-btn="true"] a:first',that.$el),
            navSelector:$('[data-lazy-loading-btn="true"]',that.$el),
            appendCallback:false,
            path:this.lazyPath,
            // debug:true,
            prefill:true,
            itemSelector:'.vc_grid-item',
            loading: {
                msg: $loader,
                selector: that.$loaderControl,
                start: function(opts){ (INSTANCE).beginAjax(opts); // this is impossible yet. },
                finished: function(opts) { $loader.css('opacity',0); }
            }
        }
```

this is because you send only wrapper and options but not sending context.
 opts.loading.start.call($(opts.contentSelector)[0],opts);

better would be to send 
 opts.loading.start.call($(opts.contentSelector)[0],opts,this);
so it will allow to use infinitescroll methods (like _prefill, beginAjax and etc).

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 comes with vanilla JS support. Additionally, you can access the instance with `[.data('infiniteScroll')`](https://infinite-scroll.com/api.html#jquery-fn-data-infinitescroll).

The `loading.start` and `loading.finished` option methods have been replaced with [events](https://infinite-scroll.com/events.html): `request` and `append` or `load`.

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
