### ISSUE TITLE
infscr-loading

### ISSUE THREAD

**Issue by themesidea** [metafizzy/infinite-scroll#594]
Hi,
Just a question, how to show the msgText  below the button load more.

Thanks

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 has a new setup for loading and status elements. [See `status` option](https://infinite-scroll.com/options.html#status). This uses your own HTML.

``` html
<div class="page-load-status">
  <p class="infinite-scroll-request">Loading...</p>
  <p class="infinite-scroll-last">End of content</p>
  <p class="infinite-scroll-error">No more pages to load</p>
</div>
```

``` js
status: '.page-load-status'
```

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
