### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by reggi** [metafizzy/infinite-scroll#599]
What are the chances getting a NPM comparable version of infinite-scroll?

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll is now available on [npm as `infinite-scroll`](https://www.npmjs.com/package/infinite-scroll)

``` bash
npm install infinite-scroll
```
