### ISSUE TITLE
Unexpected tokenwhen I try combinate load() funtion

### ISSUE THREAD

**Issue by NeoCsatornaja** [metafizzy/infinite-scroll#600]
I tryed combinate with load and I get a unexpected token erorr in console.
my code looks like this:
<code>$('.more').infinitescroll({
binder: $('.more'),
$( "video-body" ).load( "next.php" );
});
</code>

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
