### ISSUE TITLE
Not finishing?

### ISSUE THREAD

**Issue by lookapanda** [metafizzy/infinite-scroll#601]
Usually it should show "no more content" when the end is reached, but it is just stuck at "loading more content..."

See: https://www.thurnax.com/index.php/Thread/4528-Testbeitrag/?l=2
Click the button at the bottom first, then scroll down...you will see what I mean :/
Why is that so?

**Comment by danlewis** [comment]
Also have the same issue when I override the msg option as below

    $("#listing").infinitescroll({
    loading: {
      msg: $("<div class='infinite-loading'><i class='fa fa-refresh fa-spin'></i></div>")
    },
    navSelector: "ul.pagination",
    nextSelector: "ul.pagination a[rel=next]",
    itemSelector: "#listing li.comment",
    bufferPx: 400
    })

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 has a new setup for loading and status elements. [See `status` option](https://infinite-scroll.com/options.html#status). This uses your own HTML.

``` html
<div class="page-load-status">
  <p class="infinite-scroll-request">Loading...</p>
  <p class="infinite-scroll-last">End of content</p>
  <p class="infinite-scroll-error">No more pages to load</p>
</div>
```

``` js
status: '.page-load-status'
```

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
