### ISSUE TITLE
Infinite scroll and another jquery scripts

### ISSUE THREAD

**Issue by Luppakorva** [metafizzy/infinite-scroll#602]
Ok, so thought to ask some help.

I'm first of all completely new to jquery, infinite-scroll is the first one I'm working with.

So, I have gotten infinite scroll to work perfectly but when it loads the 2nd page the other jquery scripts I'm using are not loaded. I have tried to google this up and find a solution but all I have managed to find (actually from another issue) was that infinite-scroll loads only html and that is most likely the reason it doesn't work.

So, what is the way to include further jquery scripts (I'd have to include multiple ones) into next pages? Most likely more than newbie question but if someone could point me out to right path I'd be more than grateful.

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 'refreshes' <script> tags, like for Twitter or CodePen embeds. This may have been an issue with previous v2.

If you're asking about separate `.js` that is not included in the initial page, that's a separate issue. You'll have to specify what needs to be loaded. You can do this with the [`append` or `load` event](https://infinite-scroll.com/events.html)

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
