### ISSUE TITLE
Infinitescroll change domain name

### ISSUE THREAD

**Issue by macagoraga** [metafizzy/infinite-scroll#603]
Hi

is possible that the plugin change domain name which have a number?

the domain name have a number "2" and when scrolling down for load new post, its change domain name to "3".

Check below screenshot.

![screen shot 2014-12-17 at 09 39 01](https://cloud.githubusercontent.com/assets/5359394/5468685/91a6fef8-85d2-11e4-8431-ce1e04714a3c.png)

Since part of domain are changed for pagination, I guess if possible that also domain name is changed.

**Comment by desandro** [comment]
This looks to be a bug with how `nextSelector` did not correctly parse the path. This issue could have been fixed with setting `path`:

``` js
path: [ 'http://www.2ize.com/index.php?do=/blog/page_', '/' ]
```
