### ISSUE TITLE
How does Infinite Scroll know when it reaches the end?

### ISSUE THREAD

**Issue by Jaxel** [metafizzy/infinite-scroll#604]
I have a page here:
http://8wayrun.com/articles/soulcalibur-ii.22/category

The content is set up as follows:

```
<div class="articlesGrid">
        <div class="articleItem"></div>
        <div class="articleItem"></div>
        ...
</div>

<div class="articlesPager">
    <a...
    <a...
    <a class="nextPage"...
</div>
```

Then I am calling the infinite scroller as follows:

```
$grid.infinitescroll({
    navSelector: ".articlesPager",
    nextSelector: ".articlesPager a.nextPage",
    itemSelector: ".articlesGrid"
}
```

On the page I linked above, it will reach page 4 before it runs out of content. On that fourth page, `.articlesPager a.nextPage` does not exist... because there is no next page. We can see this if we go directly to page 4 here:
http://8wayrun.com/articles/soulcalibur-ii.22/category?page=4

However, the issue I am having is if I use the infinite scrolling from page 1. When it reaches page 4 and doesn't find a nextPage element, instead of displaying that I've reached the end of the internet, it keeps on reloading page 4. What am I doing wrong?

**Comment by desandro** [comment]
Looks like your page's JS has changed in the past two years. I'm closing this issue as such.
