### ISSUE TITLE
NavSelector and Pausing?

### ISSUE THREAD

**Issue by Jaxel** [metafizzy/infinite-scroll#605]
When you use Infinite Scroll, it hides the NavSelector... is there a way to get it to NOT do this? I would prefer if it instead loaded the NavSelector from the new page and replaced the old one.

Also, is there a way to get the script to pause after loading 3 pages, then require the user to click a button to resume?

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

You can pause loading on scroll in an event. See similar demo: [Scroll 2 pages, then load with button](https://infinite-scroll.com/extras.html#scroll-2-pages-then-load-with-button)

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.

``` js
var $container = $('.container').infiniteScroll({
  // options...
  // enable button
  button: '.view-more-button',
});

var $viewMoreButton = $('.view-more-button');

// get Infinite Scroll instance
var infScroll = $container.data('infiniteScroll');

$container.on( 'load.infiniteScroll', onPageLoad );

function onPageLoad() {
  if ( infScroll.loadCount == 1 ) {
    // after 2nd page loaded
    // disable loading on scroll
    $container.infiniteScroll( 'option', {
      loadOnScroll: false,
    });
    // show button
    $viewMoreButton.show();
    // remove event listener
    $container.off( 'load.infiniteScroll', onPageLoad );
  }
}
```
