### ISSUE TITLE
pathParse is wrong... in some cases...

### ISSUE THREAD

**Issue by Jaxel** [metafizzy/infinite-scroll#606]
Starting from here, with debug mode on:
http://8wayrun.com/articles/soulcalibur-ii.22/category

["heading into ajax", "articles/soulcalibur-ii.22/category?page=2"]
["heading into ajax", "articles/soulcalibur-ii.22/category?page=3"]
["heading into ajax", "articles/soulcalibur-ii.22/category?page=4"]
["heading into ajax", "articles/soulcalibur-ii.22/category?page=5"]

This is all correct.

But if I start from this page:
http://8wayrun.com/articles/soulcalibur-ii.22/category?page=3

["heading into ajax", "articles/soulcalibur-ii.22/category?page=4"]
["heading into ajax", "articles/soulcalibur-ii.32/category?page=4"]
["heading into ajax", "articles/soulcalibur-ii.42/category?page=4"]
["heading into ajax", "articles/soulcalibur-ii.52/category?page=4"]

How do I fix this?

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 has better support for URLs with parameters, and it has all new support for infinite-scrolling from subsequent pages. I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
