### ISSUE TITLE
infinite scroll duplicate issue

### ISSUE THREAD

**Issue by aydcery** [metafizzy/infinite-scroll#608]
I am using this code;

```
    var $container = $('#container');
var offset = '20';
    $container.imagesLoaded(function(){
    $container.masonry({
    itemSelector : '.box',
    isFitWidth: true,
    columnWidth: 236,
    gutter: 14
    });
    }); 

    $container.infinitescroll({
    navSelector  : '.page-links-list',    // selector for the paged navigation
    nextSelector : '.page-links-list .page-next',  // selector for the NEXT link (to page 2)
    itemSelector : '.box',     // selector for all items you'll retrieve
path: function(pageNumber) {
return "?start=" + ((pageNumber - 1) * offset);
}
```

and it's working perfect when my pagination url is like this;

```
    http://www.mypageurl.com/content?start=20
```

but in category page my pagination url is like this ;

```
    http://www.mypageurl.com/content?sort=categoryname&start=20
```

and it's not working in category page, if I don't use path function it's duplicating posts :(

best regards

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. It has been support for URLs with parameters like your example. Please open a new issue if you run into trouble with Infinite Scroll v3.
