### ISSUE TITLE
I'd like to trigger two related loops when the end of either is reached

### ISSUE THREAD

**Issue by isarmstrong** [metafizzy/infinite-scroll#610]
Hey Paul & Co,

I've mostly coded up a replica of the qz.com blog functionality with one notable exception. On the tail end of a page or headline column, I've still got standard pagination. The ideal functionality is that when the end of the excerpts or headlines div is reached, it will trigger an AJAX load in both columns. This behavior works if I do a click through to the next page but, for obvious reasons, it'll only trigger one page loop via AJAX.

![Appearance at the bottom of both sections](http://content.screencast.com/users/Imperative/folders/Snagit/media/e5e66849-70fb-43d8-a6cb-1e352d79d619/01.13.2015-09.23.png)

Now, I could spin my wheels for a while and hack up a way to make one scroll point trigger both scripts but I thought I'd ask the community about the cleanest way to get this behavior.

Anything I should know that might help?

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 supports multiple instances on the same page. Or you can disable [appending](https://infinite-scroll.com/options.html#append) and do your own behavior on the [`load` event](https://infinite-scroll.com/events.html#load).


``` js
$container.on( 'load.infiniteScroll', function( event, response, path ) {
  var $response = $( response );
  // append posts from loaded page
  var $posts = $response.find('.post');
  $container.append( $posts );
  // append sidebar items from loaded page
  var $sidebarItems = $response.find('.sidebar-item');
  $sidebar.append( $sidebarItems );
});

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
