### ISSUE TITLE
Loading fires too early

### ISSUE THREAD

**Issue by Ian-Y** [metafizzy/infinite-scroll#614]
At first, the loading fires even if I only scroll the page 1 pixel.

Then, the loading fires when I scroll the page to 20%.

Then, the loading fires when I scroll the page to 40~50%.

Then, the loading fires when I scroll the page to 60~75%.

Then, the loading fires when I scroll the page to 60~75%.

Then, the loading fires when I scroll the page to 60~75%.

**Comment by Ian-Y** [comment]
I had simplified my files at [here](https://drive.google.com/file/d/0BwkLXIVz0y59eTktMWl3bE9xd2c/view).

**Comment by Ian-Y** [comment]
[Demonstration on Plunker](http://goo.gl/boZdhW).

**Comment by Ian-Y** [comment]
After checking the source code, I found [on line 423](https://github.com/paulirish/infinite-scroll/blob/master/jquery.infinitescroll.js#L423) that the loading has something to do with the position of navigation. Then I realized that I hid the navigation in css by default that caused the script to be unable to calculate the position of the navigation correctly. After un-hiding the navigation through css, it has been fixed.

I genuinely suggest that this being addressed in documentation.

**Comment by loveMrStar** [comment]
I also have this problem, if only in the user experience is not the problem of. But I think, as a precise personnel, not controllable program makes me feel uneasy

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
