### ISSUE TITLE
infinite-scroll with Wookmark plugin

### ISSUE THREAD

**Issue by LeventeNagy** [metafizzy/infinite-scroll#615]
Hello. i would like to use zhis plugin with wookmark: https://github.com/GBKS/Wookmark-jQuery

The problem is after my html is loaded, the template is broken

Wookmark

<pre>
(function ($){
      $(window).load(function(){
        var $handler = $('.homepage-grid li');

        $handler.wookmark({            
            autoResize: true, // This will auto-update the layout when the browser window is resized.
            container: $('#main'), // Optional, used for some extra CSS styling
            offset: 36, // Optional, the distance between grid items
            outerOffset: 0, // Optional, the distance to the containers border
            itemWidth: 220 // Optional, the width of a grid item
        });
      });
      
    })(jQuery);
</pre>

infinite-scroll

<pre>
$(function() {

    $('#main').infinitescroll({
            loading: {
                selector: '#load-more',
                finishedMsg: '',
                img: 'public/36-1.gif',
                msgText: '',
            },
            animate         : true,
            navSelector     : ".infinite-wrapper",
            nextSelector    : 'a.more',
            itemSelector    : "ul.homepage-grid",     
            debug           : false,
            dataType        : 'html',
            behavior        : "twitter"
    });

});
</pre>

If i use it this way the content breaks

if i re-define wookmark in infinite callback 

<pre>
$(function() {

    $('#main').infinitescroll({
            loading: {
                selector: '#load-more',
                finishedMsg: '',
                img: 'public/36-1.gif',
                msgText: '',
            },
            animate         : true,
            navSelector     : ".infinite-wrapper",
            nextSelector    : 'a.more',
            itemSelector    : "ul.homepage-grid",     
            debug           : false,
            dataType        : 'html',
            behavior        : "twitter"
},
function()
{

     var $handler = $('.homepage-grid li');

        $handler.wookmark({            
            autoResize: true, // This will auto-update the layout when the browser window is resized.
            container: $('#main'), // Optional, used for some extra CSS styling
            offset: 36, // Optional, the distance between grid items
            outerOffset: 0, // Optional, the distance to the containers border
            itemWidth: 220 // Optional, the width of a grid item
        });
});

});

</pre>

Still breaks the content but if i refres a few times it works, if re open my page, it break again and okay after i refresh a few times again.

Could anybody give me a hint? would save my life

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. [Infinite Scroll v3 has direct support for Masonry](https://infinite-scroll.com/options.html#outlayer). Please open a new issue if you run into trouble with Infinite Scroll v3.
