### ISSUE TITLE
Check for maxPage *after* AJAX

### ISSUE THREAD

**Issue by cfxd** [metafizzy/infinite-scroll#620]
I can almost get around the issue in https://github.com/paulirish/infinite-scroll/issues/619 if I set the `maxPage` option, however the `maxPage` gets checked at the start of an AJAX request when scrolling or clicking a "load more" button.

It would be great if the `maxPage` check could run at the end of each successful scroll or click to eliminate the need to click a "load more" button one additional, unnecessary time.

**Comment by desandro** [comment]
See my response at https://github.com/metafizzy/infinite-scroll/issues/619#issuecomment-311087402
