### ISSUE TITLE
the next page button won't hide when data is null

### ISSUE THREAD

**Issue by shangdiyisi** [metafizzy/infinite-scroll#627]
The next page button won't hide when data of first page is null. I've add "prefill : true".

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
