### ISSUE TITLE
Use infinite scoll to preload all pages in the background

### ISSUE THREAD

**Issue by sieppl** [metafizzy/infinite-scroll#629]
Is there a hack or trick to use infinite scroll to load all pages (one by one) without requiring the user to scroll?

**Comment by sieppl** [comment]
This works, is there a better solution?

```javascript
(function preloadAll() {
   if ($('.selector').data('infinitescroll').options.state.isDone) {
       return false;
   }

   if ($('.selector').data('infinitescroll').options.state.isDuringAjax) {
       setTimeout(preloadAll, 1000);
   }
   else {
        $('.selector').infinitescroll('retrieve');
        setTimeout(preloadAll, 2000);
   }

}());
```

**Comment by desandro** [comment]
Thanks for sharing your solution. Yes, I'd say that may be the best way to 'preload' pages. This kind of behavior is best suited in the developer's domain code, not as part of Infinite Scroll's core.
