### ISSUE TITLE
Infinite Scroll expression not firing in Firefox or Chrome

### ISSUE THREAD

**Issue by easilyBaffled** [metafizzy/infinite-scroll#630]
I had `<ul infinite-scroll="getViewableItems()" infinite-scroll-distance="1">` working when I ran it in Chrome. When I updated to Chrome 41.0.2272.89 last week, it stopped responding. The same thing is happening in Firefox 31.0. 
I made sure `getViewableItems` works, and I have played with `infinite-scroll-distance`, but there is no response from infinite-scroll. 
There is a response for Safari, but it will fire 7-20 times even with '`THROTTLE_MILLISECONDS`' set.

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
