### ISSUE TITLE
CSS3 Column breaks the logic

### ISSUE THREAD

**Issue by zukilover** [metafizzy/infinite-scroll#634]
I'm not sure what went wrong, but if you use CSS3 column rules, the infinite scroll doesn't work at all.

Might be some height calculation problem?

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
