### ISSUE TITLE
scroll not working properly. - Loading data on top scroll and without reaching bottom

### ISSUE THREAD

**Issue by bhumitra** [metafizzy/infinite-scroll#635]
I am not able to get the examples to work also.

This is not working!

Loading data on top scroll and without reaching bottom

Does anyone have a proper working example with code?

**Comment by Amerr** [comment]
+1

**Comment by loveMrStar** [comment]
example : http://h5china.cn/joke/index.jsp

**Comment by Amerr** [comment]
@loveMrStar is there any example load messages . on scroll top. Scrolling from bottom to top to read all message.

**Comment by loveMrStar** [comment]
@Amerr Do you mean pull up and then load the message?

**Comment by Amerr** [comment]
yes @loveMrStar . like slack does

**Comment by loveMrStar** [comment]
@Amerr   Here's an example: the drop - up and pull - up of iScroll 5 is more load - up - but there is no such unlimited scrolling.
http://amazeui.org/examples/iscroll.html

**Comment by loveMrStar** [comment]
@Amerr   If you want iscroll and unlimited scrolling, you can do this:
(1) when the drop is refreshed
    ①Empty the container for a message list
        //...
    ②Update method to reset unlimited scrolling plugin
         $(selector).Infinitescroll ('update', {state: {currPage: 0, isDone: false});
    ③Use the retrieve method to load the next page automatically
         $(selector).Infinitescroll ('retrieve');
    ④If before the called pause method also need to call the resume method to infinite rolling recovery
          $(selector).Infinitescroll ('resume');
(2) when the load is loaded
     ①Use the retrieve method to load the next page automatically
          $(selector).Infinitescroll ('retrieve');
          $(selector).Infinitescroll ('resume');
      ②When loading the page, the method is called to call the pause method in the unlimited scrolling plug-in.
           $(selector).Infinitescroll ('pause');

**Comment by desandro** [comment]
Infinite Scroll does not support bottom-up loading or scrolling. I'm closing this issue as its been quiet for a while. Please open a new issue if you would still like to see this feature.

---

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).
