### ISSUE TITLE
I want to maintenance of the project

### ISSUE THREAD

**Issue by astrocean** [metafizzy/infinite-scroll#637]
@paulirish  I think the maintenance of the project, if there is no better choice. I with he also for a long time. While on the function and the underlying implementation not carefully studied, but I really feel he is a good project. Due to technical, I might have to him temporarily unable to do a lot of updates, but I will try my best. Thank you

**Comment by paulirish** [comment]
@loveMrStar great. the best way forward is to start a brand new repo and begin building a v2 of the project there. as it matures, we can start to migrate this project into yours.

**Comment by appskitchen** [comment]
Really appreciate it

**Comment by joshuachestang** [comment]
I wish I could help!!! I'm more of a Ruby developer, but I could help with updating the website for infinte scroll.

**Comment by philippze** [comment]
There's this other infinitescroll plugin:

https://github.com/pklauzinski/jscroll

In case for any reason you want brand new code: I've written a minimal version of an infinitescroll plugin here:

https://github.com/philippze/infinitescroll

**Comment by desandro** [comment]
Thank you for your interest and willingness to contribute Infinite Scroll. After discussing this matter with Paul, he's allowed me to take over the project. Read the blog post: [Metafizzy taking over Infinite Scroll](https://metafizzy.co/blog/metafizzy-taking-infinite-scroll/). I'll be releasing a brand new version in the coming weeks.

Moving forward, your feedback contributions are still appreciated with the new version. 🌈🐻
