### ISSUE TITLE
Infinite scroll + masonry

### ISSUE THREAD

**Issue by rolandrnl** [metafizzy/infinite-scroll#647]
Hi,

Unfortunately the plugin appends the container of the loader into the same container where my items are. Is it possible to specify the container for the loading animation?

Thank you!

**Comment by jamieburchell** [comment]
Had this issue today. Set the `selector` param in the `loading` object when you initialise the library. E.g. `selector: '.loader'`

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 uses different method for its loading status elements. See [`status` option](https://infinite-scroll.com/options.html#status). This element should be outside of the items container element.

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
