### ISSUE TITLE
Infinite Scroll not working on mobile

### ISSUE THREAD

**Issue by m1xf1t** [metafizzy/infinite-scroll#649]
The plugin works just fine on the desktop.

When I switch to mobile - [ iPhone5s / device I tested on ] It only shows 
the first set of listed items. 

As I scroll on mobile it doesn't actually load any of the other items.

Please advise.

Example Link:
https://oneleven.io/events

**Comment by nitheeshskiploop** [comment]
Even i'm facing same issue.

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
