### ISSUE TITLE
New Documentation

### ISSUE THREAD

**Issue by lukeshumard** [metafizzy/infinite-scroll#65]
We need some new docs...badly. We're at the stage of the rewrite now where most things are pretty concrete so it's time to smash this. Anyone who wants a section, comment below and we'll knock them out.

I'm sure as we're going through this we can also weed out some of this junk for a cleaner API.

Also, it was a bit unclear from our chat earlier, but are we doing the docs on a subdomain using Github's wiki or are we keep it in Wordpress?
### Public Methods
- bind
- unbind
- destroy
- retrieve
- pause
- resume
- toggle
- scroll
- update
### Options
- callback
- debug
- behavior
- binder
- nextSelector
- loading
- navSelector
- contentSelector
- extraScrollPx
- itemSelector
- animate
- pathParse
- dataType
- appendCallback
- bufferPx
- orientation
- errorCallback
- currPage
- infid
- state
- pixelsFromNavToBottom
- path
### Behaviors
- What are behaviors?
- How to use?
- Quick guide

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). With an all new site. Look at how younger Dave wanted to help :)
