### ISSUE TITLE
Executing a javascript function while infinite scroll executes

### ISSUE THREAD

**Issue by TheWolfCoder** [metafizzy/infinite-scroll#650]
Is there a way in jquery to execute a seperate javascript function while infinite scroll is running? Here is the infinite scroll code:

```
$(document).ready ->
  $("#my_table.page").infinitescroll({
    navSelector: "nav.pagination" # selector for the paged navigation (it will be hidden)
    nextSelector: "nav.pagination a[rel=next]" # selector for the NEXT link (to page 2)
    itemSelector: "#my_table tr.post" # selector for all items you'll retrieve
    loading: {
      img: "loader.gif",
      msgText: "Loading more results.."
      finishedMsg: 'End..'
    }
})
;
```

Here was the javascript:

```
function alertUserAtEnd()
{
alert('Running the end of the pagination');
alert('Pagination finished');
}
```

`

**Comment by khansab4** [comment]
have Same Problem, any Solution ??

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

[Infinite Scroll v3 has events](https://infinite-scroll.com/events.html). You can use [`request` event](https://infinite-scroll.com/events.html#request) for when loading begins, and `append` or `load` for when loading ends.

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
