### ISSUE TITLE
Facebook videos issue

### ISSUE THREAD

**Issue by qAlex26** [metafizzy/infinite-scroll#651]
Hello, all good just facebook videos doesn't show after the infinite scroll is loaded, what callback code i need to define ?
This problem drive my crazy...
Thanks.

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
