### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by firsh** [metafizzy/infinite-scroll#652]
> Resume
> 
> $('.selector').infinitescroll('resume');
> Destroys the instance of infinite scroll. This is create a flag to not load anymore content and will unbind all events.

I guess it must be resume description, not the destroy.

**Comment by firsh** [comment]
#653

**Comment by desandro** [comment]
Thanks for catching this typo. 

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so this typo has been removed.
