### ISSUE TITLE
Serialize parameters

### ISSUE THREAD

**Issue by lucianoreis** [metafizzy/infinite-scroll#655]
I am using the infinite- scroll to page data that is filtered with parameters passed by .serialize ( ) .
The infinite- scroll adds painação only passed parameters in the URL eg https://app.com/my-route?param1=val1&param2=val2&page=2

``` js
$("#search").on("change", function (event) {
  var $this = $(this);
  var frmValues = $this.serialize();
  $.ajax({
    type: 'GET',
    url: '/products',
    data: frmValues
  })
  .done(function (data) {
    $('#items').html(jQuery(data).find('#items').html());
  })
  .fail(function () {
    console.log('Erro no filtro');
  });
  event.preventDefault();
});
```

This generates a GET https://app.com/my-route?param1=val1&param2=val2 call
And when I trigger the paging it ignores these parameters only running GET https://app.com/my-route?page=2
How can I solve this?

Translated by Google

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. v3 has better support for URLs with parameters. Please open a new issue if you run into trouble with Infinite Scroll v3.
