### ISSUE TITLE
Paging dies to load all records

### ISSUE THREAD

**Issue by lucianoreis** [metafizzy/infinite-scroll#657]
I listed all products in a category returning [ "Error" , "end" ] [ " Binding " , " unbind " ] , change the filter category and pagination does not work anymore . this makes no sense , how to fix it ?

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
