### ISSUE TITLE
infinitescroll not working with ajax page like jquerymobile

### ISSUE THREAD

**Issue by savoo** [metafizzy/infinite-scroll#658]
infinitescroll not working with ajax page like jquerymobile

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
