### ISSUE TITLE
infinite scroll without loading image

### ISSUE THREAD

**Issue by lzt7** [metafizzy/infinite-scroll#659]
I have looked everywhere to try and figure out how to use infinite scroll and not have a loading image, but I cannot find it. This is how you set it up loading text and image:

```
loading: {
    img: "/img/loading.gif",
    msgText: "Loading new posts..."
}
```
if i set msgText to '' then there will be no text, yet I cannot seem to do the same with the loading image as if I set it to a blank string, it will display the error image image.
I don't want to use a base64 encoded 1x1 pixel transparent image,
How can I use infinite scroll with no loading image?

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

With Infinite Scroll v3, you can set (or not set) a loading message and/or loading image within a [`status` element's HTML](https://infinite-scroll.com/options.html#status)

``` html
<div class="page-load-status">
  <p class="infinite-scroll-request">Loading new posts...</p>
  <p class="infinite-scroll-last">End of content</p>
  <p class="infinite-scroll-error">No more pages to load</p>
</div>
```

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
