### ISSUE TITLE
It wont goes ahead

### ISSUE THREAD

**Issue by abhibagul** [metafizzy/infinite-scroll#661]
It won't work when it tries to get content of 3rd page and returns the same content of the first page instead.

**Comment by desandro** [comment]
Sounds like an issue with how `path` option is being set. Can you provide your infiniteScroll JS code to look at?

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).
