### ISSUE TITLE
Locally hosted loading gif

### ISSUE THREAD

**Issue by RBIII** [metafizzy/infinite-scroll#662]
Probably a dumb question but how do I use a loading gif hosted locally in my project? I'm using Ruby on Rails, with the javascript for infinite scrolling below

```javascript
$container.infinitescroll({
      navSelector: 'nav.pagination', // selector for the paged navigation
      nextSelector: 'nav.pagination a[rel=next]', // selector for the NEXT link (to page 2)
      itemSelector: '#discover_content div.discover-article', // selector for all items you'll retrieve
      bufferPx: Math.round($(window).height() * 1.5),
      pixelsFromNavToBottom: Math.round($(window).height() * 1.5),
      loading: {
        finishedMsg: 'No more products to load.',
        msgText: "",
        img: "/app/assets/images/myblend-loading.gif"
      }
    }
```
I'm pretty sure the path is right but whenever I hit the infinite scrolling code I get an error in my console like "GET http://localhost:3000/app/assets/images/myblend-loading.gif 404 (Not Found)" and the image doesn't display. How can I use the gif I downloaded as the loading gif?

**Comment by desandro** [comment]
Looking at your options code, your image's complete URL would looks like:

```
http://example.com/app/assets/images/myblend-loading.gif
```

Double check that this URL works.
