### ISSUE TITLE
Not support zepto.js?

### ISSUE THREAD

**Issue by FourLeafClover** [metafizzy/infinite-scroll#666]

**Comment by jacopotarantino** [comment]
Are you running into any particular error with zepto? It's not officially supported here..

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). Officially, Infinite Scroll does not support Zepto. But it does support [vanilla JS](https://infinite-scroll.com/#initialize-with-vanilla-javascript). You can use Infinite Scroll with zepto with its vanilla JS code.
