### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DaveMiscampbell** [metafizzy/infinite-scroll#668]
We've been using this library for some time under the previous MIT license.

I see that the code is now GPL licensed - can you confirm that if we continue using the previous version (tagged 2.1.0) that we are not bound by the GPL license? Since it is marked by the MIT license I would say not but just wanted to check.

Thanks!

**Comment by desandro** [comment]
Yes, you may continue to use [Infinite Scroll v2](https://github.com/metafizzy/infinite-scroll/tree/2.1.0) under the MIT license.

**Comment by DaveMiscampbell** [comment]
Perfect - thanks for the quick response!
