### ISSUE TITLE
Tumblr - Uncaught DOMException: Failed to set the 'responseType' property on 'XMLHttpRequest'

### ISSUE THREAD

**Issue by shinoamakusa** [metafizzy/infinite-scroll#672]
First, thanks for keeping infinite-scroll alive and updating it new heights

I have old v2 code which I tried to update to new v3 API and in some ways not sure how to completely change as it uses old Infinite Scroll, ImageLoaded, Isotope and callback function to launch fancyBox too:

``` js
$(function() {
   var $container = $('.main-content');
   $container.imagesLoaded({
       background: true
   }, function() {
       $container.isotope({
           itemSelector: '.post-article',
           layoutMode: 'masonry',
           transitionDuration: '1s'
       });
   });
   $container.infinitescroll({
           itemSelector: ".post-article",
           navSelector: "#pagination",
           nextSelector: "#pagination #next-page a",
           loading: {
               finished: undefined,
               finishedMsg: "",
               msg: null,
               msgText:"",
               selector: null,
               speed: 'fast',
               start: undefined
           },
           bufferPx: 5500,
           prefill:true,
           debug: true,
           animate:false
       },
       // trigger Masonry as a callback
       function(newElements) {
           var $newElems = $(newElements).css({
               opacity: 0
           });
           // ensure that images load before adding to masonry/isotope layout
           $newElems.imagesLoaded(function() {
               $newElems.animate({
                   opacity: 1
               });
               $container.isotope('appended', $newElems);
               $newElems.each(function()
               {
                   $(this).find(".image-thumbnail a").each(openFancyBox);
               });
               
           });
       }
   );
});
```

**Comment by desandro** [comment]
Thanks for trying out Infinite Scroll v3! I've written up [documentation on how to upgrade from Infinite Scroll v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Looking at your code, you should be able to upgrade to Infinite Scroll v3 with this code:

``` js
$(function() {
  var $container = $('.main-content');

  // init Isotope
  $container.isotope({
    itemSelector: '.post-article',
    layoutMode: 'masonry',
    transitionDuration: '1s'
  });

  // layout Isotope after images loaded
  $container.imagesLoaded( function() {
    $container.isotope('layout');
  });

  // get Isotope instance
  var isotope = $container.data('isotope');

  // init Infinite Scroll
  $container.infiniteScroll({
    append: '.post-article',
    hideNav: '#pagination',
    path: '#pagination #next-page a',
    prefill: true,
    debug: true,
    // use outlayer option for Isotope integration
    outlayer: isotope,
  });

  // init FancyBox on append event
  $container.on( 'append.infiniteScroll', function( event, response, path, items ) {
    var $items = $( items );
    $items.find('.image-thumbnail a').each( openFancyBox );
  });

});
```

+ Use [`outlayer` option](https://infinite-scroll.com/options.html#outlayer) for Isotope integration. This takes care of all the fade in & isotope `appended` stuff.
+ Loading option has been removed. Use [`status` option](https://infinite-scroll.com/options.html#status) instead if you like.
+ Use [`append` event](https://infinite-scroll.com/events.html#append) instead of the callback function for FancyBox initialization

Please provide a live URL so we can all see the results! I'd love to see how you use Infinite Scroll + Isotope

**Comment by shinoamakusa** [comment]
That gives me the following error in Developer Console:

```
infinite-scroll.pkgd.min.js:12 Uncaught DOMException: Failed to set the 'responseType' property on 'XMLHttpRequest': The response type cannot be changed for synchronous requests made from a document.
    at r (https://unpkg.com/infinite-scroll@3.0.0/dist/infinite-scroll.pkgd.min.js:12:9886)
    at n.s.loadNextPage (https://unpkg.com/infinite-scroll@3.0.0/dist/infinite-scroll.pkgd.min.js:12:10636)
    at n.s.onScrollThresholdLoad (https://unpkg.com/infinite-scroll@3.0.0/dist/infinite-scroll.pkgd.min.js:12:10414)
    at n.e.emitEvent (https://unpkg.com/infinite-scroll@3.0.0/dist/infinite-scroll.pkgd.min.js:12:1952)
    at n.s.dispatchEvent (https://unpkg.com/infinite-scroll@3.0.0/dist/infinite-scroll.pkgd.min.js:12:5963)
    at n.<anonymous> (https://unpkg.com/infinite-scroll@3.0.0/dist/infinite-scroll.pkgd.min.js:12:13942)
    at n.<anonymous> (https://unpkg.com/infinite-scroll@3.0.0/dist/infinite-scroll.pkgd.min.js:12:8917)
    at n.onPageScroll (https://unpkg.com/infinite-scroll@3.0.0/dist/infinite-scroll.pkgd.min.js:12:8988)
```

Live url is http://jai-envie-de-toi.ml/ (be aware that it contains sensitive adult content aka nudity)

**Comment by desandro** [comment]
Thanks for that. This bug is occurring because the XMLHttpRequest has been set to syncronous for some reason. I don't know why just yet. I'll continue to investigate.

**Comment by shinoamakusa** [comment]
@desandro thanks in advance! :)

**Comment by Tom-Bonnike** [comment]
Any update on this? A workaround maybe? I know the issue probably comes from Tumblr but…

**Comment by desandro** [comment]
@Tom-Bonnike Are you experiencing the same issue? Could you provide a live URL?

**Comment by shinoamakusa** [comment]
Btw, the infinite scroll on my link works fine on IE, but not on any of Edge, Firefox or Chrome browsers I tested on. Hope this helps ...

**Comment by dco1** [comment]
Hey there. I am running into the same issue with Tumblr. Here's a live URL: https://eggstoast.tumblr.com

Thanks!

**Comment by blogjw** [comment]
i'm currently experiencing the same issue!

**Comment by shinoamakusa** [comment]
Would you kindly provide an update if there is a fix for this issue coming?

**Comment by shinoamakusa** [comment]
As this issue exists in browsers other than IE then maybe create a fallback functionality so that if the v3 method to get next page fails it falls back on the method used in v2 which worked regardless of browser.

**Comment by desandro** [comment]
@shinoamakusa Thanks for digging into this. Your fix has been merged and will be out in the next release.

**Comment by shinoamakusa** [comment]
Thanks, I just figured the theory that not all browsers implemented that 3rd parameter should be true by default as per specs and just tried to specify it and voila! :) Glad to be of help on my own issue and other people would be happy too :)

**Comment by desandro** [comment]
v3.0.2 has been released with this PR merged. Please update! Thank you again to @shinoamakusa for the contribution and saving my day 🌈 🐻

**Comment by benjamindenboer** [comment]
Experiencing this issue again, using version 3.0.3. Any advice?

**Comment by benjamindenboer** [comment]
cc @desandro

**Comment by desandro** [comment]
@benjamindenboer  This issue is tough to pin down. Do you have a live URL I can take a look at?
