### ISSUE TITLE
Issue with naming convention when using history and path: 'index{{#}}.html

### ISSUE THREAD

**Issue by macsupport** [metafizzy/infinite-scroll#678]
Using infinitescroll in _index.html_  and setting `history: 'replace'` and `path: 'index{{#}}.html',`, when one reloads a history page, (e.g. named index3.html as one scrolls), the actual page named _index3.html_ opens, not my index.html page with the history set to index3.html. My description is confusing, I understand, but the naming of the history pages the same as index{{#}}.html disrupts the function of infinitescroll history. I would normally not want the actual index3.html page to open, just my index.html page with the scroll position at the history of index3.html. Perhaps an option to set the history naming choice?

Mike
@jquerymac

**Comment by desandro** [comment]
Thanks for reporting this issue.

From your description, it sounds like you're better off disabling `history: false`. This when, when a user refreshes, they land back on the initial `index.html`, not a subsequent page.

If you want the user to last on `index.html` with `index3.html`'s content, Infinite Scroll does not support that. I would consider that I server-side issue.

Chime in if I'm not hearing things right 😜

**Comment by macsupport** [comment]
No. I get it. I was under the impression that history was to mark the position of the infinitescroll position and that reloading the page would bring one to that specific history position on index.html, not load the index{{#}}.html page itself. Thanks for explaining it more clearly.
