### ISSUE TITLE
Hitting the back button takes you back to first page

### ISSUE THREAD

**Issue by fschroiff** [metafizzy/infinite-scroll#679]
**Test case:** https://infinite-scroll.com/demo/full-page/
Browser: Safari 10.1.1 (12603.2.4)

- Scroll until the URL changes (`.../page2.html`)
- click on an external link
- hit the browser's back button

You are now back on https://infinite-scroll.com/demo/full-page/

I expected to be taken back to .../page2.html

**Comment by desandro** [comment]
Thanks for reporting this bug. Looks like there's a race condition with how Infinite Scroll re-sets scroll position before loading a page, and how Infinite Scroll watches scroll position to set page

**Comment by franszo** [comment]
Hi @desandro 
all the respect for your work on this! this is well waited feature! 
I have to say, its the same story for me, scrolling down to X pages, and clicking an external URL, makes the URL to original, then opening the new link. This is also happening on your fullpage demo
https://infinite-scroll.com/demo/full-page/

just another note : implemented into WP, where next link is `/page/2`, once this applied to the url, and going back to it, this only loads the contents of that exact page, not the original page and scrolling down to the 2nd loaded. Any other way to store the loaded page with a # or a ? so its not loading that exact page back?

Big up for your work!

**Comment by desandro** [comment]
@franszo Thanks for reporting this issue. To your _another note_, this is how Infinite Scroll's `history` option is designed to work. I feel this is an elegant solution that holds up even with JavaScript disabled.

**Comment by franszo** [comment]
@desandro 
Thanks for quick reply. I personally thought its storing that I scrolled down until page6 for example, and on going back, its loading up all the pages up to page6.

**Comment by desandro** [comment]
[v3.0.1](https://github.com/metafizzy/infinite-scroll/releases/tag/v3.0.1) has been released with this fix added. Please update! Closing this issue has resolved 🌈🐻
