### ISSUE TITLE
Having different loading `path` and `url`

### ISSUE THREAD

**Issue by imfaisalkh** [metafizzy/infinite-scroll#681]
I'm using this script in a WordPress theme and instead of loading an entire HTML `document` on subsequent page loads on scroll I'm making a manual `ajax` request to only request required markeup. For this I'm using some code like this:

			$('.grid').infiniteScroll({
				append: '.grid-item',
				path: 'http://localhost/wordpress/theme-name/wp-admin/admin-ajax.php?action=ajax_load_more&type=portfolio&page={{#}}',
				loadOnScroll: true,
			});

It works fine and loads and append only the necessary markup (thus faster loading time). Now, the issue is the URL shown in the bar is similiar to the loading path, which I don't want. I want 'loading path' and 'url in the bar' to be different in format. For example:

Loading Path: `http://localhost/wordpress/theme-name/wp-admin/admin-ajax.php?action=ajax_load_more&type=portfolio&page={{#}}`

Path in url bar: `http://localhost/wordpress/page/1/`

 Is it possible with this plugin?

**Comment by desandro** [comment]
Thanks for submitting this issue. If you wish to set the browser URL to a different URL than Infinite Scroll's `path`, then you'll have to disable `history: false` and set URL with your own code, on [`append` or `load` event](https://infinite-scroll.com/events.html). I would look something like

``` js
// get Infinite Scroll instance
var infScroll = $grid.data('infiniteScroll');

$grid.on( 'append.infiniteScroll', function() {
  // use loadCount property to set custom URL & title
  var title = 'Page ' + infScroll.loadCount;
  var url = '/wordpress/page/' + infScroll.loadCount;
  history.replaceState( null, title, url );
});
```

**Comment by imfaisalkh** [comment]
Thanks for your response, your solution makes sense, however, I'm guessing by using the `append` event the URL in the address bar won't change on scroll-up/down once the `append` event has fired on the initial scroll. Shouldn't we use the `history` event here?

**Comment by imfaisalkh** [comment]
Well, turns out `history` event does not fire when we set `history: false`. If we are able to fire `history` event when the URL is supposed to change I think it would be more flexible.

**Comment by desandro** [comment]
> If we are able to fire history event when the URL is supposed to change I think it would be more flexible.

Thanks for this feedback. Infinite Scroll v3 is still new. I'll wait until others request this feature before considering to add it.

**Comment by imfaisalkh** [comment]
Thanks, I'm closing this issue now.

**Comment by nateluzod** [comment]
I think I found an inelegant but seemingly effective way to do this with `history`:

Have the following options set:

```
history: 'replace',
historyTitle: true
```

Pass `post_name` of the next post as a URL param in your AJAX path. You might update yours to:

`http://localhost/wordpress/theme-name/wp-admin/admin-ajax.php?action=ajax_load_more&type=portfolio&page={{#}}?slug=next-post-slug'`

When the history event fires, you can parse the `path` value to get your slug, then set the URL to what you want with `history.replaceState()`. 

Mine ended up looking like this:
```
infiniteScroll.on('history', function(title, path) {
  var permalink = path.split('?slug=');
  history.replaceState( null, null, permalink[1]);
});
```

There's a slight flash in the address bar since we're changing the URL twice. Ideally the user is more interested in page content than the address bar, though. 

Hope that helps if anyone else is looking for a way to do this. If there's a cleaner/better way to accomplish this please let me know.

**Comment by desandro** [comment]
@nateluzod Thanks for posting your solution. Your code overwrite Infinite Scroll's history behavior. I would recommend disabling `history` and using `load` or `append` event as I've mentioned in previous comment. You still have access to the `path` argument, and you can get the page title from `response.title`.

``` js
infiniteScroll.on( 'append', function( response, path ) {
  var permalink = path.split('?slug=');
  // update URL
  history.replaceState( null, null, permalink[1]);
  // update title
  document.title = response.title;
});
```

**Comment by ADTC** [comment]
Coming here from #821 I'd say it would be great to have a simple way to achieve this internally by setting an option (a mockup is given there), but also it should work correctly when the page is reloaded or navigated back to.
