### ISSUE TITLE
checkLastPage listing only 2 pages

### ISSUE THREAD

**Issue by blackflow** [metafizzy/infinite-scroll#682]
Did anyone had a problem when setting checkLastPage to .pagination__next (navigation/next) loaded only 2 pages and then stopped (showing status)? If I choose to make it false in the end it just keeps appeding pages that don't exist 
(second case https://www.rekt.gg/f/game/49885 )

**Test case:** http://codepen.io/desandro/pen/WOjqNM

**Comment by desandro** [comment]
Thanks for reporting this bug. Sorry, I'm not able to reproduce this bug. See demo https://codepen.io/desandro/pen/932d64552cdcf7e9c31946b8d3556240/
