### ISSUE TITLE
It keeps on incrementing page number

### ISSUE THREAD

**Issue by fateemah** [metafizzy/infinite-scroll#683]
$('.hadith').infiniteScroll({
					// options
					path: '.pagination a',
					append: '.articles',
					loadOnScroll: true,					
			});

```
<p class="pagination">
  		<strong>1</strong>
		<a href="http://ahadith.ws/bukhari/book/5" data-ci-pagination-page="2">2</a>
</p>

```
while scrolling, it keeps on incrementing last number /book/6, /book/7 .....

**Comment by imfaisalkh** [comment]
Are you using WordPress? If so make sure that WordPress is returning 404 error for any subsequent pages which do not have any articles.

**Comment by fateemah** [comment]
No, I'm using codeigniter

**Comment by desandro** [comment]
Thank you for reporting this issue. I'm sorry to see you're having trouble with Infinite Scroll. Could you provide a **live URL**, or even better a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).

**Comment by fateemah** [comment]
i'm using Codeigniter framework. Cant post reduced test case for it
