### ISSUE TITLE
Infinite scroll is not being triggered on Laravel 5.4(button works)

### ISSUE THREAD

**Issue by neorganic** [metafizzy/infinite-scroll#685]
So the problem is as described in the title - it doesn't seem to trigger(load a new item) when scrolling , unless I use the button method. The only item that is being loaded is the first one(that is loaded when the page loads).

**my view**
```
  <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div id="content" class="col-md-10">
                        @foreach($brokenLink as $broken)
                            <div class="item col-lg-12">
                                <h4 class="media-heading">{{ $broken->broken_link }}
                                    <small>{{ $broken->created_at->diffForHumans() }}</small>
                                </h4>
                                {{ $broken->broken_link_at }}
                                <hr>
                            </div>
                        @endforeach
                    <button class="button view-more-button"></button>
                            {{ $brokenLink->render() }}
                </div>

                <p style="clear:both;">&nbsp;</p>
                <img style="display: none" id="loading" src="/images/loading.gif" alt="">
            </div>
        </div>
    </div>
```
**At the bottom of file:**
```
<script src="/js/jquery-3.1.1.min.js"></script>
<script src="/js/infinite-scroll.pkgd.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#content').infiniteScroll({
            path: '.pagination__next',
           //button: '.view-more-button', <-- the button method works...
            elementScroll: true,
            append: '.item',
            status:'#loading',
            hideNav: 'ul.pagination',
            prefill: false,
            scrollThreshold: 100,
            debug: true
        });
    });
</script>
```
**My controller**

```
   public function broken_link()
    {
        $brokenLink = BrokenLink::where('user_id', Auth::user()->id)
            ->paginate(1);
        return view('reports/broken_link')->with('brokenLink',$brokenLink);
    }
```
There are not errors in the console.

I use ubuntu 16.04 , currently newest Chrome Version 59.0.3071.109 (Official Build) (64-bit)  - if that helps. I don't think that that could be a browser issue, but also tested on Firefox, also tried using infinite scroll version 2 and jquery v2, same results....  The current used package version is - Infinite Scroll PACKAGED v3.0.0

**Comment by desandro** [comment]
Thank you for reporting this issue. I'm sorry to see you're having trouble with Infinite Scroll. Could you provide a **live URL**, or even better a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).

**Comment by neorganic** [comment]
Just wanted to note, that everything worked, but because of some 3rd party css it was invisible . light-dashboard-bootstrap.css to be precise  .
