### ISSUE TITLE
Tumblr + InfiniteScroll v3 no success appending succeeding page posts

### ISSUE THREAD

**Issue by gomarion** [metafizzy/infinite-scroll#687]
Hello guys,

Good day! First of all, thank you for creating such a wonderful plugin. I've had success using the v2 of the plugin and was very satisfied with it. I recently tried to implement v3 of InfiniteScroll seeing that masonry is already built into it. But after migrating to v3, so far, I have no success implementing it.

I read in some issues here that v3 has some problems with Tumblr such as this ticket: https://github.com/metafizzy/infinite-scroll/issues/672. At some point of trying out different ways to initialize InfiniteScroll including the vanilla JS implementation, using latest jQuery, even trying to edit the infinite-scroll.pkgd.js, I had that same issue "Uncaught DOMException: Failed to set the 'responseType' property on 'XMLHttpRequest'". So I reverted everything back to the original jQuery form.

Below is the HTML structure of the posts and their container:

```
<section class="content-area">
	<article class="post">...</article>
	<article class="post">...</article>
	<article class="post">...</article>
	...
</section>
```

Below is the code I used to initialize infiniteScroll:

```
var $tilegrid = $('.content-area');

$tilegrid.infiniteScroll({
	path: ".next-page",
	append: '.post',
	debug: true
});
```

This is the site I was working on http://ai-support-stage.tumblr.com/. And as you can see from the browser Console, it gets stucked in "[InfiniteScroll] scrollThreshold".  I couldn't put the codes inside codepen as stated in your _guidelines for contributing_ since it's difficult to replicate the Tumblr environment issue.

Do you guys have any idea why it's behaving as such? Thanks a lot in advance for the response!

Marion

**Comment by desandro** [comment]
Thanks for reporting this bug. Looks like you're running into an issue already reported #672. I'm sorry to say I do not have a fix at this time. I'll be looking into it.

**Comment by gomarion** [comment]
Thanks a lot for the response, Desandro. For now, I'll revert back to v2 since that works fine for me. But I do hope to be able to use v3 soon. I'll be on the lookout for a fix on this. Keep up the good work! :)
