### ISSUE TITLE
Infinite scroll pagination between sibling entries

### ISSUE THREAD

**Issue by howells** [metafizzy/infinite-scroll#688]
This isn't an issue, more of a question.

I have an individual article (whose url is `/news/current-entry`) which has a Next Article and Previous Article pagination which simply link to `/news/next-entry` and `/news/prev-entry`. I'd like Infinite Scroll to load and append the next article on scroll: you can see this behvaiour here - https://qz.com/1029445/what-you-should-do-instead-of-sending-angry-emails-to-your-enemies/

How would I configure infinite scroll to handle this, since `path:` is expecting a page number rather than a straight-forward URL, whereas I need to fetch the next url from the newly loaded content.

Any ideas hugely appreciated!

**Comment by desandro** [comment]
Thanks for reporting this issue! Setting [`path` to a function](https://infinite-scroll.com/options.html#path) will allow us to use any kind of URL, not just URLs with numbers.

For your use case, I think this can be done by setting a variable `nextURL` and then updating that variable on [`load` event](https://infinite-scroll.com/events.html#load) by selecting the element with the URL. The code would look something like this:

``` js
var nextURL;

function updateNextURL( doc ) {
  nextURL = $( doc ).find('.pagination__next').attr('href');
}
// get initial nextURL
updateNextURL( document );

// init Infinite Scroll
var $container = $('.container').infiniteScroll({
  // use function to set custom URLs
  path: function() {
    return nextURL;
  },
});

// update nextURL on page load
$container.on( 'load.infiniteScroll', function( event, response ) {
  updateNextURL( response );
});
```

Please try this out and report back if its working or not. I realize this is a tricky issue.

**Comment by howells** [comment]
@desandro fantastic, thanks David - seems to work well

**Comment by desandro** [comment]
Re-opening for visibility, as several people have asked about this.

**Comment by desandro** [comment]
This code has been added to the docs in [Extras - Loading URLs from loaded pages](https://infinite-scroll.com/extras.html#loading-urls-from-loaded-pages)

**Comment by MadLandley** [comment]
Hi,

Thanks for the additional code. I had the same problem and the above solution solved it. Although, when scrolling upwards the url doesn’t change back to the post in view. Any ideas how to fix that?

**Comment by albalirus** [comment]
David, can you provide JavaScript variant of the fix?

```
var nextURL;

function updateNextURL( doc ) {
	nextURL = doc.querySelector('.fs-load-more-next').href;
}

// get initial nextURL
updateNextURL( document );

infScroll.on( 'load', function( event, body ) {
	updateNextURL( body );
});
```
