### ISSUE TITLE
Always request next page

### ISSUE THREAD

**Issue by yogie89** [metafizzy/infinite-scroll#689]
Hi, im just to try using infiniteScroll, when im using it everything fine, until the last page, the script always request for the next page, even thou im on the last page already. 

what is my mistake for this one yah ? appreciate for the clue.

<img width="455" alt="screen shot 2017-07-16 at 11 42 37 pm" src="https://user-images.githubusercontent.com/7960832/28249468-ac65b0dc-6a80-11e7-9169-228d187e73fc.png">

**Comment by desandro** [comment]
Thank you for reporting this issue. I'm sorry to see you're having trouble with Infinite Scroll. Could you provide a **live URL**, or even better a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).

I would double check that you have set the correct conditions for [checkLastPage to work](https://infinite-scroll.com/options.html#checklastpage)
