### ISSUE TITLE
404 request before last page check with prefill

### ISSUE THREAD

**Issue by einkoro** [metafizzy/infinite-scroll#690]
When you use the `prefill` option it will 404 trying to grab a page that doesn't exist before the last check fires. I encountered this working with WordPress & WooCommerce but have created a minimal test case linked below.

```
[InfiniteScroll] pageIndex. current page determined to be: 1 from next link
[InfiniteScroll] initialized. on products
[InfiniteScroll] prefill
[InfiniteScroll] request. URL: /shop/page/2/
XHR finished loading: GET "https://shopmmcurate.com.dev/shop/page/2/".
[InfiniteScroll] scrollThreshold
[InfiniteScroll] load. Products – Page 2 – Shop MMCurate. URL: /shop/page/2/
[InfiniteScroll] append. 2 items. URL: /shop/page/2/
[InfiniteScroll] prefill
[InfiniteScroll] request. URL: /shop/page/3/
[InfiniteScroll] last. URL: /shop/page/2/
GET https://shopmmcurate.com.dev/shop/page/3/ 404 ()
[InfiniteScroll] error. Error. URL: /shop/page/3/
XHR failed loading: GET "https://shopmmcurate.com.dev/shop/page/3/".
```

```
$( '.archive .products' ).infiniteScroll( {
    path: '.page-numbers .next',
    append: '.product',
    prefill: true,
    debug: true
} );
```

Test case: http://mmcurate.com/test/test-case.html

**Comment by desandro** [comment]
Thank you for reporting this bug! This issue will be fixed in the next release of Infinite Scroll.

**Comment by desandro** [comment]
[v3.0.1](https://github.com/metafizzy/infinite-scroll/releases/tag/v3.0.1) has been released with this fix added. Please update! Closing this issue has resolved 🌈🐻

**Comment by AustinBenavides** [comment]
The current implementation calls `this.checkLastPage` on append, as below:
`this.on( 'append', this.checkLastPage );`

Wouldn't it make more sense to call `this.checkLastPage` on load, especially since append is set to false by default?
`this.on( 'load', this.checkLastPage );`

**Comment by desandro** [comment]
@AustinBenavides Hmm, this is an interesting idea. I'll re-open this issue to consider it.
