### ISSUE TITLE
better warning about the license change.

### ISSUE THREAD

**Issue by jvanasco** [metafizzy/infinite-scroll#692]
The README should clearly indicate that there was a license change, perhaps an "IMPORTANT.txt" or CHANGELOG should be added to note this as well.  The licensing change is easy to miss in a git sync.

Changing from MIT to GPL is quite significant in terms of legal liabilities and compliance.

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. I realize its a big change, but Isotope v3 was an entirely big change. The license is documented right up front on both the README and [infinite-scroll.com](https://infinite-scroll.com). In addition, I'd added an item in the [GitHub Releases entry](https://github.com/metafizzy/infinite-scroll/releases/tag/v3.0.0).

**Comment by jvanasco** [comment]
My point is that the change in licensing isn't clear to existing users with active checkouts on the commandline (i.e. `git sync`).

The README doesn't state the license has *changed*, it only states what the current license is.
The "releases" entry is only available on the website.

There exists a lot of potential for existing users to continue using this library after syncing, and not realize that licensing has changed.  Significant changes like this are typically handled with a large callout, so existing users can catch it.  

If this were a new project or a forked repo, there wouldn't be a compliance issue --  but this took over the existing upstream remote.  Anyone pulling from the old repo at https://github.com/paulirish/infinite-scroll will be expecting an MIT license, but will be pulling in the new GPL licensed software.

That may not sound serious, but In many corporate organizations I've worked with GPL is expressly not allowed, and developers get in a lot of trouble for deploying releases without licenses in place.

**Comment by chipsenkbeil** [comment]
Agreed. I had to do a double-take on the license change.

**Comment by desandro** [comment]
It's been 1 year since the v3 release. This issue has been relatively quiet. Moving on 🌈🐻
