### ISSUE TITLE
Safari - not working with picturefill

### ISSUE THREAD

**Issue by tiagogon** [metafizzy/infinite-scroll#694]
I am using on my website the infinite-scroll and everything works fine on Chrome and Firefox. 

But on Safari once the thumbnails are appended, the images do not load. I believe this is because i use the [picturefill](https://github.com/scottjehl/picturefill) which is not being triggered after the items are loaded by infinite scroll.

You can see it on this images or live [here](https://trouble.place/m/photography/). 

![screen shot 2017-07-21 at 20 06 30](https://user-images.githubusercontent.com/3286869/28476408-38240c54-6e50-11e7-9fde-066ac6d8429d.png)

According to [this answer](https://github.com/scottjehl/picturefill/issues/73) I think i need to call `picturefill()` after the items are loaded by infinite scroll.
 
Unfortunately I am a beginner in js and don't know how to solve it. Does anyone know how to solve this? 

I thank you in advance!

**Comment by desandro** [comment]
Hello! Thanks for submitting this issue. Looks like you were close to a solution. You should be able to resolve this by adding this code:

``` js
$container.on( 'append.infiniteScroll', function(){
  picturefill();
});
```

Or, you can be more specific, by specifing the images that have been appended

``` js
$container.on( 'append.infiniteScroll', function( event, response, path, items ){
  picturefill({
    elements: $( items ).find('img');
  });
});
```

**Comment by tiagogon** [comment]
hi @desandro, 

thank you soo much for your help! 

I have tried to add the first piece of code, but still does not work. This is the version i have now on production [here](https://trouble.place). 

And the second version of the code is giving this error on the console:

![screen shot 2017-07-22 at 17 43 29](https://user-images.githubusercontent.com/3286869/28492504-5b889466-6f05-11e7-9272-80f3e4c4219a.png)

Is there any other solution we could try?

**Comment by desandro** [comment]
I'm not sure what the problem is. After loading a page, go to the console and execute `picturefill()`. You'll see that it doesn't resolve the missing images. The images are in the image, but they are displaying with 0 size. The images have a natural size, which means that something is loading, but its not displaying.

I did see that the `alt` attributes have `<` characters, like `alt="<empathic therapy"` which may throw things off. Similar to  aFarkas/lazysizes#174. Maybe fixing that could change things?

**Comment by tiagogon** [comment]
Thanks you again @desandro.

So I tried to do what you suggest on [this page](https://trouble.place/m/photography/) and I am getting "undefined", as you can see on [this screencast](http://recordit.co/tjQjRZ5MUj).
