### ISSUE TITLE
First page not loaded on JSON demo

### ISSUE THREAD

**Issue by yorgosg** [metafizzy/infinite-scroll#696]
I want to use a JSON api to load data for displaying a list with infinite scroll.
I found this demo https://codepen.io/desandro/pen/LLjYgG, but it only loads data from the 2nd page and on. The first page is never loaded.

**Comment by desandro** [comment]
I've revised the codePen demos to start loading on first page.

**Comment by santyas** [comment]
Hi @desandro !

I have the json/js file local, with around 600 items. Can I use it like this?

`path: function() {
        return 'js/products.js';
    },
`

**Comment by santyas** [comment]
@desandro Thank you David, ill try and tell you then.
Sorry, I forgot say that I have 700 items inside this json/js file. Each one with an url image. Is it a problem? I need to put it inside `<div><img src="" /></div>`

Thanks again.
