### ISSUE TITLE
Usage In Static Page Template Without Pagination 

### ISSUE THREAD

**Issue by braddalton** [metafizzy/infinite-scroll#698]
Works really well on archives where pagination is present however i would like to add a button for infinite scroll after 2 rows of entries on a page template where there is no pagination. Is this possible.

I assume i need a function for path

```
 path: function() {
// code
  },
```

**Comment by desandro** [comment]
Thanks for reporting this issue. I recommend you look into the [Button behaviors demos](https://infinite-scroll.com/extras.html#button-behaviors) and try working off of their code.

**Comment by braddalton** [comment]
How does this work when i'm using videos in grid?

[Live jsfiddle](https://jsfiddle.net/haymanpl/7f5dfL2f/14/)

This is the part where i am stuck

```
var nextPenSlugs = [
    '3d9a3b8092ebcf9bc4a72672b81df1ac',
    '2cde50c59ea73c47aec5bd26343ce287',
    'd83110c5f71ea23ba5800b6b1a4a95c4',
];
```

I need to scroll rows of videos and there's no slug.
