### ISSUE TITLE
URL changue if scroll down or top

### ISSUE THREAD

**Issue by Rejiz** [metafizzy/infinite-scroll#701]
**Test case:** http://codepen.io/desandro/pen/WOjqNM
Hi i have a question not problem, when i scroll down, my url change, depend of page loading but if i have 3 pages my url change more than 3,
i dont want see ?page=# 
![screenshot_7](https://user-images.githubusercontent.com/6858941/29133665-14f9c046-7ce9-11e7-9240-8fb8c5a8cbe9.png)

this is my code ISOTOPE + INFINITESCROLL+ LARAVEL

``` js
// init Isotope
var $grid = $('.grid').isotope({
  itemSelector: '.element-item',
  layoutMode: 'fitRows',
  filter: function() {
    return qsRegex ? $(this).text().match( qsRegex ) : true;
  }
});
// get Isotope instance
var iso = $grid.data('isotope');
// init Infinite Scroll
$grid.infiniteScroll({
  path: function() {
  var pageNumber = ( this.loadCount + 2 ) * 1;
  return '/restaurants-bars?page=' + pageNumber;
},
  // Infinite Scroll options
  // do not set append
  // do not set outlayer
});
// append items on load
$grid.on( 'load.infiniteScroll', function( event, response, path ) {
  var $items = $( response ).find('.element-item');
  // append items after images loaded
  $items.imagesLoaded( function() {
    $grid.append( $items );
    $grid.isotope( 'insert', $items );
  });
});
```

**Comment by desandro** [comment]
Thanks for reporting this issue. You can [disable changing the URL by setting `history: false`](https://infinite-scroll.com/options.html#history)
