### ISSUE TITLE
Could someone please share an example of how to make Infinite Scroll + Isotope to work properly?

### ISSUE THREAD

**Issue by Siilionu** [metafizzy/infinite-scroll#704]
Hi

This is a problem that causes a headache to many people. Let's finish it once and for all.

Could someone please share an example of how to make **Infinite Scroll** + **Isotope** to work properly?
Here is my code: https://codepen.io/anon/pen/gxoyEQ

Thank you.

**Comment by desandro** [comment]
See my response https://github.com/metafizzy/infinite-scroll/issues/674#issuecomment-311658109

**Comment by Siilionu** [comment]
Sorry. Not working! Can you just share a **working example** with **isotope** so that we can solve this problem for all of us? Just pointing is not helpful.

Here is my isotope code: https://codepen.io/anon/pen/gxoyEQ

Thanks for your hard work. :)
