### ISSUE TITLE
Big Issue in Bootstrap Modal

### ISSUE THREAD

**Issue by kalichaudhary** [metafizzy/infinite-scroll#708]
Initialise loading images problem in bootstrap modal.

**Comment by desandro** [comment]
Thank you for reporting this issue. I'm sorry to see you're having trouble with Infinite Scroll. Could you provide a **live URL**, or even better a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).

**Comment by kalichaudhary** [comment]
Recently I have leaved this plug-in. Now using jQuery self.
