### ISSUE TITLE
Load more button on first click than  infinite auto scroll 

### ISSUE THREAD

**Issue by oronoa** [metafizzy/infinite-scroll#709]
Thx for the wonderful plugin 
How can I achieve the above ? It's good UX to enable the user to be able to see the footer and after clicking load more be able to infinite scroll.

**Comment by desandro** [comment]
Thanks for this question. See [Click button to start loading](https://infinite-scroll.com/extras.html#click-button-to-start-loading-on-scroll)

``` js
var $container = $('.container').infiniteScroll({
  // options...
  // disable loading on scroll
  loadOnScroll: false,
});

var $viewMoreButton = $('.view-more-button');
$viewMoreButton.on( 'click', function() {
  // load next page
  $container.infiniteScroll('loadNextPage');
  // enable loading on scroll
  $container.infiniteScroll( 'option', {
    loadOnScroll: true,
  });
  // hide button
  $viewMoreButton.hide();
});
```

See [jQuery demo](https://codepen.io/desandro/pen/EXXGem) or [vanilla JS demo](https://codepen.io/desandro/pen/KqqbEd)
