### ISSUE TITLE
Status option does not work as intended

### ISSUE THREAD

**Issue by maimairel** [metafizzy/infinite-scroll#710]
Hi, 

I think the `status` option does not work as you would expect for the `last` and `error` statuses.
When those statuses are displayed, they should be kept on the screen after the events have ended.

Currently, you wouldn't even see the `last` status after the last page has loaded because it is immediately hidden after the content is appended/loaded.

Maybe I'm wrong, but I just wanted to make sure :)

Thanks!

**Comment by wipflash** [comment]
Same here too. it add `display: none;`

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm tracking this bug in #706
