### ISSUE TITLE
Cannot load owl slider 

### ISSUE THREAD

**Issue by wipflash** [metafizzy/infinite-scroll#711]
Cannot load owl slider inside the loaded div. the first page will load correctly but after that, it does not load.
![image](https://user-images.githubusercontent.com/8122779/30309041-a088dbd8-97a6-11e7-9470-188384fdc191.png)

**Comment by desandro** [comment]
After a new page is loaded, you'll have to initialize Owl Carousel where necessary. You can use the [`append` event](https://infinite-scroll.com/events.html#append)

``` js
$container.on( 'append.infiniteScroll', function( event, response, path, items ) {
  // init Owl carousel on appended items
  $( items ).find('.carousel').owlCarousel();
});
```

**Comment by starchild** [comment]
Hi, sorry to be a NOOB, but I'm struggling to get this working.

below is the IS code we're calling and below that is the owl-carousel code block.  can you please advise the correct syntax in this case?

`// init Infinite Scroll
$('.infinitescroll_cls').infiniteScroll({
  path: '.pagination__next',
  append: '.infinitescroll_cls_sub',
  status: '.scroller-status',
  hideNav: '.pagination',
    scrollThreshold: 3000,
    loadOnScroll: true,
    prefill: true
    
});`

`$(function() {
    $('.owl-carousel').owlCarousel({
        loop: false,
        rewind: true,
        lazyLoad: true,
        margin: 10,
        dots: true,
        responsive: {
            0: {
                items: 1
            },
            600: {
                items: 1
            },
            1000: {
                items: 1
            }
        }
    })
}); `
