### ISSUE TITLE
Add infinite scroll without the path being a real page

### ISSUE THREAD

**Issue by maimairel** [metafizzy/infinite-scroll#712]
Hi, 

Do you think it is possible to add a functionality that allows loading from a predefined source instead of real pages.

For example, infinite scrolling a masonry image gallery where there are numerous images, with their URLs already defined, but only the first twenty are shown. Then infinite scroll will load the next twenty by using some javascript function that creates the image markups and so on.

Thanks!

**Comment by desandro** [comment]
Hello! Thanks for opening this issue. Yes, you can do this with the current Infinite Scroll API, disabling [`loadOnScroll`](https://infinite-scroll.com/options.html#loadonscroll), and adding new items on [scrollThreshold event](https://infinite-scroll.com/events.html#scrollthreshold). See demo https://codepen.io/desandro/pen/jGObLQ

``` js
$grid.infiniteScroll({
  path: 'page{{#}}', // hack
  loadOnScroll: false, // disable loading
  history: false,
});

$grid.on( 'scrollThreshold.infiniteScroll', function() {
  // add grid items
  var $items = getItems();
  $items.imagesLoaded( function() {
    $grid.append( $items );
    $grid.masonry( 'appended', $items );
  });
});
```
