### ISSUE TITLE
Error When Returning No Html

### ISSUE THREAD

**Issue by williamlmetcalf** [metafizzy/infinite-scroll#714]
We are using Infinite Scroll along with Masonry.  We are using ASP.NET MVC to return a PartialView of our image HTML.  When we reach the end of our images, we return a PartialView that contains no HTML.  Infinite Scroll throws an error on the last page because the XMLHttpRequest response is null.

Here is our setup:

// Masonry
```
self.masonry({
     itemSelector: "masonry-item",
     percentPosition: true
})
```

// Infinite Scroll
```
self.infiniteScroll({
     path: url + "?page={{#}}",
     history: false,
     prefill: true,
     append: "masonry-item",
     outlayer: self.data("masonry")
})
```

**Comment by desandro** [comment]
Thanks for reporting this issue. So, to clarify, the request for the last page returns a response, but with no actual data/HTML. Is that correct? I'll have to add a test for this.

**Comment by williamlmetcalf** [comment]
That is correct.  We return a PartialView that contains no HTML. Thank you for looking into the issue.

**Comment by htapal** [comment]
@desandro I'm running into the same issue where I need to treat an empty response as an indicator that last page has reached.  Any update on this?

**Comment by desandro** [comment]
Closing in favor of #840
