### ISSUE TITLE
Auto load next post on Wordpress

### ISSUE THREAD

**Issue by j1f** [metafizzy/infinite-scroll#715]
Hello,

I'm currently trying to create an infinite scroll to automatically load the next post when you are already viewing a post. In fact, I want to reproduce the behavior of articles from https://qz.com or https://bloomberg.com.

With the following code, I only succeed to load the first next post, but the others... I think I miss something but I don't know what! Any ideas? :)

Here is my PHP:
```html
    <div class="articles">
        <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
            My content
        </article>
    </div>

    <div class="page-load-status">
        <p class="infinite-scroll-request">Loading...</p>
        <p class="infinite-scroll-last">End of content</p>
        <p class="infinite-scroll-error">No more pages to load</p>
    </div>

    <?php $prev = mod_get_adjacent_post('prev', array('post', 'videos')); ?>
    <?php if($prev) : ?>
        <div class="pagination">
            <a class="pagination_previous" href="<?php echo get_permalink($prev->ID)?>"><?php echo $prev->post_title; ?></a>
        </div>
    <?php endif; ?>
```

And my JS:
```javascript
    $('.articles').infiniteScroll({
        path: '.pagination_previous',
        append: 'article',
        status: '.page-load-status',
    });
```

**Comment by desandro** [comment]
Thanks for opening this issue. Others have asked about this. See my answer https://github.com/metafizzy/infinite-scroll/issues/688#issuecomment-316403688

**Comment by tapankumar** [comment]
@j1f : To load one story in advance, i have invoked below function after page load.

//Initially loading additional story
infScroll.loadNextPage();

Check if this helps.
