### ISSUE TITLE
app.bundle.js:25100 Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.

### ISSUE THREAD

**Issue by jesperlandberg** [metafizzy/infinite-scroll#716]
After updating to 3.0.1 for the "destory" fix I get another error when trying to use destroy().

"Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present."

Im using barba.js and im initalizing infinite scroll on enter and destroying on leave:

```
let infScroll = null

const Blogpage = Barba.BaseView.extend({
  namespace: 'blog',
  onEnterCompleted: function() {
    infScroll = new InfiniteScroll( '.js-articles-list', {
      path: '.js-load-more',
      append: '.js-article',
      button: '.js-load-more',
      scrollThreshold: false,
      status: '.page-load-status',
    })
  },
  onLeave: function() {
    infScroll.destroy()
  }
})
```

**Comment by desandro** [comment]
Thank you for reporting this issue. I'm sorry to see you're having trouble with Infinite Scroll. Could you provide a **live URL**, or even better a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).

**Comment by desandro** [comment]
Looks like this was a destroy with button bug. A fix will go out in the next release. See #719
