### ISSUE TITLE
Page scrolls with content?

### ISSUE THREAD

**Issue by jesperlandberg** [metafizzy/infinite-scroll#717]
I'm not sure why or if it has anything to do with this plugin but when i load more posts the page scroll position changes, so that it's always at the bottom of the container. This is not something I want.

my JS looks like this:
```
    infScroll = new InfiniteScroll( '.js-articles-list', {
      path: '.js-load-more',
      append: '.js-article',
      button: '.js-load-more',
      scrollThreshold: false,
      status: '.page-load-status',
    })
```

my markup looks like this:
```
<div class="articles-list">
  <div class="grid-x grid-margin-x js-articles-list">
      {% for entry in posts|slice(1) %}
          {% include 'components/articles/article.twig' %}
      {% endfor %}
  </div>
</div>
<div class="grid-x">
  <div class="cell">
    {% if pagination.next %}
      <a href="{{ pagination.next.link }}" class="btn js-load-more">Load more</a>
    {% endif %}
  </div>
</div>
```

**Comment by desandro** [comment]
Thank you for reporting this issue. I'm sorry to see you're having trouble with Infinite Scroll. Could you provide a **live URL**, or even better a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).
