### ISSUE TITLE
Javascript in Post/Loaded Page will not be performed

### ISSUE THREAD

**Issue by uponity** [metafizzy/infinite-scroll#718]
This Code will not be loaded in a infinite scroll loaded Page or Post:

```
<script src="https://scripts.tracdelight.com/tracdelight.js?accesskey=ac9a4cce18b76fdb586db1607be5bcec" async="async"></script>
<div class="td-widget" data-td-args="{'widget':'65n1sutdhx83mzfk'}">&nbsp;</div>
```

Have anyone a Solution for this?

Regards,
Danny

**Comment by desandro** [comment]
Thanks for reporting this issue. I believe the problem may be `async` attribute on the script tag. I'll have to investigate.

**Comment by uponity** [comment]
Hello, do you have some news for me?
Regards,
Danny

**Comment by josearagon** [comment]
I have same problem. Any news from this?
Thanks

**Comment by asberfer** [comment]
The same problem here, in my case I need to load Google ads along with the content, but the script tags loaded are empty, like so:

    <div id="ad-5a1d3b1e824b9" class="ad">
        <script type="text/javascript"></script>
    </div>

I've already checked and the content is retrieved ok, so I guess it has something to do with the append process. Any help would be appreciated.

Asur

**Comment by j1f** [comment]
I'm also facing this problem, any news about this?

**Comment by happynautpro** [comment]
Any Updates on this? I have the same problem.

**Comment by sechix** [comment]
Me too ...

**Comment by sechix** [comment]
Any updates?

**Comment by desandro** [comment]
🎉 v3.0.4 has been released with a patch added for executing the inline code in scripts.

Now, Infinite Scroll will execute JS code that's like:

``` html
<script>
  console.log('hello page 2!')
</script>
```

 Please update!

**Comment by sechix** [comment]
Hi, Now keep the scripts, but in my case not execute external scripts as for example modal popup inside new elements scrolled

**Comment by desandro** [comment]
@sechix Do you have a **live URL** I can take a look at? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).

**Comment by desandro** [comment]
I'm closing this issue as resolved. Please open a new issue if this issue pops up again.
