### ISSUE TITLE
Button won't disappear when last page has been loaded 

### ISSUE THREAD

**Issue by satrya** [metafizzy/infinite-scroll#721]
**Live URL:** http://ilovechrisbaker.com/

First, thank you for fixing the last issue with the status. Another issue I found is when using even to show and hide button. The `last` even not working in my case. Please check the Live URL, the console log message appeared but the button won't disappear. Here's my code:

```
$container = $( '.selected-projects' );

$container.infiniteScroll( {
	path: '.page-numbers .next',
	append: 'article.entry',
	scrollThreshold: false,
	status: '.page-load-status',
	history: false,
	checkLastPage: true
} );

var $viewMoreButton = $( '.more-projects' );
$viewMoreButton.on( 'click', function() {
	$container.infiniteScroll( 'loadNextPage' );
} );

$container.on( 'request.infiniteScroll', function( event, path ) {
	$viewMoreButton.hide();
} );

$container.on( 'append.infiniteScroll', function( event, response, path, items ) {
	$viewMoreButton.show();
	responsiveVideo();
} );

$container.on( 'last.infiniteScroll', function( event, response, path ) {
	$viewMoreButton.hide();
	console.log( 'Last!' );
} );
```

**Comment by desandro** [comment]
Thanks for reporting this issue. Looks like Infinite Scroll is not currently working on your site.

``` 
chrisbaker.min.js:1 Bad InfiniteScroll path option. Next link not found: .next a
r.updateGetPathSelector @ chrisbaker.min.js:1
chrisbaker.min.js:1 Disabling InfiniteScroll
```

**Comment by satrya** [comment]
Hi @desandro, please ignore the error message and please try the **Load More Projects** button.

![load](https://user-images.githubusercontent.com/891643/30754945-f494d4fc-9fee-11e7-9e4b-8af8d7476d43.png)

**Comment by desandro** [comment]
This is likely caused by a race condition where `last` event is triggered before the final `append` event. You can resolve this by adding a flag in your code.

``` js
var isLast = false;

$container.on( 'append.infiniteScroll', function( event, response, path, items ) {
	if ( !isLast ) {
		$viewMoreButton.show();
	}
	responsiveVideo();
} );

$container.on( 'last.infiniteScroll', function( event, response, path ) {
	$viewMoreButton.hide();
	isLast = true;
	console.log( 'Last!' );
} );

**Comment by satrya** [comment]
Nice, it is working. Thanks a lot, @desandro :)
