### ISSUE TITLE
Scrolling with more than images

### ISSUE THREAD

**Issue by RayKahn** [metafizzy/infinite-scroll#723]
I am having 3 issue with infinite-scroll:

1. Intermittent issue: no content gets loaded. When that happens I get the following from browser debug: 
/web/v2/providers/list?page={{#}}&types=1,2,3
infinite-scroll.pkgd.min.js:12 [InfiniteScroll] initialized. on portfolio grid-container portfolio-3 portfolio-full portfolio-nomargin portfolio-notitle clearfix
infinite-scroll.pkgd.min.js:12 [InfiniteScroll] request. URL: /web/v2/providers/list?page=2&types=1,2,3
plugins.js:524 Animsition: Element does not exist on page.
plugins.js:524 Animsition: Does not support this browser.
infinite-scroll.pkgd.min.js:12 [InfiniteScroll] load. . URL: /web/v2/providers/list?page=2&types=1,2,3

2. infinite-scroll breaks page when user scrolls down and up again.

3. infinite-scroll does not load the next batch of data (next pages).

JS code:

`<script type="text/javascript">
		
		var path = '/web/v2/providers/list?page={{#}}&types=<%= typesArray %>';
		var geoOptions = {
		    maximumAge: 5 * 60 * 1000,
		};

		if ("geolocation" in navigator) {
			
			var geoSuccess = function(position) {
			    path += "&latitude=" + position.coords.latitude + "&longitude=" + position.coords.longitude;
			};
			  var geoError = function(error) {
			    console.log('Error occurred. Error code: ' + error.code);
			    // error.code can be:
			    //   0: unknown error
			    //   1: permission denied
			    //   2: position unavailable (error response from location provider)
			    //   3: timed out
			  };
			
		  	navigator.geolocation.getCurrentPosition(geoSuccess, geoError, geoOptions);
		} 
		var $container = $('.portfolio').infiniteScroll({
			// use path string with {{#}} for page number
		  	path: path,
		  	// load response as flat text
		  	responseType: 'text',
		  	status: '.scroll-status',
		  	history: false,
		  	debug: true,
		});

		$container.on('load.infiniteScroll', function( event, response ) {
			// parse response into JSON data
		  	var data = JSON.parse( response );		  	
		  	// compile data into HTML
		  	var itemsHTML = data.map( getItemHTML ).join('');
		  	// convert HTML string into elements
		  	var $items =  $( itemsHTML );
		  	// append item elements
		  	$container.infiniteScroll( 'appendItems', $items );
		});

		// load initial page
		$container.infiniteScroll('loadNextPage');

		var itemTemplateSrc = $('#article-item-template').html();

		function getItemHTML( provider ) {
			return microTemplate( itemTemplateSrc, provider );
		}

		// micro templating, sort-of
		function microTemplate( src, data ) {
			// replace {{tags}} in source
		  	return src.replace( /\{\{([\w\-_\.]+)\}\}/gi, function( match, key ) {
		    	// walk through objects to get value
		    	var value = data;
		    	key.split('.').forEach( function( part ) {
		      		value = value[ part ];
		    	});
		    	return value;
		  	});
		}

	</script>`

Template code:
`<script type="text/html" id="article-item-template">
	  '<article class="portfolio-item pf-icons pf-illustrations">
			<div class="portfolio-image">
				<div class="fslider" data-arrows="false" data-speed="400" data-pause="4000">
					<div class="flexslider">
						<div class="slider-wrap">
							{{provider.images}}
						</div>
					</div>
				</div>
				<div class="portfolio-overlay" data-lightbox="gallery">
					{{provider.thumbs}}
				</div>
			</div>
			<div class="portfolio-desc">
				<h3><a href="/web/v2/provider/portfolio/{{provider.providerID}}">{{provider.parcticename}}</a></h3>
				<span><a href="#">{{provider.city}}, <i class="fa fa-car" aria-hidden="true"></i> {{provider.distance}}</a></span>
			</div>
		</article>'
	</script>`

HTML code:
`<section id="content">

			<div class="content-wrap nopadding">

				<a class="button button-full center button-light button-white" href="https://itunes.apple.com/us/app/bidbeauty/id1264954256?ls=1&mt=8" target="_blank">
					<div class="container clearfix">
						Download BidBeauty app from <strong>iOS App Store</strong> <i class="icon-caret-right" style="top:4px;"></i>
					</div>
				</a>

				
				<div id="portfolio" class="portfolio grid-container portfolio-3 portfolio-full portfolio-nomargin portfolio-notitle clearfix" >
				</div>
				<input type="hidden" name="typesArray" id="typesArray" vale="<%= typesArray %>">

				<div class="page-load-status" style="padding-top: 20px; border-top: 1px solid #DDD; text-align: center; color: #777;">
					<div class="loader-ellips infinite-scroll-request">
				    	<span class="loader-ellips__dot"></span>
				    	<span class="loader-ellips__dot"></span>
				    	<span class="loader-ellips__dot"></span>
				    	<span class="loader-ellips__dot"></span>
				  	</div>
				  	<p class="infinite-scroll-last">End of content</p>
				  	<p class="infinite-scroll-error">No more pages to load</p>
				</div>

			</div>

		</section>`

I have deployed the code to live site where you can see the issues:
https://www.bidbeauty.co/web/v2/providers

Thanks in advance.

**Comment by desandro** [comment]
Content is being loaded on the page. The problem is that its hidden. Likely by the slider or your CSS. I'm able to view content when I remove all the styles in `style.css`.

![screen shot 2017-09-29 at 9 45 41 am](https://user-images.githubusercontent.com/85566/31018703-fee12134-a4fa-11e7-804f-b99de2feeda8.png)

I recommend debugging by removing styles and seeing what's causing the issue.

**Comment by RayKahn** [comment]
Desandro,
Thanks for the response. You are correct when I remove the style.css reference from my html file it shows the result. Is there a way to determine what's causing the breakage? What do you recommend that I do to determine the root cause? I still need to format the page nicely.

Thanks
-r

**Comment by RayKahn** [comment]
BTW,
What does this error mean?

Uncaught TypeError: Cannot read property 'querySelectorAll' of null
    at n.s.appendNextPage (infinite-scroll.pkgd.min.js:12)
    at n.s.onPageLoad (infinite-scroll.pkgd.min.js:12)
    at n.<anonymous> (infinite-scroll.pkgd.min.js:12)
    at XMLHttpRequest.o.onload (infinite-scroll.pkgd.min.js:12)
s.appendNextPage @ infinite-scroll.pkgd.min.js:12
s.onPageLoad @ infinite-scroll.pkgd.min.js:12
(anonymous) @ infinite-scroll.pkgd.min.js:12
o.onload @ infinite-scroll.pkgd.min.js:12
XMLHttpRequest.send (async)
r @ infinite-scroll.pkgd.min.js:12
s.loadNextPage @ infinite-scroll.pkgd.min.js:12
s.onScrollThresholdLoad @ infinite-scroll.pkgd.min.js:12
e.emitEvent @ infinite-scroll.pkgd.min.js:12
s.dispatchEvent @ infinite-scroll.pkgd.min.js:12
(anonymous) @ infinite-scroll.pkgd.min.js:12
(anonymous) @ infinite-scroll.pkgd.min.js:12
setTimeout (async)
(anonymous) @ infinite-scroll.pkgd.min.js:12

**Comment by desandro** [comment]
Sorry, I'm not able to reproduce this issue.  Could you provide a **live URL**, or even better a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).
