### ISSUE TITLE
feature request: option `preloadFirstPage`

### ISSUE THREAD

**Issue by hirasso** [metafizzy/infinite-scroll#724]
Hi Dave, I will try to explain my use case as clear as possible:

I have a button on the bottom of my archive page, that, when clicked, initiates infiniteScroll. After being clicked, the button disappears and infiniteScroll keeps on loading subsequent pages. That works just fine.

Now comes the request: I would love if the first page from infiniteScroll would already be loaded on first button click, so that it would immediately be appended. Maybe you could introduce an option `preloadFirstPage: true` ? Or is a behaviour like this already possible with a clever use of the available options and events?

As always, thank you for your great products.

**Comment by otterslide** [comment]
`$container.infiniteScroll('loadNextPage');`
