### ISSUE TITLE
page-load-status not hidden on small content on 1st page

### ISSUE THREAD

**Issue by vincent3569** [metafizzy/infinite-scroll#727]
hi,

on loading next page, `style="display: none;"`  is added to status element (`.page-load-status`  in your [examples](https://infinite-scroll.com/options.html#status)).

but in case of the 1st page content do not fill the page, this style is not added on loading of the page, so the element is visible. it is hidden only after load event have been fired to load the 2nd page.
this element should be hidden on the first loading of the page to prevent displaying with small content.

maybe a new event `create` could manage that when an instance of infinteScoll is created but have nothing to do (request or load).

you can see a live example here : http://test.vincentbourganel.fr/page/gallery/

update : 
on codepen, in your example, there is a css rule on `.page-load-status`:
```
.page-load-status {
  display: none; /* hidden by default */
[...]
}
```

if you don't want to add the rule on init, at least you could document this (via an information).

**Comment by desandro** [comment]
Thanks for reporting this issue. Another, perhaps better, solution is to hide with JS after Infinite Scroll is initialized in JS

``` js
$('.container').infiniteScroll({...});
$('.page-load-status').hide();
```
