### ISSUE TITLE
AJAX pulled URL array not working for "path"

### ISSUE THREAD

**Issue by Minolta1034** [metafizzy/infinite-scroll#729]
OK so first thing, live URL: https://testing.androidheadlines.com/2017/8/in-motion-is-crowdfunding-an-electric-scooter-hybrid.html

You can take a look in the console and you should see a log entry of just a 0 (this is the loadCount) and then a url like "https://testing.androidheadlines.com/2017/08/lg-hombot-turbo-cr5765gd-review-everything.html" which is the first URL in my array of post URLs.

However when I attempt to return this same value to Infinite Scroll it respond with this error:

> Uncaught TypeError: Cannot read property 'match' of undefined

The JS I am using for the AJAX call is as follows:

```
  // init Infinite Scroll  
  var $container = jQuery('#load-article-bottum').infiniteScroll({
    path: getNextArticle,
    append: '#article-wrap',
    status: '.page-load-status',
    debug: true,
  });  
  
  function getNextArticle() {
      jQuery.ajax({
          method: 'POST',
          url: 'https://testing.androidheadlines.com/wp-admin/admin-ajax.php',
          data: {
              'action': 'ah_get_post_array' //this is the name of the AJAX method called in WordPress
          }, 
          success: handleNextArticle,
          error: function (data) {
              alert("error");
          }
      }); 
  }
  
  function handleNextArticle(data) {
            var infScroll = InfiniteScroll.data( '#load-article-bottum' )   
            var theCount = infScroll.loadCount;
            var resultArray = jQuery.parseJSON(data);
            var nextPost = resultArray[theCount];
            return nextPost;     
  }
```

So I am having a slight issue integrating the Infinite part of the script into my site. The script is saying it cannot read the property I am returning for path, however when I console log the variable it is a correct, fully formed URL?

Any assistance would be greatly appreciated.

**Comment by desandro** [comment]
Thanks for submitting an issue. Let's take a look at the function:

``` js
  function getNextArticle() {
      jQuery.ajax({
          method: 'POST',
          url: 'https://testing.androidheadlines.com/wp-admin/admin-ajax.php',
          data: {
              'action': 'ah_get_post_array' //this is the name of the AJAX method called in WordPress
          }, 
          success: handleNextArticle,
          error: function (data) {
              alert("error");
          }
      }); 
  }
```

When executed, `getNextArticle()` does not return any value. It has no `return`. See [path option docs](https://infinite-scroll.com/options.html#path).

Additionally,  I don't think your code will work the way you intend. Infinite Scroll handles making the request. If you wish just use Infinite Scroll's scroll watch behavior

+ do not set `append`
+ set `history: false`
+ set `path: '{{#}}'` as a sort  of placeholder

You can then make requests on [scrollThreshold](https://infinite-scroll.com/events.html#scrollthreshold)

``` js
$container.on( 'scrollThreshold.infiniteScroll', function() {
  jQuery.ajax(...)
});
```

**Comment by Minolta1034** [comment]
Thanks for the response! Still struggling with this haha.

So on success I am actually calling another function: handleNextArticle and that does have a return:

```
  function handleNextArticle(data) {
            var infScroll = InfiniteScroll.data( '#load-article-bottum' )   
            var theCount = infScroll.loadCount;
            var resultArray = jQuery.parseJSON(data);
            var nextPost = resultArray[theCount];
            **return nextPost;**     
  }
```

However I decided to modify my code to try and follow your guidelines. How would I modify the path or pass the info to it on that scroll event and replace the placeholder?

Here is my new code:

```
  var $container = jQuery('#load-article-bottum').infiniteScroll({
    path: '{{#}}',
    history: false,
    status: '.page-load-status',
    debug: true,
  });
  
  $container.on( 'scrollThreshold.infiniteScroll', function() {
      jQuery.ajax({
          method: 'POST',
          url: 'https://testing.androidheadlines.com/wp-admin/admin-ajax.php',
          data: {
              'action': 'ah_get_post_array' //this is the name of the AJAX method called in WordPress
          }, 
          success: function(data) {
            var infScroll = InfiniteScroll.data( '#load-article-bottum' )   
            var theCount = infScroll.loadCount;
            var resultArray = jQuery.parseJSON(data);
            var nextPost = resultArray[theCount];
            return nextPost;     
          },
          error: function (data) {
              alert("error");
          }
      });
  });   
```

This is still causing an issue, though I am now seeing an error for CreateListFromArrayLike called on non-object.

**Comment by Minolta1034** [comment]
So I modified my Path value to be a selector with a URL present on the page and I was able to get everything going, but I am still having trouble getting it to render the actual page URL I am passing.

I am now wondering if it would be better to dump the JSON array of posts in the header/footer of the page itself using PHP and then have the path variable read that array on page load instead of doing an AJAX call for it.

**Comment by desandro** [comment]
> I am now wondering if it would be better to dump the JSON array of posts in the header/footer of the page itself using PHP and then have the path variable read that array on page load instead of doing an AJAX call for it.

That could work. In which case, I recommend not using Infinite Scroll at all. You can handle all this behavior with customer jQuery code.
