### ISSUE TITLE
please help .......

### ISSUE THREAD

**Issue by w3ci** [metafizzy/infinite-scroll#731]
@#
**Test case:** [](http://codepen.io/desandro/pen/WOjqNM)
__

![qq 20171016161855](https://user-images.githubusercontent.com/8262509/31602065-7061d97a-b28e-11e7-8a3a-04b034fc5861.jpg)

**Comment by desandro** [comment]
Thank you for reporting this issue. I'm sorry to see you're having trouble with Infinite Scroll. Could you provide a **live URL**, or even better a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).

**Comment by w3ci** [comment]
@desandro 

URL: http://s.styletc.cn/

![qq 20171016161855](https://user-images.githubusercontent.com/8262509/31863198-deb78ae4-b77c-11e7-9c65-b4bb3a48c696.jpg
![qq 20171022225942](https://user-images.githubusercontent.com/8262509/31863199-f66851b4-b77c-11e7-9fc9-b8896252bc6c.jpg)
)

**Comment by desandro** [comment]
I believe there is some issue with the response returned from the server.  `response` is sometimes `null`. See also this error:

> 11.0.1.js?85e2bbe06f0295d89b7d678d76e3dc1b:1 A parser-blocking, cross site (i.e. different eTLD+1) script, http://s5.qhres.com/static/ab77b6ea7f3fbf79.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
