### ISSUE TITLE
Errors When Using Masonry with Infinite Scroll

### ISSUE THREAD

**Issue by braddalton** [metafizzy/infinite-scroll#734]
Getting errors when trying to use Masonry with Infinite Scroll. Can someone help please.

**Comment by desandro** [comment]
Hello! Looks like you're using old options for Infinite Scroll, but you've updated the JS. See [Upgrading from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2)

**Comment by braddalton** [comment]
Thanks however there is no infinite scroll demo which uses V3 and Masonry https://codepen.io/desandro/pens/tags/?selected_tag=infinite-scroll-docs

I did update the the options however it still doesn't work.

Please link to a live demo which uses Masonry and Infinite Scroll V3

**Comment by desandro** [comment]
Ah, sorry about that. That's the wrong link. The tag should be `infinite-scroll-v3-docs`. I'll update that. See https://codepen.io/desandro/pens/tags/?grid_type=list&selected_tag=infinite-scroll-v3-docs

+ [Masonry, Infinite Scroll, with jQuery](https://codepen.io/desandro/pen/eRRQVo) demo on CodePen
+  [Masonry, Infinite Scroll, with vanilla JS](https://codepen.io/desandro/pen/XgRpNr) demo on CodePen

Both of these are listed under [outlayer](https://infinite-scroll.com/options.html#outlayer)

**Comment by braddalton** [comment]
Thanks but do you have a demo like your old demo but which uses the new version?

This is what i need to do but with V3 https://masonry.desandro.com/v2/demos/infinite-scroll.html

**Comment by desandro** [comment]
The demos I provided are the best match for that old demo.

**Comment by braddalton** [comment]
Sorry but i don't have time to search thru 20 demos. Which one best matches the old demo i linked to?

**Comment by desandro** [comment]
[Masonry, Infinite Scroll, with jQuery](https://codepen.io/desandro/pen/eRRQVo) demo on CodePen
