### ISSUE TITLE
Get infinite scroll working for ajax/dynamically loaded content using Vanilla JS

### ISSUE THREAD

**Issue by priyashantha** [metafizzy/infinite-scroll#735]
I'm trying to use VanillaJS implementation for infinite scroll of my site. But I can't get it working for dynamically loaded content. But we can do that with jQuery using delegated click event handler like this:

```
        require('infinite-scroll')
        $(document).on('click', '.js-next-pagination', function(e) {
            e.preventDefault();

            var inf = $('.js-paginator-holder').infinitescroll({
                // options
            }, function (data) {});

            inf.infinitescroll('retrieve');
            return false;
        });
```

I tried the same event handler with VanillaJS like:

```
        var InfiniteScroll = require('infinite-scroll');
        document.addEventListener('click', function(e) {
            e.preventDefault();
            if (e.target.classList.contains('js-next-pagination')) {
                var inf = new InfiniteScroll('.js-paginator-holder', {
                    // options
                });
                // todo - retrieve stuff
            }
            return false;
        });
```

But I couldn't find a way of doing retrieve thing on VanillaJS implementation like jQuery does `inf.infinitescroll('retrieve');`. 

Could anyone suggest a proper way of accomplishing above thing?

**Comment by desandro** [comment]
Have you looked at [Button behaviors](https://infinite-scroll.com/extras.html#button-behaviors) demos?

**Comment by priyashantha** [comment]
Oh. I've totally missed that help. Sorry to bother you @desandro Thank you very much for pointing out that.
