### ISSUE TITLE
Change `elementScroll` after initialization

### ISSUE THREAD

**Issue by hirasso** [metafizzy/infinite-scroll#736]
Hi there, I have an infinite scroll instance that doesn't overflow on small screens, but becomes a fixed overflowing sidebar on larger ones. Is it possible to set the `overflowing` option on screen resize, like this?
```javascript
$(window).resize(() => {
  infScroll.elementScroll = $(window).width() > 998 ? true : false;
});
```

**Comment by desandro** [comment]
Thanks for this question. Sorry, no, you can only set `elementScroll` option on initialization. if you do want to change options on resize (which I feel is an unnecessary feature as users hardly ever resize their windows). Then you'll have to `destroy` and re-initialize.

``` js
var infScrollOptions = {
  path: 'a.pagination__next',
  // ...
};

var $window = $( window );
var $container = $('.container');
var isInfScrollInit = false;

function initInfiniteScroll() {
  // destroy previous instance
  if ( isInfScrollInit ) {
    $container.infiniteScroll('destroy');
  }
  // init Infinite Scroll
  infScrollOptions.elementScroll = $window.width() > 998;
  $container.infiniteScroll( infScrollOptions );
  // set flag
  isInfScrollInit = true;
}

// init first time
initInfiniteScroll();

$window.resize( initInfiniteScroll );
```
