### ISSUE TITLE
Destroy and Re-enable infiniteScroll

### ISSUE THREAD

**Issue by prokr** [metafizzy/infinite-scroll#737]
Hello, how is it possible to destroy and re-enable infiniteScroll?
Firebug always fires an error "Uncaught TypeError: d._init is not a function"
Or how is it possible to change the href of the next page to be loaded?
Sorry, I don't have test examples online, but you can try to run code on your infinitescroll

`$('.container').infiniteScroll('destroy');`

and then 

`('.container').infiniteScroll({
			path : '#page_nav a',
			append : '.item'
});`

Thank you.

**Comment by desandro** [comment]
See https://github.com/metafizzy/infinite-scroll/issues/688#issuecomment-316403688
