### ISSUE TITLE
Add previous page above first page

### ISSUE THREAD

**Issue by good2create** [metafizzy/infinite-scroll#738]
Hello,

When you open for example the full page demo (https://infinite-scroll.com/demo/full-page/) and scroll down to page 2 and refresh you cant scroll up to page 1 again. If you scroll up to the top you can reach only the page 2.

Please help, am I missing something?

Thanks, Henrik

**Comment by desandro** [comment]
This is how Infinite Scroll has been designed. It will not dynamically add content above the first loaded page.
