### ISSUE TITLE
Conserving the same url while scrolling and append

### ISSUE THREAD

**Issue by visualight** [metafizzy/infinite-scroll#740]
Hello,

I use infiniteScroll to append data frol another pages to one page.
The problem is : InfiniteScroll rewrite the url on scroll with the next page.
Example : blog/article (this url is rewrited on scroll by : /blog/article/1 ...)

Is it possible to disable the rewriting of the URL ? In fact when people refresh the page  the url must always : blog/article and not (blog/article/1 ...) 

Thank you

Code: 

```
var nextPages = [];
            for(var i=1; i < 10; i++)
            {
                nextPages.push('/blog/article/'+(i+1));
            }

            $grid.infiniteScroll({
                path: function() {
                    return nextPages[ this.loadCount ];
                },
                append: '.white-panel'
            });
```

**Comment by desandro** [comment]
> Is it possible to disable the rewriting of the URL ?

Set [`history: false`](https://infinite-scroll.com/options.html#history)

**Comment by pjforde1978** [comment]
Hey @desandro, I strongly encourage you to add the history:false option to the official docs.

I lost a bunch of time hunting this down tonight (went down an HTTP 304 rabbit hole) before ultimately removing the history.pushState call from the minified codebase. It's totally on me for not checking the GitHub issues first, of course... but I hope knowing history:false is a valid option will help others in the future.

Thanks again for your amazing contributions to web development.

**Comment by desandro** [comment]
You got it. [`history: false` mention added to docs](https://infinite-scroll.com/options.html#history)
