### ISSUE TITLE
Typo on the website

### ISSUE THREAD

**Issue by aleksspeaker** [metafizzy/infinite-scroll#741]
This is funny, but this typo killed a half of my day :)

<img width="667" alt="screen shot 2017-11-21 at 6 19 29 pm" src="https://user-images.githubusercontent.com/15803527/33083687-bb49321e-cee8-11e7-8a17-69e9478776c8.png">

Regards,

**Comment by desandro** [comment]
Thanks for reporting this. This typo is now fixed.

**Comment by aleksspeaker** [comment]
You're welcome.
Thanks for infinite-scroll. It's awesome! :D
