### ISSUE TITLE
Append to different container

### ISSUE THREAD

**Issue by lukesmithwp** [metafizzy/infinite-scroll#744]
Hey @desandro,   ##is there a way to append newly loaded items to a different div? For example, I need to request items from `.module-more .load-videos .video-contain`, but append those items to `.module-more .load-videos .video-contain .slick-track`.

This is the markup for the requested page:

```
<div class="module-more">
	<div class="load-videos">
		<div class="video-contain">
			<div class="video-block">...</div>
			<div class="video-block">...</div>
			<div class="video-block">...</div>
		</div>
	</div>
</div>
```
... and this the markup for the page I'm making the request from:
```
<div class="module-more">
	<div class="load-videos">
		<div class="video-contain">
			<div class="slick-list">
				<div class="slick-track">
					<div class="video-block">...</div>
					<div class="video-block">...</div>
					<div class="video-block">...</div>
					<----- [NEED TO APPEND HERE instead of the video-contain div.]
				</div>
			</div>
		</div>
	</div>
</div>
```

Basically I need to change the append container. **Here's what I was hoping for**:

```
var $container = jQuery('.module-more .load-videos .video-contain').infiniteScroll({
	
	path: 'page/{{#}}',
	status: '.load-more-videos .page-load-status',
	append: '.module-more .load-videos .video-contain .video-block',
	
	appendContainer: '.module-more .load-videos .video-contain .slick-track' <----- [SOMETHING LIKE THIS]
	
});
```
Is this possible? The reason is the "Slick" js plugin wraps my elements in two containers when initialized but the requested page does not initialize Slick obviously.

**Comment by desandro** [comment]
Yes, you can do this by disabling Infinite Scroll's automatic appending behavior by not setting `append`.  Then add you own custom behavior on [the `load` event](https://infinite-scroll.com/events.html#load).

``` js
var $containerA = $('.container-a').infiniteScroll({
  // options here, do not set append
});
var containerB = $('.container-b');

$containerA.on( 'load.infiniteScroll', function( event, response, path ) {
  // get items from response
  var $items = $( response ).find('.container-b .item');
  $containerB.append( $items );
});
```

**Comment by lukesmithwp** [comment]
Awesome, thanks so much!
