### ISSUE TITLE
Modify response before appending to the container - feature request

### ISSUE THREAD

**Issue by bravokiloecho** [metafizzy/infinite-scroll#745]
I think it would be very handy to be able to modify the markup of the response *before* it gets appended to the container.

I imagine this working something like:

```
$container.on( 'beforeAppend', function ( event, response ) {
    // Hide some els
    $(response).find('.some-els').hide();
});
```

Then when `.some-els` get appended to the container they already have `display: none` set.

Thanks!

**Comment by desandro** [comment]
Thanks for reporting this issue.

My recommendation to use [the `load` event](https://infinite-scroll.com/events.html#load) and disable automatic appending. This way you can control the behavior as you see fit.

``` js
var $container = $('.container').infiniteScroll({
  // options...
  // do not set `append`
});

$container.on( 'load.infiniteScroll', function( event, response, path ) {
  var $items = $( response ).find('.item');
  $items.hide();
  // add custom behavior here...
  $container.append( items );
});
```
