### ISSUE TITLE
Changing path option does not update load behavior

### ISSUE THREAD

**Issue by bravokiloecho** [metafizzy/infinite-scroll#746]
If you change the path option, infinite scroll does not acknowledge this change when loading the next page. Instead it continues to behave with whatever method it was initially setup with.

I've setup a crude test case below and with console logs to demonstrate what's going on. The path option is being changed like this:

```
infScroll.option({
     path: 'page/{{#}}'
});
```
(I know this would break the example, but it's just to show what's not happening!)

**Test case:** https://codepen.io/bravokiloecho/pen/OOGOGK

Thanks for any help!

**Comment by bravokiloecho** [comment]
I found a temporary solution of calling:
```
infScroll.updateGetPath()
infScroll.updateGetAbsolutePath()
```
after adjusting the path option. Not ideal but at least it works for now.

**Comment by desandro** [comment]
I recommend setting [`path` to a function](https://infinite-scroll.com/options.html#path) to return a dynamic path:

> Set to a function that returns the URL for page URLs that do not use incremental numbers. For example, A List Apart articles increment by 10. Use pageIndex and loadCount properties to calculate the URL.

``` js
path: function() {
  var pageNumber = ( this.loadCount + 1 ) * 10;
  return '/articles/P' + pageNumber;
}
// => /articles/P10, /articles/P20, /articles/P30 ...
```

**Comment by desandro** [comment]
You may also be interested in https://github.com/metafizzy/infinite-scroll/issues/688#issuecomment-316403688
