### ISSUE TITLE
How to use nextPenSlugs with HTML divs

### ISSUE THREAD

**Issue by samhayman** [metafizzy/infinite-scroll#752]
Hi Dave

I'm struggling to get this to work with HTML divs in a template

Here's [my live PEN](https://codepen.io/haymanpl/pen/GyNpjN)

I can't work out how to change the following code so it works with my HTML divs.

```
var nextPenSlugs = [
  '3d9a3b8092ebcf9bc4a72672b81df1ac',
  '2cde50c59ea73c47aec5bd26343ce287',
  'd83110c5f71ea23ba5800b6b1a4a95c4',
];
```

How do i use `<div class="item">` in replace of a slug in the above section of code as this template has no pagination?

I tried this but it doesn't work 

```
path: function() {
    
    var pageNumber = ( this.loadCount + 3 );
       
    return '?page=';  
      
    },
```
I need it to load 3 HTML items on button click each time not next page slugs. Thanks

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue.

The CodePen is a hack as it loads content from different URLs, rather than a typical site which would load content from `page2`, `page3`, `page4`, etc.

Can you describe what content you would like to load?

**Comment by braddalton** [comment]
Just images [as seen in the HTML](https://codepen.io/haymanpl/pen/GyNpjN), 1 row at a time

**Comment by desandro** [comment]
Okay. Where do the images URLs come from?

**Comment by braddalton** [comment]
Custom fields

**Comment by desandro** [comment]
Sorry, I don't understand what you're trying to achieve. Let me reset.

If you are loading content based on text or fields that you already have available, you may not need to use Infinite Scroll's loading behavior. You can just use it for [scrollThreshold event](https://infinite-scroll.com/events.html#scrollthreshold) and add content with custom code. recommend looking through

**Comment by braddalton** [comment]
I'd like to add a load more button so only 3 items display on page load and then more on button click.

**Comment by desandro** [comment]
Ah, in that case, if you want to change `path` to return a different URL, and that URL is contained within the loaded page HTML, you can do so. See https://github.com/metafizzy/infinite-scroll/issues/688#issuecomment-316403688

``` js
var nextURL;

function updateNextURL( doc ) {
  nextURL = $( doc ).find('.pagination__next').attr('href');
}
// get initial nextURL
updateNextURL( document );

// init Infinite Scroll
var $container = $('.container').infiniteScroll({
  // use function to set custom URLs
  path: function() {
    return nextURL;
  },
});

// update nextURL on page load
$container.on( 'load.infiniteScroll', function( event, response ) {
  updateNextURL( response );
});
```

**Comment by braddalton** [comment]
Thanks, i also need to load 3 items on click.

**Comment by braddalton** [comment]
Sure, [Try this](http://daltonwineltd.com/video-grid/)

**Comment by desandro** [comment]
Thanks for that. The big question is: where does the new content come from? Are you trying load subsequent pages? If so, what is their URL? Or, are you trying to create content by loading information from an API? If so, you may not need Infinite Scroll.

**Comment by braddalton** [comment]
Its added via custom fields. I just want to load one row of 3 items per button click.

**Comment by desandro** [comment]
WordPress custom fields are part of the CMS, but do they appear on the page's HTML or anywhere is a publicly viewable page?

Infinite Scroll is designed to load HTML from other pages on to current page. The current v3 version is solely a JavaScript library.

I'm sorry to say I do not have any expertise around the old Infinite Scroll WordPress plugin. This plugin has not been updated in years and I cannot vouch for its quality.
