### ISSUE TITLE
prefix string before ajax

### ISSUE THREAD

**Issue by tapankumar** [metafizzy/infinite-scroll#755]
Can we prefix any string in the url before infinite-scroll make ajax request.

My initial href url is "/a/b/c"

Before invoking ajax, i want to prefix like '/ajax/a/bc/' and than invoke ajax request

**Comment by tapankumar** [comment]
@desandro : We are planning to take team license of this library as it is doing everything which we want except above issue. Please help me to close this asap.

**Comment by desandro** [comment]
I recommend you set [`path` to a function](https://infinite-scroll.com/options.html#path) so you can manipulate the URL how you like.
