### ISSUE TITLE
Laravel paging, when href is empty, how to stop increasing the number of pages or stop loading new pages

### ISSUE THREAD

**Issue by bing8u** [metafizzy/infinite-scroll#758]
I use laravel, paging just shows the next page, the next page is empty [href=""], infiniteScroll continues to load the new page.
So I want the next page to be empty, and no longer continue to load the new page. 
How do I solve this problem?

**Comment by desandro** [comment]
One solution is to customize your HTML so the next page link with `href=""` does not display at all. Infinite Scroll will see that the link is not available and stop loading pages.

**Comment by bing8u** [comment]
http://yutuj.com/

**Comment by bing8u** [comment]
Online page： http://yutuj.com

The browser is required to use mobile mode access, such as the iPhone 6 Plus mode, and the other patterns are PC pages.


At the bottom of the page, there is a tab switch, and the content is indefinitely rolling, and it is at the moment:


When 1.tab clicks, $().Load () is loaded, then infiniteScroll should be updated, but I didn't find that infiniteScroll has updated methods, and only found infiniteScroll ('destroy').

I also use this. When I initialize infiniteScroll ({...}) again, there will be a mistake TypeError: instance._init is not a function, which cannot be initialized again. (a few times to switch back and forth, there will be a mistake)

Please tell me how to realize the limitless rolling idea of the following tab, **urgent!**
