### ISSUE TITLE
Double web request and starting on page 2 in the codepen demo

### ISSUE THREAD

**Issue by mbrice1012** [metafizzy/infinite-scroll#760]
I noticed these when evaluating your product. 
https://codepen.io/desandro/pen/LLjYgG/
Which was linked right from you [docs](https://infinite-scroll.com/options.html#responsetype) has two issues.

1. On start, it's sending two of the same web requests. This leads to duplicated data.
2. It's starting on page 2. Which doesn't make sense. Manually going to the url it looks like that unsplash api is built to go from 0-n. not 2-n. I'm assuming that's a bug.

See this image for reference:
![issue](https://user-images.githubusercontent.com/35908837/35492522-503dfb9e-047b-11e8-92b8-afa2597338d1.png)

**Comment by desandro** [comment]
Thanks for reporting this issue.

**# 1**, I see that Chrome lists two entries in _Network_ for the API call, one for _OPTIONS_ and one for _GET_. Firefox only lists one entry. 

![screen shot 2018-01-31 at 10 47 51 am](https://user-images.githubusercontent.com/85566/35632957-1d457d1e-0676-11e8-93b5-f05f0dbf44b0.png)

![screen shot 2018-01-31 at 10 47 36 am](https://user-images.githubusercontent.com/85566/35632962-20922be8-0676-11e8-8340-634d50c00294.png)

**# 2**, I've updated the demos to use a function for path with `this.pageIndex` to start at page **1**.

``` js
  path: function() {
    return 'https://api.unsplash.com/photos?client_id=...&page=' + this.pageIndex;
  },
```

**Comment by mbrice1012** [comment]
Ahh got it. Thanks for the help, good catch on that Options request.
