### ISSUE TITLE
Re-Initialize InfiniteScroll with New Options and Reset Pagination

### ISSUE THREAD

**Issue by thecortex** [metafizzy/infinite-scroll#762]
Hi,

I am trying to reinitialize the InfiniteScroll Object with new path function and reset count and index, but no luck. Any suggestions on how to update the path, index, count? I want for example to use it with a search query.

1- call infinite scroll with url: /ajax/?query=snoop
then the user can query different terms

2- call infinite scroll with url: /ajax/?query=samurai
then infinite scroll should reset all its parameters and start over...

**Comment by thecortex** [comment]
```
$('#search-form').submit(function (e) {
        e.preventDefault();
        //-------------------------------------//
        $grid.infiniteScroll('destroy');
        // init Infinte Scroll
        $grid.infiniteScroll({
          path: getPenPath,
          append: '.grid__item',
          outlayer: msnry,
          status: '.page-load-status',
          responseType: 'text',
        });
        // load initial page
        $grid.infiniteScroll('loadNextPage');
        return false;
    });
```
I have tried that approach, but yields an error as follows:
```
Uncaught TypeError: o._init is not a function
```

**Comment by thecortex** [comment]
I believe this is the correct way: 

```$container.infiniteScroll( 'option', {
      loadOnScroll: false,
    });```

**Comment by thecortex** [comment]
Reference here for details: https://infinite-scroll.com/extras.html#scroll-2-pages-then-load-with-button

**Comment by desandro** [comment]
Thanks for reporting this issue.

> I am trying to reinitialize the InfiniteScroll Object with new path function and reset count and index, but no luck.

Could you explain what behavior you are trying to achieve? Why are you trying to reset infinite Scroll? There may be a better solution.

**Comment by desandro** [comment]
Re `o._init is not a function`, see #768
