### ISSUE TITLE
masonry.layout not fired after infinateScroll.append on iOS (Chrom & Safari)

### ISSUE THREAD

**Issue by TmpR** [metafizzy/infinite-scroll#763]
Using the default masonry/infinite scroll demo JS and customised HTML I found that 'layout' does not get fired on Chrome or Safari on iOS.  As a work-around I have added the following code...

$grid.on( 'append.infiniteScroll', function( event, response, path, items ) {
      $grid.masonry('layout');
});

When the site goes live I'll update this with a live example. Sorry for not having the time to do a codepen, but I hope this issue report is useful.

**Comment by desandro** [comment]
Thanks for reporting this issue. A live URL would be great.
