### ISSUE TITLE
Scrolling backwards from end of scroll causes loading to occur again, how is this disabled?

### ISSUE THREAD

**Issue by arkid** [metafizzy/infinite-scroll#764]
I have a page that combines masonry with infinite scroll and it works fine except for this annoying detail.   There's no need for it to load again as you scroll back up from the end of the scroll.    How do I stop the loading occuring again ? 

**live url:** https://www.permanentstyle.com/styles-lookbook

**Comment by desandro** [comment]
Hi! Sorry to hear you're running into trouble.

> Scrolling backwards from end of scroll causes loading to occur again

I'm not sure I'm able to hit the 'end of scroll'. I've loaded 12 pages. How can I reproduce this issue?

**Comment by arkid** [comment]
Thanks for your time @desandro  yes the client had added a lot of images to the live page so its a bit time consuming.   I've created a copy here with only 20 images so its just one page load but enough to show the issue:  http://preview.permanentstyle.com/style-lookbook  
You will be asked for a login.  Use...
preview
preview123

**Comment by arkid** [comment]
Just to add some more detail... as you scroll up back up from the bottom of the page, empty content below the page footer in the site is being added.     That contains the wrapping DIV that I use to define masonry with and also tell infinite scroll to append to.    

So each time you scroll back up I get at the bottom of the body content another set of ...

`<div class="LookBookGrid">
	<nav id="pagination" style="visibility:hidden"><a class="prev page-numbers" href="http://preview.permanentstyle.com/style-lookbook/8">« Previous</a>
<a class="page-numbers" href="http://preview.permanentstyle.com/style-lookbook/1">1</a>
<a class="page-numbers" href="http://preview.permanentstyle.com/style-lookbook/2">2</a></nav>	<div style="clear:both"></div>
</div>`

**Comment by desandro** [comment]
On the first page, the `#pagination a` links to `http://preview.permanentstyle.com/style-lookbook/2`. On the second page, it links back to `http://preview.permanentstyle.com/style-lookbook/1`. It it loops back around. I believe this is causing the issue. If the second page is the last page then it should not include `#pagination a` HTML.

**Comment by arkid** [comment]
That makes total sense... brilliant thank you @desandro  !
