### ISSUE TITLE
codepen requests!

### ISSUE THREAD

**Issue by allonestring** [metafizzy/infinite-scroll#765]
Hi
When you have time, would you please make an infinite scroll masonry codepen using grid__items of fixed (px) rather than percentage widths? When I try to change your vanilla JS example, I always break it, so am clearly getting something muddled.
Would you also make an isotope/packry version, as I'm getting that muddled too?
I'm not linking to my pens as it's not worth it!
Thanks
Sal

**Comment by desandro** [comment]
Thanks for this request. I'll try to get to these once I get the chance.

**Comment by allonestring** [comment]
Hi

Thanks – that’d be great – no angst.

 

BTW, I’ve had a play with your loading dots: https://codepen.io/allonestring/pen/yKLwRb

Sal

**Comment by desandro** [comment]
Looks like this request didn't get any other interest. Alas, time to close
