### ISSUE TITLE
How to reload path from page 1 when reached the last page?

### ISSUE THREAD

**Issue by yokingma** [metafizzy/infinite-scroll#767]
Hi

I have a search result page that work with infinite scroll, 
I want to reload the path from page 1  when I change the search conditions. 
how to do it?

Thanks!

**Comment by desandro** [comment]
Thanks for reporting this issue.

One solution is to clear out the previous results, [`destroy`](https://infinite-scroll.com/api.html#destroy) the Infinite Scroll instance. Then create a new Infinite Scroll instance that uses a new path.

**Comment by yokingma** [comment]
@desandro Thank you very much, but it seems 'destroy' can not remove the instance completely?
so I reset the instance: 
```javascript
let infScroll = $('.container').data('infiniteScroll');
infScroll.pageIndex = 1;
infScroll.loadCount = 1;
infScroll.canLoad = true;
infScroll.isScrollWatching = true;
infScroll.bindScrollWatchEvents( true );
```
