### ISSUE TITLE
o._init is not a function

### ISSUE THREAD

**Issue by kamov** [metafizzy/infinite-scroll#768]
All seem work fine, but in console log after each new page load appear this error:

 o._init is not a function

**Comment by desandro** [comment]
Thank you for reporting this issue. I'm sorry to see you're having trouble with Infinite Scroll. Could you provide a **live URL**, or even better a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).

**Comment by desandro** [comment]
This bug is likely caused by calling `.infiniteScroll()` with jQuery after it has been initialized. jQuery Bridget expects a `_init()` method to be present. A fix has been added and will be in the next release.

**Comment by kamov** [comment]
Sorry, I see now notification.
Glad that you fixed.
