### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by Jdeezy** [metafizzy/infinite-scroll#769]
I'm seeing this in JSON lint:
Error: Parse error on line 1:
	ConfigurableMediaIma
-^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

Due to this code:
``` php
<?php
$_product = $this->getProduct();
$csmfHelper = Mage::helper('configurableswatches/mediafallback');
$swatchImageFallback = $csmfHelper->getConfigurableImagesFallbackArray($_product, array('small_image'), true);
?>
<script type="text/javascript">
	ConfigurableMediaImages.setImageFallback(<?php echo $_product->getId(); ?>, jQuery.parseJSON('<?php echo Mage::helper('core')->jsonEncode($swatchImageFallback); ?>'));
	ConfigurableSwatchesList.init();
</script>
```

on template/strategery/infinitescroll/swatches.phtml

If I'm not using swatch images in Magento, can I just comment out that code? I'm using jquery 3.3.1 btw.

**Comment by desandro** [comment]
This looks to be an issue with your Magento theme. Sorry I cannot provide expertise here.
