### ISSUE TITLE
Init breaks if path callback immediately returns void

### ISSUE THREAD

**Issue by Biont** [metafizzy/infinite-scroll#771]
As per the docs, the `path` callback should return void to signal that we have reached the end of content.
If however, this condition if met right at the first init, the plugin will fail to even start:

**Test case:** https://jsfiddle.net/bm2upo61/4/

**More elaborate example:** https://codepen.io/anon/pen/RMoOeV?selected_tag=infinite-scroll-v3-docs

The plugin requires the result of the path callback to be a string at least once because `proto.updateGetAbsolutePath` performs a regex on it.

If you're wondering about the use case: I added some select fields to filter the content by categories, then add the input values as GET parameters in the path callback. So it's entirely possible to navigate to a combination of categories that does not have any content. Then, if I refresh the page, infiniteScroll crashes

**Comment by desandro** [comment]
Thanks for reporting this bug. I'll look to fix this in a future release.

**Comment by desandro** [comment]
I'm now tracking this bug at #776
