### ISSUE TITLE
Cannot use two infinite scroll pagination in one page in cakephp

### ISSUE THREAD

**Issue by sakshisyscom** [metafizzy/infinite-scroll#772]
When I try to use 2 infinite scrolls in cakephp , using 2 pagintions in controller function, it is taking same page count for both paginations and ignoring rest posts' data.

**Comment by desandro** [comment]
Thank you for reporting this issue. I'm sorry to see you're having trouble with Infinite Scroll. Could you provide a **live URL**, or even better a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).

**Comment by sakshisyscom** [comment]
Login url:- http://syscomprojects.com/hundred/index.php 
Username:- tester Password:- 123456
After login:- Check this url :- http://syscomprojects.com/hundred/index.php/logins/timeline
Here , there are 19 wish posts and 18 people posts , both can be seen on click of wish list and people list respectively. We have used infinite-scroll pagination for both with limit of 3 in both . So according to limit, there will be 7 pages for wish and 6 pages for people, but it is taking 6 pages for both and missing last post in wish (numbered 1) and also this is behaving unexpectedly in some pages. How can we use 2 paginations in one page with infinite scroll and not missing any data. Kindly suggest anything for this issue.
