### ISSUE TITLE
Question: is inifinite scroll back instead of forward possible?

### ISSUE THREAD

**Issue by leroy0211** [metafizzy/infinite-scroll#773]
Our use case: 

We enter the page at page 50, the user scrolls a bit down, and then back up. Is it possible to let the user infinite scroll back up to page 49, 48, etc. with keeping the history state? 

Thanks for any help!

**Comment by desandro** [comment]
Hello! Sorry, no. Infinite Scroll does not support going back pages previous from the first page loaded.

From https://github.com/metafizzy/infinite-scroll/issues/728#issuecomment-339978291

> Scrolling up on a previous page is a significantly more complex UX problem than scrolling down. You have to account for how the up-content affects the current scroll position. Also consider how unloaded images/media would throw off scroll position.
> 
> Scrolling up could be a nice feature, but I'm doubtful that Infinite Scroll is the correct plugin for it.
