### ISSUE TITLE
Scrolling to the bottom with a footer stays inside footer

### ISSUE THREAD

**Issue by otterslide** [metafizzy/infinite-scroll#775]
If having a footer, scrolling down into the footer quickly causes all pages to load, and the page remains at the footer level:
https://codepen.io/otterslide/pen/oqGGXa

Load the page, scroll all the way down very quickly. Watch how all pages load, but the viewport shows only the footer. Is there any way to prevent this? Maybe something like HideNav, you can have HideFooter, which can show up only once all items are loaded?

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. I believe this is how browsers are designed to handle scroll. if you are the very bottom, and stuff on top loads in, you stay at the bottom.

If you do want to add extra logo about hiding the footer, you can do with [Infinite Scroll's events](https://infinite-scroll.com/events.html)
