### ISSUE TITLE
Path function to returns null on init

### ISSUE THREAD

**Issue by otterslide** [metafizzy/infinite-scroll#776]
When my path function returns null/false/undefined, it causes an error.
I have logic that at a certain point, the path function returns null, meaning no more pages.
How can I tell infinite scroll there are no more pages to load?

**Comment by desandro** [comment]
Thanks for reporting this issue. Can you provide a **reduced test case**? Try forking this demo which uses a path function: https://codepen.io/desandro/pen/ZxXNgR/

**Comment by otterslide** [comment]
Ok, it seems that it only happens if the initial call to the path function is null:
https://codepen.io/otterslide/pen/mxBZJP

infinite-scroll.pkgd.js:851 Uncaught TypeError: Cannot read property 'match' of null
    at InfiniteScroll.proto.updateGetAbsolutePath (VM500 infinite-scroll.pkgd.js:851)
    at InfiniteScroll.proto.create (VM500 infinite-scroll.pkgd.js:658)
    at new InfiniteScroll (VM500 infinite-scroll.pkgd.js:620)
    at VM501 pen.js:18

I should probably check if there are additional pages before even initializing infinite scroll in this case. I was checking in the Path function.

**Comment by desandro** [comment]
Thanks for that! I've added a fix that will go out in the next release.

**Comment by desandro** [comment]
🎉 v3.0.4 has been released with this fix added. Please update!

**Comment by matthiasprieth** [comment]
Hi, thanks for the fix. :)

- I came across the error message you've added & realized that my `loader-ellips infinite-scroll-request`-class is still showing up & not set to `display: none`. So when the error is thrown I guess the logic to hide it via script (and maybe showing "End of content" instead) is still missing.
In my case I just resolved it by setting `loader-ellips infinite-scroll-request` to `display: none` via a hidden class in my css-file at first render.    
```
<div class="page-load-status">
  <div class="loader-ellips infinite-scroll-request hidden">
    <span class="loader-ellips__dot"></span>
    <span class="loader-ellips__dot"></span>
    <span class="loader-ellips__dot"></span>
    <span class="loader-ellips__dot"></span>
  </div>
  <p class="infinite-scroll-last">End of content</p>
  <p class="infinite-scroll-error">No more pages to load</p>
</div>
```
- Also It would be nice to have something else than "console.log" echoing the message. It looks like an error but it isn't?

**Comment by dstopp** [comment]
for responseType: "text", i tried returning either nothing or null from path: option on end of data, but what i got was: infinite-scroll.pkgd.js:1265 GET http://127.0.0.1:8000/opus/null 404 (Not Found).  
Looking at the code w/a cursory glance, it seems that:
function request( url, responseType, onLoad, onError, onLast ) {
  var req = new XMLHttpRequest();
  req.open( 'GET', url, true );

needs to check to see if url is undefined or empty string but it doesn't; it treats it like a regular value. This seems to be really unfabulous...
