### ISSUE TITLE
TypeError: elem is undefined - custom query

### ISSUE THREAD

**Issue by p-drolima** [metafizzy/infinite-scroll#779]
Hi Desandro,

Hope you well. I am not 100% sure what this error means but I really cant see a solution for this so perhaps might be some kind of bug?

I have a custom wordpress query for which I get the correct return from server but then infinite scroll gives me TypeError: elem is undefined when loading next page. 

http://www.dawaf.co.uk/usfew/site/page/2/

Can you please see what is going on here?

Thank you in advance!

**Comment by p-drolima** [comment]
if you go to that link you will see a var_dump of count($query->posts) which means the query does return the correct amount of posts for next page but it does not display them which is the job of infnite-scroll

**Comment by desandro** [comment]
Thanks for reporting this bug. I'm not seeing it occur when I visit. Were you able to resolve this?

**Comment by p-drolima** [comment]
Hi,

Sorry, my client changed a setting. Let me put back the right setting.

**Comment by p-drolima** [comment]
ok, its back if you want to check. I have debug set to true

**Comment by desandro** [comment]
🎉 v3.0.4 has been released with this fix added. Please update!
