### ISSUE TITLE
hide 'view more button' and hideNav when no paging found (how to)

### ISSUE THREAD

**Issue by csychester** [metafizzy/infinite-scroll#780]
Hi Desandro,

This is related to 'Next link not found on last page error #730' but i cant find a resolution.. My jquery is based on https://codepen.io/desandro/pen/jwwdEq 'load 2 pages and load with button' 

Im using this for a products page and all works fine until I have a page with no paging links ( the number of products on the page is less than the paging increment)

i know this is not an error 'Bad InfiniteScroll path option. Next link not found: .paging li a 
infinite.js:2 Disabling InfiniteScroll'  but the infinite scroll has been disabled but in this instance how do I still hide the 'view more' button and my paging (hideNav) I want to keep inifiate scroll enabled if no link found which would be '.paging li span'  instead of '.paging li a'

Hope this makes sense.. 

Thanks in advance

**Comment by desandro** [comment]
You can hide the button with jQuery

``` js
var $nextLink = $('.paging li a');
if ( !$nextLink.length ) {
  $('.view-more-button').hide();
}
```

Or you can choose to not add the view-more-button to the HTML in your page template code.

**Comment by csychester** [comment]
Thanks Desandro..

Works well..
