### ISSUE TITLE
Network recovery

### ISSUE THREAD

**Issue by otterslide** [metafizzy/infinite-scroll#781]
I am trying the test case, and even on my own site:
http://codepen.io/desandro/pen/WOjqNM
If I set the network to offline and scroll down, the error handler gets triggered.
Once the network is set back to online, moving the scrollbar down does no re-initiate a request.  How can we get the infinite scroll to continue trying on scroll event even after an error?
There is a way to catch "internet down" , I believe with a -1 error code. That could be caught and the script would know it can continue re-trying.
Another way would be to have an optional parameter, if there is a nextUrl, always keep re-trying.
It would be nice if the error handler could receive the error object, and by returning true or false, it would tell the script if it should continue re-trying.

Another nice feature could be to automatically re-try without scroll event once there is an error, on a optional interval, and optional retry count.

Thanks.

**Comment by desandro** [comment]
Thanks for this feature request! **Add a 👍  reaction** to this issue if you would like to see this feature added. Do not add +1 comments — [They will be deleted](http://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by otterslide** [comment]
Probably the easiest solution would be to display a "Load More..." button  with an error message above it.
That might even work right now? I can define the loadMore button, and then on Error I can display it.

**Comment by desandro** [comment]
Looks like this feature request did not get much interest. Alas! I'm now closing
