### ISSUE TITLE
Firefox does not work below

### ISSUE THREAD

**Issue by weii2008** [metafizzy/infinite-scroll#783]
First thank the author

After I use this plugin, it can be automatically loaded in other browsers, but it will always be interrupted in Firefox and Microsoft Edge 41. The class name will be wrong.

`var $grid = $('.thumbnail-post-list').packery({
  // Packery options...
 itemSelector: '.article-item-card',
	gutter: 20,
	transitionDuration: '200ms',
});
// get Packery instance
var pckry = $grid.data('packery');
$grid.infiniteScroll({
	path: '#pagination-ajax a',
	append: '.article-item-card',
	hideNav: '#pagination-ajax',	
	button: '.view-more-button',
	scrollThreshold: 100,
	status: '.scroller-status',
	outlayer: pckry,
});
var $viewMoreButton = $('.view-more-button');
// get Infinite Scroll instance
var infScroll = $grid.data('infiniteScroll');
$grid.on( 'load.infiniteScroll', onPageLoad );
function onPageLoad() {
  if ( infScroll.loadCount == 3 ) {
    // after 2nd page loaded
    // disable loading on scroll
    $grid.infiniteScroll( 'option', {
      loadOnScroll: false,
    });
    // show button
    $viewMoreButton.show();
    // remove event listener
    $grid.off( 'load.infiniteScroll', onPageLoad );
  }
}`

It will appear once
`<p class="infinite-scroll-error" style="display: block;">xxx</a></p>`

[InfiniteScroll] error. Error: Network error requesting

**Comment by desandro** [comment]
Thank you for reporting this issue. I'm sorry to see you're having trouble with Infinite Scroll. Could you provide a **live URL**, or even better a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).

**Comment by weii2008** [comment]
Hello, you can visit this live page, preferably with Firefox. thank you very much

[](https://t.co/WcDI4hQiws)

**Comment by desandro** [comment]
Thanks for that. I was able to load several pages with Firefox. I did not encounter any bugs, nor see `Network error requesting`.
