### ISSUE TITLE
Fancybox with call Infinite scroll 

### ISSUE THREAD

**Issue by ieraora** [metafizzy/infinite-scroll#784]
Hi, In this example https://codepen.io/ieraora/pen/xWomYj I have Infinite scroll with Fancybox. The "first page" has 18 images. If I start Fancybox before launch the second page, fancybox stop at the 18° image. For you, how can I implement fancybox to call infinite scroll, and than continue view the other images?
Thank you.

**Comment by desandro** [comment]
Hello! I was able to find `fancyapps/fancybox#1479`. You can dynamically add content with `addContent` method. You would use it on [Infinite Scroll's `append` event](https://infinite-scroll.com/events.html#append). 

See demo https://codepen.io/desandro/pen/GdRzmL

``` js
var fancybox = $.fancybox.getInstance();

// with Infinite Scroll initialized in vanilla JS
infScroll.on( 'append', function( response, path, items ) {
  fancybox.addContent( items );
});
```


``` js
var fancybox = $.fancybox.getInstance();

// with Infinite Scroll initialized in jQuery
$container.on( 'append.infiniteScroll', function( event, response, path, items ) {
  fancybox.addContent( items );
});
```

**Comment by ieraora** [comment]
Thank you for your replay.
Sorry, but unfortunately I don't understand. I see your demo, but with fancybox I terminate to view gallery at 18° image, instead I would that fancybox call images of second page of infinite scroll.
![inkedscreenshot 2018-04-18 22 50 53_li](https://user-images.githubusercontent.com/22258422/38957720-9c5fd226-435b-11e8-9e29-af1ba4cb696b.jpg)

**Comment by fancyapps** [comment]
@desandro Actually, your code around fancybox is redundant, because, when you initialize fancybox using `selector` option, fancybox will start with all currently existing items (e.g., including fleshly added items).

What you need is to use callback to load fresh items, something like:

$().fancybox({
    selector : '[data-fancybox="images"]',
    buttons : [
		'share',
		'thumbs',
		'close'
	],
	beforeShow: function(instance, current) {
		// We have reached last item
		if (current.index === instance.group.length - 1) {
                        // Get new items
                        // var newItems = ... <- I am not sure how to do that

			// and append to this instance
                       // instance.addContent( newItems );
		}
	}
});

**Comment by ieraora** [comment]
I'm sorry, for you it's a solution? Thanks
