### ISSUE TITLE
What is a valid path value? DOMException: Failed to execute 'querySelector' on 'Document'

### ISSUE THREAD

**Issue by jinyus** [metafizzy/infinite-scroll#788]
I am getting this error when I try to put the path to the next page as the "Path" options. What am I doing wrong?
DOMException: Failed to execute 'querySelector' on 'Document': 'http://localhost:5000/index?page=2' is not a valid selector.

``` js
var nxt = "http://localhost:5000" + "{{ next_url }}";
var infScroll = new InfiniteScroll( grid, {
  path: nxt,
  append: '.grid__item',
  outlayer: msnry,
  status: '.page-load-status',
});
```

**Comment by jinyus** [comment]
I figured out what was wrong. I someone has a similar problem in the future. This is the change that I made:
function getPath() {
  var more = document.getElementById('nxt').href;
    return more;
  }
    var infScroll = new InfiniteScroll( grid, {
        path: getPath,
        append: '.grid__item',
        outlayer: msnry,
        status: '.page-load-status',
    });
    </script>  `

`

**Comment by desandro** [comment]
Thanks for following up!
