### ISSUE TITLE
Infinite scroll not working with Default permalinks of WordPress

### ISSUE THREAD

**Issue by anandau** [metafizzy/infinite-scroll#789]
Hi 

I am trying to use Infinite scroll in a WordPress project and trying to add it to the category. 
It works fine until i set permalink to plain

Now the page permalink for category page is following 
`http://example.com/?paged=2&cat=3`

Now when i scroll down it  doesn't load next page properly. It actually loads following url 
`http://example.com/?paged=2&cat=4`

If you notice, it is incrementing category (**cat**) parameter instead of **paged** which is actuall parameter to denote page number. 

When i tried to investigate what exactly happening in your code, i found that there are 3 regex rules defined 
`var pathRegexes = [
  // WordPress & Tumblr - example.com/page/2
  // Jekyll - example.com/page2
  /^(.*?\/?page\/?)(\d\d?\d?)(.*?$)/,
  // Drupal - example.com/?page=1
  /^(.*?\/?\?page=)(\d\d?\d?)(.*?$)/,
  // catch all, last occurence of a number
  /(.*?)(\d\d?\d?)(?!.*\d)(.*?$)/,
];`

Here  WordPress regex is only covering WordPress pretty permalink and not plain permalink. So it fallbacks to last option, ie. incrementing last occurence of a number, which in this case is category id. 

Can you suggest a solution for this? Or suggest a regex rule for default WordPress permalink.

**Comment by desandro** [comment]
Thanks for reporting this issue! I'll look into adding a regex to capture the `paged` parameter for WordPress.

For now, you can set [`path` with `{{#}}`](https://infinite-scroll.com/options.html#path)

``` js
path: '/?paged={{#}}&cat=3'
```

**Comment by desandro** [comment]
Closing this feature request as it didn't get much interest
