### ISSUE TITLE
"The value is only accessible if the object's 'responseType' is '' or 'text' (was 'document')"

### ISSUE THREAD

**Issue by thingsneverchange** [metafizzy/infinite-scroll#792]
Hi,

Just started using the version 3, but I don't seem to make it work on my side. The installation seems to be easy, and I did it right as the documentation displays, but I get this error : 

```
The value is only accessible if the object's 'responseType' is '' or 'text' (was 'document')
```

Code:
```
document.addEventListener('DOMContentLoaded', function(){ 
                                    
                                    var infScroll = new InfiniteScroll(document.getElementById('posts'), {
                                          path: '/page/{{#}}'
                                    });
       })
```

Also, is there any way to turn off the URL update? The previous version didn't support this feature, and I am not a big fan of it! Sorry. I know it's useful for some case, but not for the website I am building. 

Thank you.

**Comment by desandro** [comment]
Second question first:

> is there any way to turn off the URL update? 

Yes, set [`history: false`](https://infinite-scroll.com/options.html#history)

---

To your first question, can you confirm what kind response `/page/2` on your site returns? Looks like there's some of kind error with that URL or its response.

**Comment by thingsneverchange** [comment]
Hello there! Thanks for the quick response. Anyways, I had to go back to the previous version as the new one doesn't seem to work. My company's been using the infinite scroll (version 2) for four years, and had no problem with it. Not really sure if it's on our end, or the script.

I did a simple AJAX call to the '/page/2', and it returns as expected; the '#posts' container in the HTML, and contents in it as how the version 2 does. Response header:

```
accept-ranges: "bytes"
cache-control: "no-store"
content-encoding: "br"
content-length: "19987"
content-type: "text/html; charset=UTF-8"
date: "Sat, 12 May 2018 02:35:13 GMT"
server: "openresty"
status: "200"
strict-transport-security: "max-age=15552001"
vary:"X-UA-Device, Accept, Accept-Encoding
```

**Comment by desandro** [comment]
Thanks for reporting back. This is the first I've encountered this issue. Maybe someone else can chime in if they run into it as well.
