### ISSUE TITLE
Shopify collection — less than half the content being loaded

### ISSUE THREAD

**Issue by j-greig** [metafizzy/infinite-scroll#795]
This Shopify collection contains hundreds of products, but Infinite Scroll stops working after about the first 4 pages of the 13 that are available.

Can you help me identify why?

https://orro-jewellery.myshopify.com/collections/everything

Thank you! :)

**Comment by desandro** [comment]
Sorry, I wasn't able to open that page. It is password protected.

Be sure to enable [debug](https://infinite-scroll.com/options.html#debug) and check the logs.
