### ISSUE TITLE
scrollThreshold not unbound when container is removed from dom

### ISSUE THREAD

**Issue by Enalmada** [metafizzy/infinite-scroll#796]
I use [pjax](https://github.com/defunkt/jquery-pjax) to swap out parts of the page body content without a full pageload.  When I have a page with infinite scroll on it and then pjax it out with other content, bindings seem to persist.  When I scroll on the new "page" that has no infinite scroll on it anymore, I still get "[InfiniteScroll] scrollThreshold" in the console.

Since pjax loads in new content dynamically that may or may not replace existing infinite scroll, handling this manually is undesirable.  infinite-scroll should detect when its container has been removed from the dom and unbind its events.

Test case: https://s.codepen.io/adam-lane/debug/qYGEbd/XxMVwaZBNeOr

I am hoping that infinite-scroll could have something like this in it...
```
$('.container').bind('DOMNodeRemoved', function(event) {
    destroy();
});
```

**Comment by desandro** [comment]
> infinite-scroll should detect when its container has been removed from the dom and unbind its events

**Add a 👍  reaction** to this issue if you would like to see this feature added. Do not add +1 comments — [They will be deleted](http://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

Hmm, maybe. But I think this behavior it better suited for client-side code, rather than in Infinite Scroll.

**Comment by desandro** [comment]
Straightforward solution is to trigger [`destroy`](https://infinite-scroll.com/api.html#destroy) on the client side on page exit.

**Comment by desandro** [comment]
I'm closing this issue as this feature request did not get a lot of interest.
