### ISSUE TITLE
prefill can cause infinite loop

### ISSUE THREAD

**Issue by Enalmada** [metafizzy/infinite-scroll#797]
If there are not enough items in pagination to fill viewable layout, prefill goes into infinite loop.  Seems like the problem is that append 0 items doesn't end the prefill.   The docs suggest that prefill stops when there are no more items but this codepen seems to suggest that is not true:

Test case: https://codepen.io/adam-lane/pen/WJBQaZ

```
[InfiniteScroll] request. URL: https://s.codepen.io/...
[InfiniteScroll] load. CodePen - Infinite Scroll - page ...
[InfiniteScroll] append. 0 items. URL: https://s.codepen.io/...?page=1
[InfiniteScroll] prefill
...
[InfiniteScroll] append. 0 items. URL: https://s.codepen.io/...?page=2
...
[InfiniteScroll] append. 0 items. URL: https://s.codepen.io/...?page=3
...
```

**Comment by desandro** [comment]
Thanks for reporting this issue. Yes, given this scenario, `prefill` option will continue loading subsequent pages. But I feel this scenario is an edge case. Wouldn't the pages eventually run out?

Currently, if 0 items are returned, Infinite Scroll will try loading the next page. I could add a check for 0 items and stop. 
**Add a 👍  reaction** to this issue if you would like to see this feature added. Do not add +1 comments — [They will be deleted](http://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by edgarcosta** [comment]
I don't think this is a bug.

You stop the infinite scroll with `checkLastPage` option.

**Comment by desandro** [comment]
Looks like no one 👍 ed this issue. I am closing this issue.
