### ISSUE TITLE
Accordion and Infinte scroll

### ISSUE THREAD

**Issue by lexa45ru** [metafizzy/infinite-scroll#798]
When adding an accordion to the page, there are problems with history event,
When the accordion is opened, the trigger zone of the change event of the URL (history) moves to the opened accordion (On load accordion is closed)
And If accordion open on load page, the trigger zone of the change event of the URL (history) moves to the loaded page. 
Shift on height of accordion.

How to make that when you open / close the accordion, the change zone for the URL is also shifted?

P.S. Sorry for google translate.

**Comment by desandro** [comment]
I think the easiest solution is to disable history

``` js
history: false
```

**Comment by lexa45ru** [comment]
Yes this easiest method working, but i need change url also

**Comment by desandro** [comment]
Sorry but Infinite Scroll does not provide an easy way to handle this kind of behavior — with constantly changing page heights. You'll have to decide between `history` or the accordion behavior.

**Comment by lexa45ru** [comment]
it's a pity.
