### ISSUE TITLE
Infinite-scroll not working with isotope-imagesloaded on metabox fields query  on wordpress

### ISSUE THREAD

**Issue by MarameoDesignIT** [metafizzy/infinite-scroll#799]
Hello, I'm trying to add infinite scroll on a wall of isotope-imagesloaded images, the field I use is a metabox adv-image into a "portfolio" custom type.

the link to the not-working page (normally works without infinitescroll)
http://gianni.imilani.com/portfolio/classico/

Using the latest js from infinite-sroll.

//my php-tpl

<div class="single-portfolio-wall are-images-unloaded">
						 <div class="single-sizer"></div>
						 <div class="gutter-sizer"></div>
					<?php
						$bg_img = rwmb_meta('mbs_foto_slider', true);

						if (count($bg_img) > '0' ) {
							foreach ($bg_img as $attachment_id => $img_full_url) {
							$slider_img = wp_get_attachment_url($attachment_id);
							$slider_th = wp_get_attachment_image($attachment_id, 'masonry-thumb', "", array( "class" => "masonry" ));

							echo '<div class="single-portfolio-isotope">';
							echo '<a class="colorbox group1 img-responsive" href="'. $slider_img .'">';
							echo $slider_th;
							echo '</a>';
							echo '</div>';
							}

						} else
							if ( has_post_thumbnail() ) : ?>
						<?php
							$thumb = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID), 'medium' );
							$url = $thumb['0'];
							?>
							<a class="colorbox col-xs-12" href="<?php echo $url ?>" title="<?php the_title_attribute(); ?>">
									<?php the_post_thumbnail( 'portfolio-thumb' ); ?>
							</a>
						<?php endif; ?>
				</div> 
//

and this is the related part of my custom js

// init Masonry

    var $grid = $('.single-portfolio-wall').masonry({
      itemSelector: 'none', // select none at first
      columnWidth: '.single-sizer',
      gutter: '.gutter-sizer',
      percentPosition: true,
      stagger: 30,
      // nicer reveal transition
      visibleStyle: { transform: 'translateY(0)', opacity: 1 },
      hiddenStyle: { transform: 'translateY(100px)', opacity: 0 },
    });

    // get Masonry instance
    var msnry = $grid.data('masonry');

    // initial items reveal
    $grid.imagesLoaded( function() {
      $grid.removeClass('are-images-unloaded');
      $grid.masonry( 'option', { itemSelector: '.single-portfolio-isotope' });
      var $items = $grid.find('.single-portfolio-isotope');
      $grid.masonry( 'appended', $items );
    });

        //
    // init Infinte Scroll

    $grid.infiniteScroll({
      append: '.single-portfolio-wall',
      outlayer: msnry,
      status: '.page-load-status'
    });

Thanks a lot for suggestions, as someone says...i'm going slightly mad :(

**Comment by lexa45ru** [comment]
InfiniteScroll path option required. Set as: undefined

**Comment by MarameoDesignIT** [comment]
the problem is that is a non-paginated list of items... thanks for suggestion!

**Comment by MarameoDesignIT** [comment]
Thanks again lexa45ru, yesterday I found a tricks about pagination in a codepen (something like [*]), but unable to find it today... there was used infinite-scroll+isotope+imagesloaded for a list of images without pagination, I know that it is a required filed, but unble to get it working without pagination....

I hope that Desandro apperas here, he has the straight solution on the go...:)

**Comment by MarameoDesignIT** [comment]
found it!
https://codepen.io/desandro/pen/jGObLQ

but unable to get it works with my tpl-php...

**Comment by lexa45ru** [comment]
All briks in this examle add with this functions^
`$grid.on( 'scrollThreshold.infiniteScroll', function() {`
If you need pre-known number of photos, just  change array
`var itemClasses =[`
or try disable this action
`$grid.on( 'scrollThreshold.infiniteScroll', function() {`

**Comment by MarameoDesignIT** [comment]
Hi lexa,
unable to find a working solution, my js skills are very poor :(
Thank you for effort :)
Await the Author for a tricks if he'll have the time!

**Comment by desandro** [comment]
@MarameoDesignIT The code you are using is from Issue #712, which fakes loading in content by dynamically creating elements.

What effect are you trying to create?

My guess is that you have all the images in HTML on the page. But you want Infinite Scroll to load them in & add them to Masonry layout as you scroll. Is that correct?

**Comment by MarameoDesignIT** [comment]
Hi Dave, yes you are right but those images (from a query loop in wp) does't have pagination... so I used that ricks about page {{#}}...
thanks a lot for help!

**Comment by desandro** [comment]
Sorry, I will not be able to provide support on this issue.
