### ISSUE TITLE
Infinite Scroll and BarbaJS

### ISSUE THREAD

**Issue by josefarrugia** [metafizzy/infinite-scroll#800]
Hi there,

I have been struggling to get this resolved when it comes to having video elements on a page coupled with the BarbaJS framework. Do you have any sample code that I can refer to?

URL: http://beta.mariansell.com

**Comment by desandro** [comment]
Sorry, I don't have any examples of Infinite Scroll and Barba.js. 

I appreciate you providing a live URL, but I'd be better able to find a solution working with **reduced test case**. Could you try [forking this demo](https://codepen.io/desandro/pen/WOjqNM) and adding the Barba code you're trying to use?
