### ISSUE TITLE
IE: WrongDocumentError

### ISSUE THREAD

**Issue by Erando89** [metafizzy/infinite-scroll#802]
Hi there,
I cannot provide a CodePen example as this error for some reason doesn't appear in that demo but it occurs in my application though. I am just going to explain what happens in detail, present my solution and let you decide for yourself what to do with that particular information.
This problem does only occur in Internet Explorer (not Edge), I am "using" version 11.48.17134.0.

Just like in your [CodePen example](https://codepen.io/desandro/pen/WOjqNM) I initialize InfiniteScroll and when the first page gets loaded the plugin trys to append the new items to the existing DOM. Therefore it appends all items to a [`fragment`](https://developer.mozilla.org/de/docs/Web/API/DocumentFragment). This is where I get the [`WrongDocumentError`](https://developer.mozilla.org/de/docs/Web/API/DOMError) error in my application using IE 11. I included to [un-minified version](https://unpkg.com/infinite-scroll@3/dist/infinite-scroll.pkgd.js) of the plugin and the error is located in the following function:

```javascript {.line-numbers}
function getItemsFragment( items ) {
  // add items to fragment
  var fragment = document.createDocumentFragment();
  for ( var i=0; items && i < items.length; i++ ) {
    fragment.appendChild( items[i] );
  }
  return fragment;
}
```

It happens when the first item is supposed to get appended to the `fragment`. I don't know why that happens in my application but won't happen in the demo. I could solve the problem though by altering the code as follows (found final hint [here](https://stackoverflow.com/questions/1759137/domelement-cloning-and-appending-wrong-document-error)):

```javascript {.line-numbers}
function getItemsFragment( items ) {
  // add items to fragment
  var fragment = document.createDocumentFragment();
  for ( var i=0; items && i < items.length; i++ ) {
    var newNode = document.importNode(items[i], true);
    fragment.appendChild( newNode );
  }
  return fragment;
}
```

Did anyone ever encounter that problem as well?

**Comment by desandro** [comment]
Thanks for reporting this issue. Can you provide more information:

+ What options have you set? Specifically, `append`
+ What kind of content does you page have? Images, video, iframe, ?

**Comment by Erando89** [comment]
Hi desandro,

it's just plain HTML getting loaded and appended.

```javascript
$container.infiniteScroll({
	path: function() {
		if ( this.loadCount < 24 ) {
			var url = $('#infiniteScrollPage-nav a.next').attr('href');

			if(url.indexOf('page=') > 0) {				
				var posAfterPage = url.lastIndexOf('page=') + 5;
				var str1 = url.substr(0, posAfterPage);
				var str2 = url.substr(posAfterPage + 1, url.length);
			} else {				
				var posAfterPage = url.lastIndexOf('/') + 1;
				var str1 = url.substr(0, posAfterPage);
				var str2 = url.substr(posAfterPage + 1, url.length);
			}
			console.log("nextLink: " + (str1 + (this.pageIndex + 1) + str2));
			return str1 + (this.pageIndex + 1) + str2;
		}
	},	
	append: '#entrycontainer .entry',
	hideNav: '#infiniteScrollPage-nav',
	history: false,
	debug: true,
	status: '.page-load-status'
});
```

I cannot provide a live URL as this version is not live yet.

**Comment by desandro** [comment]
Thanks for that! Okay, everything looks good so far. I'll need a **live URL** to fix this.
