### ISSUE TITLE
Prevent init when next page path does not exist

### ISSUE THREAD

**Issue by kaleidografik** [metafizzy/infinite-scroll#806]
Hey @desandro - quick question.

On a page where infinite scroll exists, but there are not enough posts to generate a next page <a> tag, is it possible to deactivate infinite scroll to avoid console errors?

Currently, on a page that should show 12 posts per page, anytime less than 12 posts exist I get the console errors "infinite-scroll.pkgd.min.js:12 Bad InfiniteScroll path option. Next link not found: .pagination .next a" and "Disabling InfiniteScroll".

Anything we can do to eliminate these?

Thanks.

**Comment by desandro** [comment]
Thanks for reporting this issue. Those console errors are just logs. They will not negatively affect your other JS from executing. Feature, not a bug 😁

Yes, you can prevent Infinite Scroll from initializing in your own JS

``` js
// jquery
if ( $('.posts').length > 11 ) {
  $('.container').infiniteScroll({...});
}
```

**Comment by kaleidografik** [comment]
Perfect, thanks @desandro! Appreciate all your hard work on the various libraries.
