### ISSUE TITLE
Refresh InfiniteScroll + Masonry + remote source

### ISSUE THREAD

**Issue by nusoft** [metafizzy/infinite-scroll#807]
Hi, my website shows photos like this CodePen, but with photos from a remote source: https://codepen.io/desandro/pen/eRRQVo

Now I would like to add a button which will 'refresh' the InfiniteScroll instance, to show newly added photos from the remote source. I tried with `$container.infiniteScroll('destroy')` and reinitializing InfiniteScroll, but that gives an error `Uncaught TypeError: o._init is not a function`

Any ideas? Thanks in advance!

**Comment by nusoft** [comment]
Hi, thanks for your reply. I added my code to your pen (I tried 2 different methods): https://codepen.io/anon/pen/aKMzLa

**Comment by desandro** [comment]
Thanks for that. You should be able to re-initialize both Infinite Scroll and Masonry by first destroying both plugin instances

``` js
$(document).on("click", ".reload", function(e) {
  $grid.infiniteScroll('destroy');
  $grid.masonry('destroy');
  initMasonry();
});
```

See demo https://codepen.io/desandro/pen/ab2cc8162dde24c18ff12caf360d6186

However, there currently is a bug that doesn't properly remove jQuery data on `destroy`. I've added a fix for this that will be in the next release.  Until then, you can this [duck punch](https://metafizzy.co/blog/duck-punching-prototype/)

``` js
// duck punch
var destroy = InfiniteScroll.prototype.destroy;
InfiniteScroll.prototype.destroy = function() {
  destroy.apply( this, arguments );
  // remove jQuery data
  if ( jQuery && this.$element ) {
    jQuery.removeData( this.element, 'infiniteScroll' );
  }
};
```

**Comment by nusoft** [comment]
Awesome! Thanks a lot!

**Comment by desandro** [comment]
Infinite Scroll v3.0.5 has been released.
