### ISSUE TITLE
".infinite-scroll-request" doesn't disappear

### ISSUE THREAD

**Issue by taengoo890309** [metafizzy/infinite-scroll#808]
<a href="http://marshall-ku.tistory.com">http://marshall-ku.tistory.com</a>

I already checked <a href="https://github.com/metafizzy/infinite-scroll/issues/706">this issue</a>, but I still can't get why '.infinite-scroll-last' never appears.
I tried almost everything that I can do.

**Comment by desandro** [comment]
I am able to see the loading indicator in `.infinite-scroll-request`. Were you able to resolve this issue?

**Comment by taengoo890309** [comment]
nope. when I scroll down to final page, .infinite-scroll-request should disappear and .infinite-scroll-last should appear but the script keep trying to load next page. And I think it makes .infinite-scroll-request blinks.

**Comment by taengoo890309** [comment]
I solved the issue. Thx
