### ISSUE TITLE
Load items on scroll to the top of the page and append items to the top of previous ones.

### ISSUE THREAD

**Issue by akoSalman** [metafizzy/infinite-scroll#810]
Hi
Thank you for that good package.
I'm loading items(messages) in a messenger when user scrolls to the top of the page and then append loaded items to the top of previous items, is there any configuration in the package to do that?

**Comment by desandro** [comment]
Sorry, Infinite Scroll does not support loading new content on top. You can add a 👍 reaction to #728 to help promote this feature request. Closing this issue as a duplicate.
