### ISSUE TITLE
Jump To specific page 

### ISSUE THREAD

**Issue by lordhasyim** [metafizzy/infinite-scroll#812]
is it possible to jump to specific page?
let say i have url like this
www.example.com/tittle-hello.html#page=3

can i jump to the third pagination base on url fragment "#page=3", 

Thanks

**Comment by desandro** [comment]
Yes, you can load arbitrary pages by writting your own custom function for [`path` option](https://infinite-scroll.com/options.html#path)

**Comment by lordhasyim** [comment]
Thanks for the answer, i'll try it first, for now i'll close the issue
