### ISSUE TITLE
Where is dependency module located?

### ISSUE THREAD

**Issue by yosualb** [metafizzy/infinite-scroll#815]
if ( typeof define == 'function' && define.amd ) {
    // AMD
    define( [
      'infinite-scroll/js/core',
      'infinite-scroll/js/page-load',
      'infinite-scroll/js/scroll-watch',
      'infinite-scroll/js/history',
      'infinite-scroll/js/button',
      'infinite-scroll/js/status',
    ], factory );
  } else if ( typeof module == 'object' && module.exports ) {
    // CommonJS
    module.exports = factory(
      require('./core'),
      require('./page-load'),
      require('./scroll-watch'),
      require('./history'),
      require('./button'),
      require('./status')
    );
  }

**Comment by desandro** [comment]
See [Webpack instructions](https://infinite-scroll.com/extras.html#webpack-browserify). You should require `'infinite-scroll'` as a npm/yarn package. `pkgd.js` is for people who just want a single `.js` file and not use module loaders.
