### ISSUE TITLE
Scrolling anywhere in page triggers div loading

### ISSUE THREAD

**Issue by mhluzi** [metafizzy/infinite-scroll#818]
Hi there

I am really hoping to get this going but at the moment I have an issue with scrolling. Hopefully it is something I am just doing wrong.

What I would like is to have a page similar to the https://infinite-scroll.com/#versatile-ui page that has a div with an infinite scroll. Currently I have that set up locally using laravel and pagination. That all works but the issue is when I go to the page and scroll anywhere in the page the infinite scroll div then loads the rest of the records.

This is replicated here : https://codepen.io/Mhluzi/pen/QBmRRb - the first time you go to this page try scrolling down and you will see that content loading is triggered for both divs.

Is there perhaps something simple that I am missing? I would like to only have the infinite scroll load on the div that is specifically being scrolled.

Thanks 
M.

**Comment by desandro** [comment]
>  I would like to only have the infinite scroll load on the div that is specifically being scrolled

[Set `elementScroll`](https://infinite-scroll.com/options.html#elementscroll)

> Sets scroller to an element for overflow element scrolling. Disabled by default, window is used to scro

**Comment by mhluzi** [comment]
Thank you for the reply - works as expected - https://codepen.io/Mhluzi/pen/ejaqKj
