### ISSUE TITLE
colorbox popup loading problem

### ISSUE THREAD

**Issue by sharadaddictivemedia** [metafizzy/infinite-scroll#819]
Hello,
   I am using  infinite-scroll in my project for load more button on a web page in cakephp2.x . I am using colorbox popup for image slides and popup for youtube video . but when page load popup working fine but after appending element  popup not working please suggest me. the link is given bellow when i click load more button it is not working.

http://192.168.1.120/hy/pages/video

http://192.168.1.120/hy/workshop

**Comment by desandro** [comment]
After new items are added you your page, you may need to add these new items for other plugins.

So, if you already initialized colorbox on the original images like so:

``` js
$('.post a.gallery').colorbox();
```

You can initialize colorbox on the newly appended posts, with [append event](https://infinite-scroll.com/events.html#append):

``` js
$container.on( 'append.infiniteScroll', function( event, response, path, items ) {
  $( items ).find('a.gallery').colorbox();
});
```
