### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by runnickrun** [metafizzy/infinite-scroll#820]
https://infinite-scroll.com/api.html#appenditems has an error:

![image](https://user-images.githubusercontent.com/18515722/43965735-b7927f14-9cc8-11e8-92fe-137fa3566f52.png)

`$container.on( 'load.infiniteScroll', function( response ) {`
should be
`$container.on( 'load.infiniteScroll', function( event, response ) {`
otherwise it returns event object and doesn't work.

**Comment by desandro** [comment]
Thank you for reporting this issue! Fixed!

**Comment by Shaked** [comment]
Not sure where to post this, but although obvious I'd also add in the [documentation](https://infinite-scroll.com/api.html#appenditems) [somewhere](https://infinite-scroll.com/extras.html#loading-json) that when using `$container.infiniteScroll( 'appendItems', $items );` one should make sure to remove the `append: '.post'` option.
