### ISSUE TITLE
Programatic Reload Current Page

### ISSUE THREAD

**Issue by kfalconer** [metafizzy/infinite-scroll#823]
We have dynamic data that we would like to periodically refresh via polling. How can we force a reload from the configured URL and replace the content?

**Comment by desandro** [comment]
> How can we force a reload

[You can set `path` to a function](https://infinite-scroll.com/options.html#path), so you can use conditional statement or whatever logic you like to reset a URL to load (i.e., reload `page/2` after user hits `page/5`.
