### ISSUE TITLE
infinite-scroll-last doesn't appear

### ISSUE THREAD

**Issue by gyp1143** [metafizzy/infinite-scroll#825]
[test url](http://html-test.tistory.com/category/)
Thought I solved the problem, but it wasn't.

I almost copied the code in[ your demo](https://codepen.io/desandro/pen/eRRQVo).
Even if the script loads last page, "infinite-scroll-request" keeps blinking when scroll, and "infinite-scroll-last" never appears.

Is there something that I did wrong?

**Comment by desandro** [comment]
Since the extra pages have valid URLs, then Infinite Scroll will try to load the content in them. A better solution is to return a 404 response.
