### ISSUE TITLE
Infinite load simple divs items (WordPress)

### ISSUE THREAD

**Issue by TenebralG** [metafizzy/infinite-scroll#826]
This could be the easiest question, but as you can see I'm learning.

I'm trying to do something like [this](https://codepen.io/desandro/pen/jGObLQ). But I'm using simple `<div class="loadthisnow"></div>` as items.

Sadly, after several hours, I couldn't get it right.

Live test URL: [testing](https://therpgstore.com/rpghome/page-2/)

This is my code right now:
```
jQuery(document).ready(function($){
var $container = $('.page-content').infiniteScroll({
  path: 'page{{#}}', // hack
  loadOnScroll: false, // disable loading
  history: false,
scrollThreshold: 10,
debug: true,
});

$container.on( 'scrollThreshold.infiniteScroll', function() {
     $container.infiniteScroll( 'appendItems', $('.loadthisnow') );
});
});
```

Also, where should be the recommended position to do this? inside `</head>` or `</body>`?

Thank you for your time!

**Comment by desandro** [comment]
Were you able to resolve this issue?

**Comment by TenebralG** [comment]
> Were you able to resolve this issue?

No, this one was difficult to achieve, any help would be appreciate! thanks!

**Comment by desandro** [comment]
If you want to create an element, you'll have to set the jQuery object to a HTML string:

``` js
$container.on( 'scrollThreshold.infiniteScroll', function() {
     $container.infiniteScroll( 'appendItems', $('<div class="loadthisnow" />') );
});
```
