### ISSUE TITLE
[Question] License clarification

### ISSUE THREAD

**Issue by Braintelligence** [metafizzy/infinite-scroll#828]
Hello everyone, I just wanted to get a clarification on the license.

GPLv3 does explicitly allow commercial use, I just have to keep the copyleft-shebang in mind, which is not too hard to fulfill for GPL (other than AGPL) in web projects.

But you guys state that "If you want to use Infinite Scroll to develop commercial sites, themes, projects, and applications, the Commercial license is the appropriate license." which sounds as if you don't allow commercial usage of infinite-scroll with the GPLv3 license.

This in turn would breach the GPLv3 license, since it clearly allows commercial use.

Thus I would like to receive clarification if it is allowed to use infinite-scroll in a commercial context without aquiring a commercial license to further elaborate properly if this project is truly ran under offical GPLv3.

**Comment by desandro** [comment]
Thanks for asking this question.

Yes, you may use Infinite Scroll v3 in commercial projects under the GPLv3, so long as you adhere to the 'copyleft-shebang.'

I specifically wrote about use in commercial projects as this is easiest way for most of my customer base to understand if they need to purchase a license or not. It's less confusing than discussing what is and is not open-source, or what licenses are compatible with GPL. Also - I feel it has a stronger moral thread - if you're making money on your thing with a Metafizzy plugin, you should likely use some of that money to support the Metafizzy plugin.

**Comment by Braintelligence** [comment]
If you would like to more often make money by using a Metafizzy plugin I'd suggest switching to AGPL, because of the more strict copyleft-implication for web-services.
It wouldn't be possible to create backend-apps working with infinite-scroll without open-sourcing the whole backend-code IMO.

**Comment by desandro** [comment]
Ah! Thanks for the info. Another issue is that lots of developers want their code to be GPL compatible for Wordpress, so I choose GPL to maintain consistency.

**Comment by Braintelligence** [comment]
AFAIK you can combine GPLv3 and AGPLv3 work, which in turn would be licensed as AGPLv3 as a whole, so I don't see a problem using infinite-scroll under AGPLv3 for Wordpress currently.

**Comment by desandro** [comment]
I appreciate the insight here!

**Comment by garak** [comment]
I think there's a mistake in how GPL license is proposed.
You can't restraint someone for *using* a GPL software in a commercial project, since GPL is about *distribution*.
So, I can't distribute a proprietary project using this library with GPL license, but I can use this library inside an undistributed proprietary project (using GPL license of this library)
