### ISSUE TITLE
History with turbolinks

### ISSUE THREAD

**Issue by kierangillen** [metafizzy/infinite-scroll#830]
Hello,

Is it possible to pass the first javascript object param to `replaceState` and/or `pushState`? 

Both support a stateObj:

```
var stateObj = { foo: "bar" };
history.pushState(stateObj, "page 2", "bar.html");
```

This is necessary for those of us using turbolinks, as you need to pass `{ turbolinks: {} }` as the object to force page load on back button.

Reference: https://github.com/turbolinks/turbolinks/issues/219

Thanks for all your great products!
-Kieran

**Comment by desandro** [comment]
> Is it possible to pass the first javascript object param to replaceState and/or pushState?

One way to achieve this is with a [duck-punch](https://metafizzy.co/blog/duck-punching-prototype/). Add this JS before you initialize Infinite Scroll:

``` js

proto.setHistory = function( title, path ) {
  var optHistory = this.options.history;
  var historyMethod = optHistory && history[ optHistory + 'State' ];
  if ( !historyMethod ) {
    return;
  }

  history[ optHistory + 'State' ]( this.options.historyState, title, path );

  if ( this.options.historyTitle ) {
    document.title = title;
  }

  this.dispatchEvent( 'history', null, [ title, path ] );
};
```

You can then set a `historyState` option in your options

``` js
$('.container').infiniteScroll({
  historyState: { turbolinks: {} },
  ...
});
```
