### ISSUE TITLE
Run function after each injection

### ISSUE THREAD

**Issue by leewdch** [metafizzy/infinite-scroll#835]
Is it possible to run a function after each injection? I'm testing infinite-scroll on a website that checks on each page load if the posts are blacklisted and if that's true it removes a css class from the post element basically making it visible again. I think I found the two function used for blacklist checks but I don't know if I can run them after each injection from infinite-scroll

**Comment by desandro** [comment]
Yes. You can use events like [append](https://infinite-scroll.com/events.html#append) or [load](https://infinite-scroll.com/events.html#load)

**Comment by leewdch** [comment]
Ok I figured out how to run a function after each injection (example for reference).
```
infScroll.on( 'append', function( response, path, items ) {
  console.log("test");
});
```
I found out that rechecking the entire list after each run isn't really efficient. Is there a way to alter each item before the injection? Say for example I have a list of items like this:
```
<ul>
  <li>test</li>
  <li>test2</li>
  ..
  <li class="not_needed_class">testN1</li>
  <li class="not_needed_class">testN2</li>
  <li class="not_needed_class">testN3</li>
</ul>
```
can I get rid of each <li> class before the injection?

**Comment by desandro** [comment]
Use the `items`, its an array of elements that have been added.
