### ISSUE TITLE
Add fade effect on load

### ISSUE THREAD

**Issue by acris20** [metafizzy/infinite-scroll#836]
**Test case:** http://codepen.io/desandro/pen/WOjqNM

Hi is it possible to add a fade effect when a new page is loaded?

**Comment by desandro** [comment]
Yes, you can do with this the [append event](https://infinite-scroll.com/events.html#append).

``` js
$container.on( 'append.infiniteScroll', function( event, response, path, items ) {
  $( items ).whatever();
});
```

**Comment by acris20** [comment]
thanks
