### ISSUE TITLE
Adsense with Infinite scroll

### ISSUE THREAD

**Issue by ofyalcin** [metafizzy/infinite-scroll#838]
I'm using infinite scroll.

When user scroll to bottom, displaying the previous post. This plugin automatically changes the URL and browser title.

Ads within the content are automatically displayed when the new post is loaded. Does this situation violate Adsense rules?

**Comment by desandro** [comment]
Sorry, I am not an expert on how Adsense works, so take my response with a grain of salt.

Infinite Scroll loads the same content that would appear on loading the next page. The URL matches to the scrolled page. I don't believe this would violate Adsense rules.
