### ISSUE TITLE
How to get this pagination to infinite scroll?

### ISSUE THREAD

**Issue by UisgeBeatha436** [metafizzy/infinite-scroll#839]
Hi,

No issue, but a 'how to'. Hope someone can help me out. The articles come from a cms, and becaue of that, I can't show a live example.

I have a blog showing a summary of all articles available. This is done via a foreach-loop:
``` html
{foreach from=$items item=entry}
        <article class="post">
    		       {show article summary}
       </article>
{/foreach}
```
  
The pagination is done via a href-tag:

``` html
{if $pagenumber < $pagecount}
   <div class="page-load-status">
        <p class="infinite-scroll-request">
            <a class="pagination__next" href="{$nexturl}&showtemplate=true" rel="nofollow">Next page</a> 
        </p>
    </div>
{/if}
```

Just before the </body> I have
``` html
<script>
  var elem = document.querySelector('.container');
  var infScroll = new InfiniteScroll( elem, {
  // options
    path: '.pagination__next',
    append: 'true',
  });
</script>
```

The next-button is shown and by pressing, the next set of articles is loaded, but no automatic loading of the next set of articles. What am I overlooking?

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll. From the code you have provided, everything looks okay. You could enable [debug option](https://infinite-scroll.com/options.html#debug) to get more information.

**Comment by UisgeBeatha436** [comment]
Thanks for getting back to me.

Following your suggestion, the first time the page loads, the debug windows (Firefox Developer) shows in the log:

> [InfiniteScroll] pageIndex. current page determined to be: 6 from next link infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] initialized. on container infinite-scroll.pkgd.min.js:12:6621

After pressing 'next page', it shows:

> [InfiniteScroll] pageIndex. current page determined to be: 6 from next link infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] initialized. on container infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] scrollThreshold infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] request. URL: /index.php?mact=CGBlog,m804b0,default,1&m804b0summarytemplate=blogSummary_LeftRight&m804b0number=5&m804b0pagenumber=4&m804b0returnid=7&page=7&showtemplate=true infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] scrollThreshold infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] scrollThreshold infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] scrollThreshold infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] scrollThreshold infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] scrollThreshold infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] load. Artkelen - Develop Uisge Beatha. URL: /index.php?mact=CGBlog,m804b0,default,1&m804b0summarytemplate=blogSummary_LeftRight&m804b0number=5&m804b0pagenumber=4&m804b0returnid=7&page=7&showtemplate=true infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] append. 0 items. URL: /index.php?mact=CGBlog,m804b0,default,1&m804b0summarytemplate=blogSummary_LeftRight&m804b0number=5&m804b0pagenumber=4&m804b0returnid=7&page=7&showtemplate=true infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] scrollThreshold infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] request. URL: /index.php?mact=CGBlog,m804b0,default,1&m804b0summarytemplate=blogSummary_LeftRight&m804b0number=5&m804b0pagenumber=4&m804b0returnid=7&page=8&showtemplate=true infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] scrollThreshold
> infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] scrollThreshold infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] load. Artkelen - sitename. URL: /index.php?mact=CGBlog,m804b0,default,1&m804b0summarytemplate=blogSummary_LeftRight&m804b0number=5&m804b0pagenumber=4&m804b0returnid=7&page=8&showtemplate=true infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] append. 0 items. URL: /index.php?mact=CGBlog,m804b0,default,1&m804b0summarytemplate=blogSummary_LeftRight&m804b0number=5&m804b0pagenumber=4&m804b0returnid=7&page=8&showtemplate=true infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] scrollThreshold infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] request. URL: /index.php?mact=CGBlog,m804b0,default,1&m804b0summarytemplate=blogSummary_LeftRight&m804b0number=5&m804b0pagenumber=4&m804b0returnid=7&page=9&showtemplate=true infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] load. Artkelen - sitename. URL: /index.php?mact=CGBlog,m804b0,default,1&m804b0summarytemplate=blogSummary_LeftRight&m804b0number=5&m804b0pagenumber=4&m804b0returnid=7&page=9&showtemplate=true infinite-scroll.pkgd.min.js:12:6621
> [InfiniteScroll] append. 0 items. URL: /index.php?mact=CGBlog,m804b0,default,1&m804b0summarytemplate=blogSummary_LeftRight&m804b0number=5&m804b0pagenumber=4&m804b0returnid=7&page=9&showtemplate=true

​Does this make any sense to you?

Thanks for your help. Highly appreciated.

**Comment by desandro** [comment]
Looks like Infinite Scroll loads this URL:

```
/index.php?mact=CGBlog,m804b0,default,1&m804b0summarytemplate=blogSummary_LeftRight&m804b0number=5&m804b0pagenumber=4&m804b0returnid=7&page=7&showtemplate=true
```

But this page does not have items to load. You'll have to investigate what that page response looks like.
