### ISSUE TITLE
Trigger last page hit if loaded page appends 0 items

### ISSUE THREAD

**Issue by desandro** [metafizzy/infinite-scroll#840]
A couple issues like #761 and #839 have popped up where a page loads but returns 0 items. At this point Infinite Scroll will then try to load the next page, which could trigger a loop of endlessly loading pages. One solution is to add a conditional where, if `append` is enabled, and the loaded page includes 0 items, then that be considered the last page hit.

**Add a 👍  reaction** to this issue if you would like to see this feature added. Do not add +1 comments — [They will be deleted](http://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by marsccyu** [comment]
I got this problem...**returns 0 items and trigger a loop of endlessly loading pages**
how can I interrupt loendlessly loading in this version?

**Comment by zieru** [comment]
+1 using json keep loaded after last record, and pageindex is incrementing.

**Comment by iSk2y** [comment]
I also met this problem, but I found that the page I wanted to load contained `page-link` class , like this
```html
<ul class="pagination justify-content-center flex-wrap">
<li class="page-item active"><a href="?index-1.htm" class="page-link">1</a></li>
<li class="page-item"><a href="?index-2.htm" class="page-link">2</a></li>
<li class="page-item"><a href="?index-2.htm" class="page-link">▶</a></li>
</ul>
```
Even on the last page it doesn't have much more content , the page also had this `page-link` class . like this
```html
<ul class="pagination justify-content-center flex-wrap">
<li class="page-item"><a href="?index-1.htm" class="page-link">◀</a></li>
<li class="page-item"><a href="?index-1.htm" class="page-link">1</a></li>
<li class="page-item active"><a href="?index-2.htm" class="page-link">2</a></li>
</ul>
```

So I guess maybe use two classes selectors `.page-item active` could represent the last page . 
```javascript
$('.threadlist').infiniteScroll({
        path: '?index-{{#}}.html',
        append: '.thread',
        status: '.scroller-status',
        hideNav: '.pagination',
        debug: true,
        checkLastPage: ".page-item active",
        // responseType: 'document'
    });
```
Yes it workd!

**Comment by egallup02360** [comment]
This is still an issue with loading data via json. Loading data via json is really not documented very well. I hacked together a solution that stops the loading, but it doesn't trigger the .infinite-scroll-last message.

Also, is there a place that a commercial license holder can get support with this product?

**Comment by idmahbub** [comment]
> This is still an issue with loading data via json. Loading data via json is really not documented very well. I hacked together a solution that stops the loading, but it doesn't trigger the .infinite-scroll-last message.
> 
> Also, is there a place that a commercial license holder can get support with this product?

tray like this :
`
				var container = $('.search-result').infiniteScroll({
					path: '.pagination__next',
					responseType: 'text',
					history: false,
					debug: false,
				});			
				$container.on( 'load.infiniteScroll', function( event, response ) {
					var data = JSON.parse( response );
					parseItem(data);
					return data.result.next_page_url ? console.log('Load') : container.infiniteScroll('destroy');
				});`

**Comment by desandro** [comment]
[Infinite Scroll v4](https://infinite-scroll.com) has been released. Infinite Scroll includes revised behavior that the last page will be triggered if `append` is set, and there are no items to append. I'm closing this issue as resolved. Please open a separate issue if you encounter a problem with this new behavior.
