### ISSUE TITLE
Infinite-Scroll not working with MooTools

### ISSUE THREAD

**Issue by Ruud68** [metafizzy/infinite-scroll#842]
Hi,
Thanks for this wonderfull script: really like it!
Im am implementing it on a Joomla (CMS) website. I have it working on the default template.
But... when I switch to a template that has mootools enabled, things go wrong.
I have debugged it to one line in infinite-scoll:
https://github.com/metafizzy/infinite-scroll/blob/9f9ccf3cee66ca2fe5df8c706662cba3bdab7a5f/js/page-load.js#L83

What happens here is that the jQuery .load gets executed with the response. The scripts set in the response (including mootools) get executed resulting in an error. This error leads to the whole document being injected in the container instead of only the items. Layout goes all over the place.

When commenting out line 83 it works. but I do not know what this line actually does and although it seems working, also not sure what doesn't work...

Any thoughts on this?

**Comment by desandro** [comment]
Thanks for reporting this issue. Sounds like the problem area is with [`refreshScripts`](https://github.com/metafizzy/infinite-scroll/blob/9f9ccf3cee66ca2fe5df8c706662cba3bdab7a5f/js/page-load.js#L112-L144). This behavior is typically useful for other users. But if you want to disable it, you could do so with a [duck-puch](https://metafizzy.co/blog/duck-punching-prototype/) by adding this code before you initialize Infinite Scroll

``` js
InfiniteScroll.prototype.appendItems = function( items, fragment ) {
  if ( !items || !items.length ) {
    return;
  }
  // get fragment if not provided
  fragment = fragment || getItemsFragment( items );
  //refreshScripts( fragment );
  this.element.appendChild( fragment );
};

function getItemsFragment( items ) {
  // add items to fragment
  var fragment = document.createDocumentFragment();
  for ( var i=0; items && i < items.length; i++ ) {
    fragment.appendChild( items[i] );
  }
  return fragment;
}
```

**Comment by Ruud68** [comment]
Hi Desandro, Thanks for the follow-up. Really appreciate it :)

I have tried the code, but this doesn't work. The reason is that the issue occurs _before_ appendItems. It happens when executing:
```this.dispatchEvent( 'load', null, [ response, path ] );```

But as far as I can see this is a jQuery function invoked from the infinite-scroll script.

The issue is gone when I remove Mootools from the page (but then I have other issues), or when I comment out the load line.

I have created the following [duck-punch](https://metafizzy.co/blog/duck-punching-prototype/) that does work:
```
		InfiniteScroll.prototype.onPageLoad = function( response, path ) {
			// done loading if not appending
			if ( !this.options.append ) {
				this.isLoading = false;
			}
			this.pageIndex++;
			this.loadCount++;
			//this.dispatchEvent( 'load', null, [ response, path ] );
			this.appendNextPage( response, path );
			return response;
		};

```
Can you give me some insights into what this load function is for and what will 'break' when I comment it out?

**Comment by desandro** [comment]
`onPageLoad` gets triggered when a page is loaded. It subsequently triggers `dispatchEvent` with the `load` event. That `load` event then triggers a number of other methods, most importantly `appendItems` where the scripts are actually reloaded.

**Comment by Ruud68** [comment]
> That `load` event then triggers a number of other methods, most importantly `appendItems` where the scripts are actually reloaded.

That is strange, because when I comment out the 'load' event, the appendItems do get triggered and the items appended. isn't appendItems triggered from appendNextPage?

**Comment by desandro** [comment]
If you can produce a **reduced test case** I can actually debug this.  Could you provide a **live URL**, or even better a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).

**Comment by Ruud68** [comment]
Hi, reduced test-case is not possible as this is on a CMS (Joomla!).
What I have for you is two links: one not working, one working...

This is the link to my test-site where I have no duck-punching, so the infinite-scroll script get's executed as is: https://office.onlinecommunityhub.nl/ll_test/blog-overzicht
What you will notices is that the new rows will get appended correct but when you scroll further the layout (and top menu) goes all over the place.

This is my live-site where I have punched the duck on both onPageLoad and on appendItems.
this works correct as you can see: https://www.lerendeleiders.nl/blog-overzicht

Hope this helps, if I can assist / do things please let me know :)

**Comment by desandro** [comment]
I'm not sure I'm seeing the issue

![screen shot 2018-11-21 at 9 39 55 am](https://user-images.githubusercontent.com/85566/48848232-68caab00-ed71-11e8-8218-038164d7f3ca.png)

**Comment by Ruud68** [comment]
Hi, sorry about that I restored my test site today and forgot to reverse the duckpunches :)

Here you go: https://office.onlinecommunityhub.nl/ll_test/blog-overzicht

Keep scrolling down (this is a slow site, so the loading of the next pages might take some time).

here is a video showing the behavior: https://office.onlinecommunityhub.nl/nextcloud/s/W7TGaQMsZdJxXbY

**Comment by desandro** [comment]
I'm seeing a JSON error. Can you please investigate?

```
SyntaxError: unexpected token: ':'[Learn More] blog-overzicht:1:13
f.exec
https://office.onlinecommunityhub.nl/ll_test/media/system/js/mootools-core.js:28:436
success
https://office.onlinecommunityhub.nl/ll_test/media/system/js/mootools-core.js:168:177
d/e<
https://office.onlinecommunityhub.nl/ll_test/media/system/js/mootools-core.js:38:493
onStateChange
https://office.onlinecommunityhub.nl/ll_test/media/system/js/mootools-core.js:159:425
d/e<
https://office.onlinecommunityhub.nl/ll_test/media/system/js/mootools-core.js:38:493
<anonymous> self-hosted:974:17
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://office.onlinecommunityhub.nl/ll_test/templates/gk_technews/js/progressbar.js
Source Map URL: progressbar.min.js.map[Learn More]
```

![Uploading Screen Shot 2018-11-26 at 10.35.17 AM.png…]()

**Comment by Ruud68** [comment]
fixed :) disabled the additional .js scripts that are part of the template.
Error is gone, behavior is still the same

**Comment by desandro** [comment]
Thanks for that. I'm still unsure where the problem is occuring. Here is the output if I enable `debug`

```
[InfiniteScroll] scrollThreshold
[InfiniteScroll] request. URL: /ll_test/blog-overzicht?start=9
[InfiniteScroll] scrollThreshold
[InfiniteScroll] load. Alle Leiderschapsblogs in één overzicht | Leiderschap. URL: /ll_test/blog-overzicht?start=9
[InfiniteScroll] append. 3 items. URL: /ll_test/blog-overzicht?start=9
```

So the page is properly requested, loaded, and its items are appended. After a brief pause, then the error is triggered.

```
SyntaxError: unexpected token: ':'[Learn More] blog-overzicht:1:13
f.exec
https://office.onlinecommunityhub.nl/ll_test/media/system/js/mootools-core.js:28:436
success
https://office.onlinecommunityhub.nl/ll_test/media/system/js/mootools-core.js:168:177
d/e<
https://office.onlinecommunityhub.nl/ll_test/media/system/js/mootools-core.js:38:493
onStateChange
https://office.onlinecommunityhub.nl/ll_test/media/system/js/mootools-core.js:159:425
d/e<
https://office.onlinecommunityhub.nl/ll_test/media/system/js/mootools-core.js:38:493
<anonymous> self-hosted:974:17 
```

I believe there's some other script or HTML in `/ll_test/blog-overzicht?start=9`. When this script loads the error is then triggered.

**Comment by Ruud68** [comment]
Agree, but the error doesn't occur when I 'skip' this.dispatchEvent( 'load', null, [ response, path ] );

When commenting out that line, everything works as far as I can see. So for me the question arises: why is this line there in the first place? What does it do?
and more importantly:
What will break if I comment it out via this duckpunch: https://github.com/metafizzy/infinite-scroll/issues/842#issuecomment-438964907

**Comment by desandro** [comment]
I am closing this issue as its been inactive for over year.
