### ISSUE TITLE
How get body in error event?

### ISSUE THREAD

**Issue by ahdung** [metafizzy/infinite-scroll#845]
```
infScroll.on('error', function (error) {
    // how get response body ??
});
```

**Comment by desandro** [comment]
If the request response does not return 200 OK, the `statusText` of the request is provided in the text of the `error`.

**Comment by ahdung** [comment]
statusText not enough, I need show the customized message from server, please understand.
#846

**Comment by desandro** [comment]
[Infinite Scroll v4](https://infinite-scroll.com) has been released. Infinite Scroll v4 now includes a `response` argument, the [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) to the fetch request on [`load`](https://infinite-scroll.com/events.html#load), `append` and `error` events.
