### ISSUE TITLE
How to handle multiple navigation elements on page?

### ISSUE THREAD

**Issue by Ruud68** [metafizzy/infinite-scroll#849]
Hi,
currently working on integrating infinite-scroll into a page that has multiple navigation elements.
to be exact: 4.
2 on top of the page, 2 in the bottom. 1 of the 2 is on the page for mobile devices, these are hidden on a desktop and vv.

Currently infinite scroll is limited to handling (hiding / showing) only one navigation element: the first it finds.
In my case this will leave the bottom navigation visible.

So I am looking if there is a way out-of-the-box (that I missed in the documentation) to have infinite-scroll handle all navigation elements.

What would be the best way to do this? Would that require a change (feature) in infinite-scroll?

Thanks in advance for thinking along :)

**Comment by desandro** [comment]
The easiest way to address this issue is to hide the navigation elements with your own JS, and not rely on Infinite Scroll's `hideNav` option

``` js
$('.container').infiniteScroll({
  // do not enable hideNav
});

// hide all .page-nav elements
$('.page-nav').hide();
```

**Comment by Ruud68** [comment]
Top,
I implemented it as a onInit function. this way the navs are only removed when infinite-scroll initializes.

just posting here for reference (when somebody is looking for a similar solution)
```
onInit: hideNavs()
```
and the function:
```
function hideNavs() {
	// remove all navigation lement on page
	var nav = document.querySelectorAll(ochInfiniteScroll.hideNav),
	i = 0,
	l = nav.length;

	for (i; i < l; i++) {
		nav[i].style.display = 'none';
	}
}
```
