### ISSUE TITLE
Safari images infinite scroll not loading

### ISSUE THREAD

**Issue by giorgiodi** [metafizzy/infinite-scroll#851]
In my site http://provasitoweb12345.altervista.org/blog/ does not load the images with infinite scroll on ipad. some advice?

this is my js code with the fix but it does not work anyway

(function ($) {
	if ( $(' .pagination .next ').length ) {	
		
		$('.infinite').infiniteScroll({
			// options
			path: '.pagination .next',
			append: '.item',
			history: true
		});
		// Hack to fix images not loading on ios
		$('.infinite').on( 'append.infiniteScroll', function( event, response, path, items ) {
			$( items ).find('img').each( function( i, img ) {
				img.outerHTML = img.outerHTML;
			});
		});
	}
	$('.pagination').hide();	
	
}(jQuery));

**Comment by danielbachhuber** [comment]
@giorgiodi Did you ever figure out what the actual issue was?

**Comment by danielbachhuber** [comment]
Oh, I guess it's the same as #770
