### ISSUE TITLE
Infinite Scroll + lightGallery

### ISSUE THREAD

**Issue by mrWilson123** [metafizzy/infinite-scroll#853]
Hi,

Is there any demo code with Infinite Scroll + lightGallery working together?

http://sachinchoolur.github.io/lightGallery/

**Comment by desandro** [comment]
From reading the docs, I think you need to initialize `.lightGallery()` on the newly appended content. You can do this with the [`append` event](https://infinite-scroll.com/events.html#append)

``` js
$container.on( 'append.infiniteScroll', function( event, response, path, items ) {
  $( items ).find('.gallery').lightGallery({...});
});
```

**Comment by PapyIP** [comment]
Hello,
facing the same problem with an automatic scroll (no button to load more items), I solved it like this
```
var $lg = $('.your_LightGallery_container');
var $is = $('.your_InfiniteScroll_container');
		
$is.on('append.infiniteScroll', function( event, response, path, items ) {
	$lg.data('lightGallery').destroy(true);
	$lg.lightGallery({selector: '.your_LightGallery_selector'});
});
```
compared to indication of Sachin in this method [http://sachinchoolur.github.io/lightGallery/demos/methods.html](url), I had to redefine the lg selector.

**Comment by PapyIP** [comment]
I'll follow this with great interest.
