### ISSUE TITLE
infiniteScroll won't stop after reaching last page

### ISSUE THREAD

**Issue by rajkumarr7777** [metafizzy/infinite-scroll#855]
path: 'api/users?page={{#}}',
checkLastPage: '.pagination__last',
responseType: 'text',
append: false,
loadOnScroll: false,
button: '.js-show-more-button',
status: '.page-load-status',

\<a class=".pagination__last" href="api/users?page=4">last</a>

After reaching last page, last event does not occur.
it requests a non-existent page "api/users?page=5", and then error event occurs.

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm tracking this issue in #840
