### ISSUE TITLE
Add custom regex for href matching

### ISSUE THREAD

**Issue by fx2300** [metafizzy/infinite-scroll#858]
Hi

When using a custom next url (i.e. not Drupal or WP specific) infinite scrolling is broken when one of the argument is numeric and/or the page number is not at the end of the query string…

Solution to make it more flexible could be to allow the use of a custom regex in core.js (268) :

```
// try matching href to pathRegexes patterns
var pathParts, regex;
// allow custom regex
if (this.options.hrefRegex) {
    pathRegexes.unshift(this.options.hrefRegex);
}
for ( var i=0; href && i < pathRegexes.length; i++ ) {
    regex = pathRegexes[i];
    var match = href.match( regex );
    if ( match ) {
        pathParts = match.slice(1); // remove first part
        break;
    }
}
```
So we can add a custom regex :

```
$('my_selector').infiniteScroll({
    // options
    path: 'my_next_link_selector',
    // make sure the page number will be captured as second subpattern
    hrefRegex: /my_next_link_regexp/ 
});
```

This would allow infinite scrolling to work with next urls like : 
"/mypage/?my_page_nbr=2&my_other_arg=2010"
or
"/directory?title=&field_organization_type_tid[0]=20&page=1"
(See [regex breaks under certain conditions in drupal](https://github.com/metafizzy/infinite-scroll/issues/500))"

Regards

**Comment by desandro** [comment]
Thanks for reporting this issue.

One solution is to set [`path` to a string](https://infinite-scroll.com/options.html#path) with a `{{#}}` as the wildcard:

``` js
path: "/mypage/?my_page_nbr={{#}}&my_other_arg=2010"
```

Or you can add more complex logo by setting path to a function

``` js
path: function() {
  return `/mypage/?my_page_nbr=${this.pageIndex}&my_other_arg=2010`;
```
