### ISSUE TITLE
InfiniteScroll inside MagnificPopup

### ISSUE THREAD

**Issue by MrMooky** [metafizzy/infinite-scroll#862]
I'm not having an online test case, but would like to ask for help, still.

I'm using Infinite Scroll **inside** a Magnific Popup. This is my current code:

```
    $('.conversation__view').infiniteScroll({
        path: '.nextPage',
        append: '.message__single',
        history: false,
        hideNav: '.conversation__view ul.pagination'
    });
```

The navigation is hidden but the next posts are not being loaded. I tried changing the `scrollThreshold` value and even tried with a button and `loadOnScroll: false` but nothing happens.

I have the same script working on another part of the page, just not inside a Magnific Popup.

The Popup is initialised like that:

```
    $.magnificPopup.open({
        items: {
            src: '/messages/list',
        },
        type: 'ajax',
        ajax: {
            settings: null,
            cursor: 'mfp-ajax-cur'
        }
    });
```

Inside this list are links, that are opening a conversation details view, opened like this:

```
    $('body').on('click', '#messages__overlay a.single', function(ev){
        $('#messages__overlay .messages__content').html('Loading...').load($(this).attr('href');
    });
```

The `.load` has a callback (not shown here) where I initialise infiniteScroll, as seen in the first code example.

Any other ideas I haven't thought of?

**Comment by desandro** [comment]
If the scrollable element is not `window`, you can set it with [`elementScroll`](https://infinite-scroll.com/options.html#elementscroll)

**Comment by MrMooky** [comment]
@desandro I was quite excited to try it, but it's not working either. :/

This is my code:

```
$('body').on('click', '#messages__overlay a.single', function(ev){
        ev.preventDefault();
        $('#messages__overlay .messages__content').html('Loading...').load($(this).attr('href'), function(){
            if ( $('.conversation__view').length >= 1 ){
                $('.conversation__view').infiniteScroll({
                    path: '.nextPage',
                    append: '.message__single',
                    elementScroll: true,
                    hideNav: '.conversation__view ul.pagination'
                });
            }
        });
    });
```

And this is the output of the newest 10 messages (of 24):

<img width="422" alt="screenshot 2019-01-23 at 18 42 28" src="https://user-images.githubusercontent.com/3603346/51626027-e57b3080-1f3e-11e9-9ec0-2d3a4652be9f.png">

Your script is being initialised correctly as it hides the pagination. But neither `true`, nor `"conversation__view"` with `elementScroll` have any impact. The next page is not being loaded.

When I disable `hideNav` I see my button, but when I click it, I'm just being corrected to the next view in the main window. Now, the outer frame `mfp-wrap` etc don't exist on page load. That's probably why it doesn't work?

**Comment by MrMooky** [comment]
Ah, damnit! I got it. My bad. :/ I'm scrolling the `div.innerScroll` container, not the `div.conversation__view` container. Not it works. Thanks for your help.
