### ISSUE TITLE
url changed

### ISSUE THREAD

**Issue by crazystear** [metafizzy/infinite-scroll#863]
hi! thanks for your code. 
when I scroll the screen, The URL address will changed to xxx.com/page/2, page/3, page/4...
how to keep URL address not change?  always display like this: xxx.com

thank you! and SORRY for my bad English...>_<

**Comment by desandro** [comment]
[Set `history: false`](https://infinite-scroll.com/options.html#history)

**Comment by crazystear** [comment]
It's working! Thanks a lot :)
