### ISSUE TITLE
Infinite scroll is not showing the last page of paginator.

### ISSUE THREAD

**Issue by analiseburtet** [metafizzy/infinite-scroll#865]
The problem is: the last page of my paginator, the 'next button' is not being 'read' by infinit scroll.
You can click the button to load more and more, but never the last page of products.

**Comment by desandro** [comment]
Sounds related to #840. Is the last page not returning a 404, and rather a valid empty page? If so, then its the 840 bug.

**Comment by analiseburtet** [comment]
No it was a developer problem, in this case I was the problem hehehe thank
you :) The selector was wrong

Em seg, 18 de fev de 2019 às 21:49, David DeSandro <notifications@github.com>
escreveu:
