### ISSUE TITLE
Infinite Scroll + imagesLoaded ?

### ISSUE THREAD

**Issue by julesvaulont** [metafizzy/infinite-scroll#866]
Is possible to load the next page after all images of this page has been loaded?
Any idea? Thank you!

**Comment by desandro** [comment]
Something like ...?

``` js
$container.imagesLoaded( function() {
  $container.infiniteScroll('loadNextPage');
});
```

See [loadNextPage](https://infinite-scroll.com/api.html#loadnextpage)
