### ISSUE TITLE
resetting and reinitialising infiniteScroll?

### ISSUE THREAD

**Issue by thelar** [metafizzy/infinite-scroll#867]
Hi,
Here is the page where I'm using infiniteScroll - https://kitchens.chapterserver1.co.uk/kitchen-style/shaker-kitchens/ 

The filters at the top trigger a hashchange event which triggers jquery to re-load the blocks on the page. Eventually this will have a lot more filters but this is just for testing right now.

I need to reset and reinitialise infiniteScroll when I use the filters (or when there is a hash change caused by the use of the back button etc) and I can't work out how to do this. Here are the relevant bits of code:

This function called on page load and hashchange:
```
function render_kitchens() {
    let $container = $('.kitchen-tiles');

    emptyContainer();

    let data = {
        action: 'kitchens_load',
        paged: $('.kitchen-tiles').data('paged'),
        posts_per_page: $('.kitchen-tiles').data('pp-page'),
    }

    let hash = getHashParams();

    if($.isEmptyObject(hash)){
        let $kitchen_tiles = $('.kitchen-tiles');
        let style = $kitchen_tiles.data('type');

        if(style!==''){
            data.style = style;
        }
    }else{
        data.style = hash.style;
    }


    $.ajax({
        // eslint-disable-next-line no-undef
        url: ajax_object.ajax_url,
        type: 'POST',
        data: data,
        dataType: 'json',
        // eslint-disable-next-line no-unused-vars
        success: function(response){
            let itemTemplateSrc = $('#kitchen-item-template').html();
            $.each(response.kitchens, function(i, val){
                let itemHTML = getItemHTML(itemTemplateSrc, val);
                $container.append(itemHTML);
            });
            setupInfScr();
        },
    });
}
```

Function to set up infinite scroll called in `success` function of above:

```
function setupInfScr(){

    let $elem = $('.kitchen-tiles');
    let jQueryBridget = require('jquery-bridget');
    jQueryBridget( 'infiniteScroll', InfiniteScroll, $ );

    let $container = $elem.infiniteScroll({
        path: function () {
            return '/wp-admin/admin-ajax.php?action=kitchens_load&posts_per_page=3&paged=' + (this.pageIndex + 1) + '&style=' + $elem.data('type');
        },
        responseType: 'json',
        history: false,
    });

    $container.on('load.infiniteScroll', function(event, response){
        // parse response into JSON data
        let itemTemplateSrc = $('#kitchen-item-template').html();
        $.each(response.kitchens, function(i, val){
            let itemHTML = getItemHTML(itemTemplateSrc, val);
            $container.append(itemHTML);
        });
    });
}
```

I've tried a few things inside the seuptInfScr function, like destroy and setting the data to null, but nothing really works. What should my approach be here???

Sorry, it's not really an 'issue' persee but could really do with some guidance.

Many thanks
Kevin

**Comment by desandro** [comment]
Hello! I'll try my best to provide some insight here.

Conceptually, when a new filter is selected, these things need to happen

+ Remove current content — perhaps with jQuery `.empty()`
+ Disable current Infinite Scroll instance. With the [destroy method](https://infinite-scroll.com/api.html#destroy)
+ Add new content, which you got
+ Enable new Infinite Scroll instance, which you got

**Comment by thelar** [comment]
@desandro Hi, thanks for the reply!!!

I've actually moved on a bit and am using masonry as well as infinite-scroll for my site.

I've forked one of your pens to try and demonstrate what I need to achieve - https://codepen.io/the_lar/pen/BbNdjZ

As you can see, when I hit the 'Remove and Reload' button, the remove happens but the next infinite scroll page loads where the previous items were removed. Obviously I need to reload the items at the top of the container... how do I achieve this??

Many many thanks if you can help, I've spent ages on trying to do this!!!

Kevin

**Comment by thelar** [comment]
Also, you can see the page I'm actually working on here - http://kitchens.chapterserver1.co.uk/kitchen-style/traditional-kitchens/ 

Please help! I feel I'm almost there but just can't see how to achieve this!!!

**Comment by thelar** [comment]
I think I've solved it!!! Seems like all it needed was .masonry() calling on the grid in the end - my hashchange function now contains:

```
let hash = getHashParams();
    // eslint-disable-next-line no-unused-vars
    let style = '';
    let $grid = $('.grid');



    if($.isEmptyObject(hash)){
        style = $grid.data('type');
    }else{
        style = hash.style;
    }

    $grid.attr('data-type', style);
    $grid.attr('data-paged', 1);

    let element = $('.grid-item');
    $grid.masonry('remove', element);
    $grid.infiniteScroll('loadNextPage');
    $grid.masonry();
```

I've updated the page here - https://kitchens.chapterserver1.co.uk/kitchen-style/shaker-kitchens/

Do you forsee any issues with this approach?
Kevin

**Comment by desandro** [comment]
Thanks for following up! Very nice use of Masonry's `remove` method. Your code looks okay from here. That you've found a solution means you've got a good understanding of how both plugins work.

**Comment by howdu** [comment]
@desandro it would be great if there was a way to reset the pageIndex/total from a event. It would re-check the pagination if this has changed from filtering. Only way currently is completely destroy and reinitialize the plugin. 
https://github.com/metafizzy/infinite-scroll/issues/933
