### ISSUE TITLE
Cannot load afterglowplayer

### ISSUE THREAD

**Issue by wizedesign** [metafizzy/infinite-scroll#868]
Hi, cannot load [afterglowplayer](http://afterglowplayer.com/) inside the loaded div, the first page will load correctly but after that, it does not load.

I understand I have to use this code, but I can not figure out what to add.
```
$container.on( 'append.infiniteScroll', function( event, response, path, items ) {
     // ???
});
```

[View screenshot - NSFW](https://user-images.githubusercontent.com/40828215/53303025-3c419600-386e-11e9-9cc0-6ca5a9e7fae4.jpg)

Thanks!

**Comment by desandro** [comment]
You'll have to look into the [afterglowvideo JavaScript API](http://docs.afterglowplayer.com/docs/api). I'm not exactly sure the right method, but it would look something like this:

``` js
$container.on( 'append.infiniteScroll', function( event, response, path, items ) {
     $( items ).find('video').each( function( i, video ) {
         afterglowvideo.initPlayer( video );
    });
});
```

Unfortunately, I do not believe afterglow Player provides an API hook like this. You'll have to open a new issue on their tracker: https://github.com/moay/afterglow/issues. cc @moay
