### ISSUE TITLE
Load multiple page at a time : infinite-scroll

### ISSUE THREAD

**Issue by insaurabh** [metafizzy/infinite-scroll#869]
How can i load multiple page at a time say 5 pages and then on click of **< button >** load next 5 pages.

Currently i am able to load the 5th page but not all the pages till the 5th one.

with this example

my settings are
```
let viewMoreButton = document.querySelector('.view-more-button');
let ifs = new InfiniteScroll(infiniteScroll.attr('data-ifs-container'), {
	path: function () {
		return 'page/' + ( ( this.loadCount + 2 )) + window.location.search;
	},
	append: '.somediv',
	history: 'replace',
	historyTitle: true,
	log: false,
	//scrollThreshold: false,
	button: viewMoreButton,
	status: '.page-load-status',
	onInit: function () {
	// some other settings
	}
});

ifs.on( 'load', onPageLoad );

function onPageLoad() {
  if ( ifs.loadCount == 5 ) {
    console.log('ifs.loadCount' + ifs.loadCount);
    ifs.options.loadOnScroll = false;
    viewMoreButton.style.display = 'inline-block';
    ifs.off( onPageLoad );
  }
}
```

but no new page is appended.
Thank You.

**Comment by desandro** [comment]
Infinite Scroll is not designed to handle loading multiple pages at the same time. The best you could do is trigger [loadNextPage](https://infinite-scroll.com/api.html#loadnextpage) on [append](https://infinite-scroll.com/events.html#append) five times in a row.
