### ISSUE TITLE
last page load more button

### ISSUE THREAD

**Issue by Macro-Jackson** [metafizzy/infinite-scroll#872]
If there is only one page available then there is no next page button being outputted by my system. It seems Infinite Scroll is giving an error on this:
Bad InfiniteScroll path option. Next link not found: .next

.next is the class of the link 

InfiniteScroll is right here. There is no next link. It's the last page, so no link to the next and also no faulty anchor without a href.  How do I prevent InfiniteScroll giving an error and trying to load a next page? I don't want to fake a next page link.

**Comment by Macro-Jackson** [comment]
Solved for now with a fake link and a rel="nofollow". 

Hoping for an answer.

**Comment by desandro** [comment]
See https://github.com/metafizzy/infinite-scroll/issues/691#issuecomment-357312879
