### ISSUE TITLE
Update pagination history during scrolling

### ISSUE THREAD

**Issue by ghost** [metafizzy/infinite-scroll#873]
Do you plan to implement anything like this maybe using ajax? You already supported history updated in the address bar when scrolling so I was wondering if it was possible to update the pagination element entirely when scrolling. I tried using `.load()` into the path function but it somehow breaks the function entirely if used alongside vanilla javascript

Example: when scrolling to page-2 position `&page=2` is appended in the url bar and the pagination element is replaced with the pagination element from page-2 url

**Comment by desandro** [comment]
You could implement this behavior using the [`history` event](https://infinite-scroll.com/events.html#history). You'll have to read the `path` argument and update the page nav accordingly.
