### ISSUE TITLE
[Question] Copyright clarification

### ISSUE THREAD

**Issue by iustin** [metafizzy/infinite-scroll#877]
Hi,

This is similar to #828, but slightly different. While the licence terms are clear, I don't see anywhere a "Copyright <author>". The masonry and imagesloaded projects have a clear statement (e.g. <https://desandro.mit-license.org/>, which includes "Copyright © 2019 David DeSandro". Can you please update the licence docs to mention this as well?

Context: I'm shipping the library with my webapp (AGPLv3), and I prefer to have clear copyright terms for all files. Thanks!

**Comment by desandro** [comment]
[index.js has a Copyright line](https://github.com/metafizzy/infinite-scroll/blob/v3.0.5/js/index.js#L9) as does [infinite-scroll.pkgd.js](https://github.com/metafizzy/infinite-scroll/blob/v3.0.5/dist/infinite-scroll.pkgd.js#L9)

**Comment by iustin** [comment]
Ah, sorry, i didn't see that. Would you mind though adding this as well to https://infinite-scroll.com/#license? That's where I'd expect to see it, but there's no mention at all. Either way, I'm good.
