### ISSUE TITLE
Custom start page number

### ISSUE THREAD

**Issue by iustin** [metafizzy/infinite-scroll#878]
I have a similar problem to #478 which referred to version 2.0. It seems that infinite-scroll still assumes a starting page index of 1 (if it can't determine the page, or if path is a function, per the documentation), which doesn't work well with either zero-based numbering or with just jumping into another page index.

I already know the correct page index, so my first attempt was to reset it after initialization is done, but this doesn't work well with prefill. So the right workaround is to provide an `onInit` that sets up the starting page number. I guess this is common enough that it would be good to support it officialy:

- cheap option: mention this in docs as recommended way to init the page number
- a more prope fix: add an option to set the initial page number

Thoughts?

**Comment by desandro** [comment]
Infinite Scroll v3 does account for starting-pages other than # 1. For example, you can start on [https://infinite-scroll.com/demo/full-page/page3.html](https://infinite-scroll.com/demo/full-page/page3.html) and it will load `page4.html`. In this case, it's calculating the starting page index from `path` element `href`.

In addition, if you do know the correct page index, you can set `path` to a function and use [`loadCount`](https://infinite-scroll.com/api.html#loadcount) with it

``` js
var startIndex = 3;
// ...
path: function() {
  var pageNumber = ( this.loadCount + startIndex ) * 10;
  return '/articles/P' + pageNumber;
}
```

**Comment by iustin** [comment]
Thanks for the reply.

> Infinite Scroll v3 does account for starting-pages other than # 1. For example, you can start on https://infinite-scroll.com/demo/full-page/page3.html and it will load `page4.html`. In this case, it's calculating the starting page index from `path` element `href`.

In my case, this doesn't work well. It looks that a more complex URL - with a query string as well confuses the parser and it always in my case says "page is 1".

I'll try to come up with a minimal test case, but in the meantime, the path I had was having problems with was of the form: `http://localhost:3000/search/images/0?person=foo`. And this resulted in page set to 1.

> In addition, if you do know the correct page index, you can set `path` to a function and use [`loadCount`](https://infinite-scroll.com/api.html#loadcount) with it
> 
> ```js
> var startIndex = 3;
> // ...
> path: function() {
>   var pageNumber = ( this.loadCount + startIndex ) * 10;
>   return '/articles/P' + pageNumber;
> }
> ```

Ah, I see. I was not thinking of using loadCount together with custom start index. I'll have to check - for me, once I do initialize the page number, everything works well afterwards with path being of the `{{#}}` form.

**Comment by Cryden** [comment]
I want start from the page https://infinite-scroll.com/demo/full-page/page3.html and then  load page2.html. How can this be done?

**Comment by desandro** [comment]
@Cryden You can set the return value in the `path` function to whatever you want. It doesn't have to be ascending number order. You could use `( startIndex - this.loadCount )`.
