### ISSUE TITLE
Uncaught DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'document').

### ISSUE THREAD

**Issue by lanhtv** [metafizzy/infinite-scroll#882]
Hi,
I'm using the version 3, but I don't seem to make it work on my side. The installation seems to be easy, and I did it right as the documentation displays, but I get this error :
`Uncaught DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'document').`

This is my code:
`

if (related_articles.length) {

    $('#block-system-main').infiniteScroll({

        append: ".node-article",

        debug: false,

        history: false,

        responseType: 'document',

        path: function() {

             return related_articles[this.loadCount];

        }

    });

}

`

**My page:** https://youth1.com/baseball/banditos-black-blitz-opponents-easton-april-300-point-slugfest

**Comment by desandro** [comment]
Looks like this bug is being triggered on code with in line 5 of your sites source

```
<script type="text/javascript">(window.NREUM||(NREUM={})).loader_config={xpid:"VQUDV1RaCBABXVFaBQEDVw=="};window.NREUM||(NREUM={})...
```

I do not believe its related to Infinite Scroll
