### ISSUE TITLE
Preloading in button mode

### ISSUE THREAD

**Issue by mohelten** [metafizzy/infinite-scroll#884]
Hi,
I am using the button solution, so loading on click because I want the user to have the possibility to reach the footer.
For loading time it would be great to preload the next page and after clicking the content is directly appended.

**Comment by desandro** [comment]
I am closing this issue as its been inactive for over year.

**Comment by 1aurabrown** [comment]
I would like this feature to.. Can this be accomplished somehow by calling 'loadNextPage()' ?
