### ISSUE TITLE
Blog posts repeats on homepage

### ISSUE THREAD

**Issue by marilynwo** [metafizzy/infinite-scroll#892]
Hi, the infinite scrolling is working on inner WordPress pages, but when I placed a blog roll on the homepage, the scrolling works, but the images repeat themselves. You may see this URL for reference: https://design2.meetanders.com/

The image after the "Happy Working" image should be different.

This error happens when I set this page you see as the homepage (https://ibb.co/xgqGV1k)

I'm using this with Oxygen Builder. 

**Test case:** http://codepen.io/desandro/pen/WOjqNM

**Comment by devajitgupta** [comment]
sorry
