### ISSUE TITLE
Is possible skip requested element?

### ISSUE THREAD

**Issue by bilalmalkoc** [metafizzy/infinite-scroll#894]
For example, if loaded or requested element has some class, dont append it, just skip and go next. Is it possible?

**Comment by desandro** [comment]
One solution is to add a specific class to items that should be displayed, and use this in [`append`](https://infinite-scroll.com/options.html#append)

``` js
append: '.post.addable'`
```

Another solution is to write you're own [load event handler](https://infinite-scroll.com/events.html#load) that selects and adds the desired content.
