### ISSUE TITLE
infinite-scroll-last and infinite-scroll-error visible on first page

### ISSUE THREAD

**Issue by Maveee** [metafizzy/infinite-scroll#902]
I prefer the button instead of the infinite autoscroll, and it works great!
However, everything in infinite-scroll-last and infinite-scroll-error classes is always displayed on the frist page. How do I fix this?

https://themavesite.com/WallSavior/

**Comment by desandro** [comment]
Looks like you opted not use Infinite Scroll. Is there something else I can take a look at?
