### ISSUE TITLE
Serverside json end of content

### ISSUE THREAD

**Issue by egallup02360** [metafizzy/infinite-scroll#912]
Loading data via json is really not documented very well.

I got json content loading in, but when there is no content left to load, infinite scroll continually tries to load more content.

Is there some sort of status or key I should be returning to let infinite scroll know the last page has loaded? I already tried returning a status of 204 and also tried just returning null from the backend, but infinite scroll continues to attempt to load more content. 

I also attempted to use checkLastPage, but there isn't an actual element on the page to check for, it's all json data.

Below is the js code I'm using for infinite scroll.
```
<script>
  var $container = $('.infinite-container').infiniteScroll({
    path: function() {
      return 'page_data.json&page=' + this.pageIndex;
    },
    responseType: 'text',
    status: '.page-load-status',
    scrollThreshold: 100,
    history: false,
  });

  $container.on( 'load.infiniteScroll', function( event, response ) {
      var data = JSON.parse( response );
      // compile data into HTML
      var itemsHTML = data.data.map( getItemHTML ).join('');
      // convert HTML string into elements
      var $items =  $( itemsHTML );
      // append item elements
      $container.infiniteScroll( 'appendItems', $items );
  });

  $container.infiniteScroll('loadNextPage');

  var itemTemplateSrc = $('#line-template').html();
</script>
```

Thanks for any help with this.

**Comment by desandro** [comment]
See my answer in https://github.com/metafizzy/infinite-scroll/issues/906#issuecomment-616681788
