### ISSUE TITLE
All docs codepen examples show "No more pages to load" 

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [metafizzy/infinite-scroll#916]
Example:
https://codepen.io/desandro/pen/xrdERX

https://codepen.io/desandro/pen/WmeqWg

![image](https://user-images.githubusercontent.com/16711871/82754667-33c06e00-9dd7-11ea-9d23-331294428681.png)

**Comment by desandro** [comment]
Thanks for reporting this issue! Looks like CodePen changed their debug URL domains from `s.codepen.io` to `cdpn.io`. I fixed this by using domain-relative `/` path instead.

``` js
// previous
function getPenPath() {
  var slug = nextPenSlugs[ this.loadCount ];
  if ( slug ) {
    return 'https://s.codepen.io/desandro/debug/' + slug;
  }
}

// fixed
function getPenPath() {
  var slug = nextPenSlugs[ this.loadCount ];
  if ( slug ) {
    return '/desandro/debug/' + slug;
  }
}
```
