### ISSUE TITLE
Next page from URL instead of pagination?

### ISSUE THREAD

**Issue by magix01** [metafizzy/infinite-scroll#921]
Is it possible to set path for selector that only contains one link and then load, i am trying to make infinite scroll in wordpress posts that will load next post but cant have pagination there, i tried something but its too hacky and wont update history url correctly.

Any help?

**Comment by sj5505** [comment]
> Is it possible to set path for selector that only contains one link and then load, i am trying to make infinite scroll in wordpress posts that will load next post but cant have pagination there, i tried something but its too hacky and wont update history url correctly.
> 
> Any help?

sj

**Comment by braddalton** [comment]
@desandro @sj5505 Did you get this fixed? I'm getting errors when trying to load next and previous posts. Works fine on archives but not on single posts.

**Comment by tassawarr** [comment]
i'm having the same issue. Actually it auto updates the url of next post with a change in post date or adding a different number at the end of url which leads it to 404. I don't know what's the matter with this.

**Comment by lmartins** [comment]
Did anyone found a workaround for this? Looking to implement the same use case as @magix01, where I want to load the next post from a normal WordPress post url.

I've tried to set `path` as function to then query the next post link element, but that doesn't work and will always load the second post in the sequence over and over again.

**Comment by desandro** [comment]
Sounds like you're asking for [Loading URLs from loaded pages](https://infinite-scroll.com/extras.html#loading-urls-from-loaded-pages). Previously asked for in #688. Report back if you're looking for different kind of behavior.
