### ISSUE TITLE
History breaking links when enabled

### ISSUE THREAD

**Issue by denoise** [metafizzy/infinite-scroll#924]
I'm using Infinite Scroll loading the data from a JSON and it's working fine if I don't enable the history.

A problem occurs when I enable the history: 'replace' option that changes the page URL for the subfolder and path of my server-side script breaking all links and images.

Here is my init code:

``` js
$infiniteContainer = $('#resultsContainer').infiniteScroll({
    path: function() {
        return 'ajax/ajax.items.php?'
        + '&s=' + searchStr
        + '&cat=' + filterCat
        + '&sub=' + filterSubCat
        + '&order=' + orderBy
        + '&offset=' + this.pageIndex;
    },
    responseType: 'text',
    history: 'replace',
    loadOnScroll: true,
    checkLastPage: true
});
```

when I enable the history then my URL gets converted to:

mydomain.com/ajax/ajax.items.php?s=&cat=&sub=&order=&offset=1

and the URL should stay as mydomain.com/

How can I prevent infinite scroll to change the URL to the wrong path and just passing the variables I need for scrolling to a specific page?

**Comment by agdgdh** [comment]
> I'm using Infinite Scroll loading the data from a JSON and it's working fine if I don't enable the history.
> 
> 
> 
> A problem occurs when I enable the history: 'replace' option that changes the page URL for the subfolder and path of my server-side script breaking all links and images.
> 
> 
> 
> Here is my init code:
> 
> 
> 
> $infiniteContainer = $('#resultsContainer').infiniteScroll({
> 
>     path: function() {
> 
>         return 'ajax/ajax.items.php?'
> 
>         + '&s=' + searchStr
> 
>         + '&cat=' + filterCat
> 
>         + '&sub=' + filterSubCat
> 
>         + '&order=' + orderBy
> 
>         + '&offset=' + this.pageIndex;
> 
>     },
> 
>     responseType: 'text',
> 
>     history: 'replace',
> 
>     loadOnScroll: true,
> 
>     checkLastPage: true
> 
> });
> 
> when I enable the history then my URL gets converted to:
> 
> 
> 
> mydomain.com/ajax/ajax.items.php?s=&cat=&sub=&order=&offset=1
> 
> 
> 
> and the URL should stay as mydomain.com/
> 
> 
> 
> How can I prevent infinite scroll to change the URL to the wrong path and just passing the variables I need for scrolling to a specific page?

**Comment by desandro** [comment]
> How can I prevent infinite scroll to change the URL to the wrong path and just passing the variables I need for scrolling to a specific page?

[Set `history: false`](https://infinite-scroll.com/options.html#history)

``` js


history: false
// disable changing URL and browser history

```
