### ISSUE TITLE
InfiniteScroll with post data

### ISSUE THREAD

**Issue by Neurozone** [metafizzy/infinite-scroll#925]
Hello.
I wish to use infiniteScroll with post parameter data.
But as I'm not very good in javascript I need some help
Here is my vanilla code:

    $.ajax({
      url: '/item/select',
      type: 'post',
      data: {flux: flux, page: $(window).data('page')},

      success: function (data) {
        $('.row').append(data).last();
      }

The code for infiniteScroll seem to be the following:

$('#articles').infiniteScroll({
  // options
  path: '/item/select',
  append: '.post'
});

But where can I send post parameter ?
Please help me :)

**Comment by desandro** [comment]
Sorry, Infinite Scroll only loads content with `get`.
