### ISSUE TITLE
Scrolling not working for parked domain

### ISSUE THREAD

**Issue by Lucky12k4** [metafizzy/infinite-scroll#927]
I have two domains in which one is parked and uses content from the primary one. The primary domain is https://thesocietyofbrokencollectionsonly.com and the parked one is https://thesobco.com. 

The issue is that infinite scrolling is not working on the parked domain. I have added a htaccess rule "Header always set Access-Control-Allow-Origin "https://thesobco.com" " to allow CORS but it's still not working. In Chrome, I get the error "Uncaught TypeError: $(...).infinitescroll is not a function".

Any help would be highly appreciated. 

Thanks and regards.

**Comment by desandro** [comment]
This may be an order-of-operations issue. I would recommend your scripts to be ordered:

1. jquery.min.js
2. jquery.infinitescroll.min.js
3. the body script with `$("#display-posts-main").infinitescroll(`

Heads up: looks like you're using Infinite Scroll v2 which is no longer supported.
