### ISSUE TITLE
this.options.outlayer.appended is not a function

### ISSUE THREAD

**Issue by arkid** [metafizzy/infinite-scroll#928]
I have infinite scroll setup on a site that I maintain and it does work but I get these errors in the JS console.   

I've absolutely no idea why it's doing this, can anyone assist to resolve this ?

You can see this here : https://www.permanentstyle.com/search?phrase=shirt - scroll down to start the page loading more thumbnails and it will appear.

**Comment by desandro** [comment]
Looks like you were able to resolve this issue.
