### ISSUE TITLE
Unable to use elementScroll selector with html node element

### ISSUE THREAD

**Issue by steponmepls** [metafizzy/infinite-scroll#929]
**Test case:** https://codepen.io/leewdch/pen/QWEENrW

I'm trying to implement infinite-scroll on an imageboard but the `scrollThreshold` event is triggered with minimal scrollbar movements no matter if it's going up or down. Since I couldn't figure out the issue (it happens only on this one website in specific for some reason) I tried using the `html` node element instead but the threshold isn't met neither on the website where I'm testing my userscript nor on the codepen I used to isolate the problem.

Any clue of what is going on?

![image](https://user-images.githubusercontent.com/63500907/96373247-837b4980-116b-11eb-8cc2-7eb1ef1dbcc4.png)

**Comment by desandro** [comment]
1. `html` element may not work as visible elements exist within `body`.
2. Sounds like the issue is how to resolve the 'minimal scrollbar movements'. If you have a live URL with that issue I can take a look.
