### ISSUE TITLE
Reloading the content based on filter

### ISSUE THREAD

**Issue by Adman** [metafizzy/infinite-scroll#933]
Hello!
Thanks for an awesome plugin.
I'm working on a small image gallery, where images are loaded by infinite-scroll plugin, and managed by Masonry in a grid. There is also a filter, so user can filter images based on some parameters. When user changes something in filter, I'd like to remove all the images from container and start loading them from page one (with GET parameters specified in path). I've tried calling `destroy` method along with removing all images from the container and subsequently reinitializing entire plugin, but it somehow doesn't work -- the images keep adding below some margin. I think it is due the fact that some special "top"-position counter is not reset.
Has someone experienced such a problem? Is there a correct way how to do this "plugin reload" for container?

**Comment by desandro** [comment]
Thank you for reporting this issue. I'm sorry to see you're having trouble with Infinite Scroll. Could you provide a **live URL**, or even better a **reduced test case**, or at least the code you're using? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).

**Comment by Adman** [comment]
Sorry it took me too long, but I managed to fix the problem by using this:

```javascript
masonry_object.destroy()
inf_scroll_object.destroy();
$('.image-container .grid-item').remove();
init_masonry();
init_infinite_scroll();
inf_scroll.loadNextPage();
```
