### ISSUE TITLE
Error: Can't resolve './core' after npm install

### ISSUE THREAD

**Issue by moneef** [metafizzy/infinite-scroll#952]
Hi, i used npm to install infinite-scroll, and required it in app.js, but when i run `npm run watch` i get the error below

```
ERROR in ./node_modules/infinite-scroll/dist/infinite-scroll.pkgd.js 800:8-25
Module not found: Error: Can't resolve './core' in '/node_modules/infinite-scroll/dist'
```

any help will be appreciated

**Comment by ShouibAamiri** [comment]
have it solved

**Comment by desandro** [comment]
You should import `infinite-scroll`. `dist/infinite-scroll.pkgd.js` is for browser usage.

**Comment by munts** [comment]
@desandro Can you explain this to me.  I too am getting the same error that moneef was getting.  I used npm to install infinite-scroll and masonry...  I then do an import statement in my script.js

import 'infinite-scroll/dist/infinite-scroll.pkgd.min'
import 'masonry-layout/dist/masonry.pkgd.min'

But when I do an npm run build, I get the "Module not found: Error: Can't resolve './core' in '/node_modules/infinite-scroll/dist'"

So, how do I get around this?  Do I need to load it differently?  Note, I am using this in a website which will run in the browser.

Thanks,
Scott
