### ISSUE TITLE
Rating of a topic and infinite scroll

### ISSUE THREAD

**Issue by madromas** [metafizzy/infinite-scroll#981]
After new batch of topics load up, my rating of a topics stops working. How do I initialize a function every time it loads more topics?

 ` icms.rating.onDocumentReady();`

Where do I place it, so it will run every time infinite scroll loads more topics?

**Comment by madromas** [comment]
Fancybox for gallery also stops working after new topics load. How to reinitialize that?

**Comment by ac-mmi** [comment]
for initializing a function every time it loads more topics you should add the functionality in the method defined for the path attribute of infinite scroll

**Comment by madromas** [comment]
> for initializing a function every time it loads more topics you should add the functionality in the method defined for the path attribute of infinite scroll

This didn't help at all....

**Comment by ac-mmi** [comment]
need code to understand better

**Comment by madromas** [comment]
`icms.rating.onDocumentReady();`

I have presented it above.

Here is what I did:

```
  history: false,
  scrollThreshold: 500,
});
$('.content_list').one('click', function(){
      icms.rating.onDocumentReady();
    }); 
```

Everything works. but, there is this extra click I have to do. Lets say I want to vote up, I have to click arrow twice for it to log the vote. And same with every post.

**Comment by ac-mmi** [comment]
you are using this infinite scroll in the conversations list page

**Comment by madromas** [comment]
No, on the post list page here glonks.com

**Comment by ac-mmi** [comment]
Reason for your vote-up not working is that your event a.vote-up.click won't work for dynamically generated elements
in order to rectify that you should use 
$(document).on('click', 'a.vote-up', function(){ 
//function defintion
});
It allows you to attach an event handler to a parent element that is always present (like document).

**Comment by madromas** [comment]
What about on vote-down?

You see here. I appreciate the help, but I fail to understand.

**Comment by madromas** [comment]
It works good. Only one tiny issue. Is there a way to make that one extra click to disappear?

Example: When new row of topics load up and you try to vote-up or vote-down, you have to click it twice the first time for it to register a vote. Like in order for vote system to work one extra click has to be made... Not a big deal, just wondering.

**Comment by ac-mmi** [comment]
Maybe remove the function from rating.js that might be causing the problem.

Also one question i saw your esoTalk-v3 there i tried to change the default.master.php file from core/views but the same weren't reflected in the browser

**Comment by madromas** [comment]
Also, on the new posts that loads, the pictures become not clickable anymore.....

`esoTalk-v3 there i tried to change the default.master.php file from core/views`

Let me take a look, refresh my memory

**Comment by madromas** [comment]
The only reason why changes will not update in the browser is if you placed a JS code that has errors in it.

**Comment by ac-mmi** [comment]
when loading new images there is this one class `.ajax-modal-ready` missing that might not opening the modal
Cause i tried to add this class in the newly loaded post and it worked

**Comment by madromas** [comment]
That's the thing. Modal loads in the beginning when site loads, Than when new posts load, modal is missing. Gotta include that modal in there somehow. No big deal, I will try to figure it out....

And If I were you, I would not use that EsoTalk. There is an error there, that I cannot figure out, and it will only work on 8.1.
I think some tables not installing during installation. Anyway its a headache.

**Comment by madromas** [comment]
I fixed the missing `.ajax-modal-ready` , they open fine, just not in MODAL window... uuugggghhh

Need to load modal.js upon new post load. But that's not important....

Thank you for your help

**Comment by ac-mmi** [comment]
Could you please close this issue? It would be helpful for me as I am new to this platform.

**Comment by madromas** [comment]
> Could you please close this issue? It would be helpful for me as I am new to this platform.

In esoTalk, change this line to FALSE

https://github.com/madromas/esoTalk-v3/commit/39ed584726878ac1641f02a6228bfae1e822f34f

Let me know if it works. I will close this issue...

**Comment by madromas** [comment]
> Could you please close this issue? It would be helpful for me as I am new to this platform.

I just checked EsoTalk and everything now working

Also delete this file core/views/default.master.php

And to edit default.master. Each Skin has it's own default master here:

addons/skins/Dark/views/default.master.php
